

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "36", "38", "48", "50", "55", "56", "57"],
		"CDFG" : "top_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "37273", "EstimateLatencyMax" : "37273",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "A_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_215", "Port" : "A", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "C", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "C_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "C_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "C", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "A_DRAM", "Type" : "None", "Direction" : "I"},
			{"Name" : "C_DRAM", "Type" : "None", "Direction" : "I"},
			{"Name" : "denom_row", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_215", "Port" : "denom_row", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "denom_row", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_7", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_215", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_7", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_7", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_6", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_215", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_6", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_6", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_5", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_215", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_5", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_5", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_4", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_215", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_4", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_4", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_215", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_3", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_3", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_215", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_2", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_2", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_215", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_1", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_1", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_215", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "38", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Inst_start_state" : "13", "Inst_end_state" : "14"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_7", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_75_7_fu_286", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_7", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_7", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_6", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_75_7_fu_286", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_6", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_6", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_5", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_75_7_fu_286", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_5", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_5", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_4", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_75_7_fu_286", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_4", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_4", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_75_7_fu_286", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_3", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_3", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_75_7_fu_286", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_2", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_2", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_75_7_fu_286", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_1", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_1", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_75_7_fu_286", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem", "Inst_start_state" : "15", "Inst_end_state" : "16"},
					{"ID" : "50", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem", "Inst_start_state" : "18", "Inst_end_state" : "19"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.denom_row_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_7_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_6_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_5_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_4_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_3_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_2_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_1_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_7_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_6_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_5_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_4_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_3_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_2_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_1_U", "Parent" : "0"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_U", "Parent" : "0"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_sum_U", "Parent" : "0"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_sum_1_U", "Parent" : "0"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_sum_2_U", "Parent" : "0"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_sum_3_U", "Parent" : "0"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_sum_4_U", "Parent" : "0"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_sum_5_U", "Parent" : "0"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_sum_6_U", "Parent" : "0"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_sum_7_U", "Parent" : "0"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_38_1_fu_195", "Parent" : "0", "Child" : ["35"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_38_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "66", "EstimateLatencyMax" : "66",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_sum_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_sum_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_sum_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_sum_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_sum_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_sum_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "col_sum", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_38_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_38_1_fu_195.flow_control_loop_pipe_sequential_init_U", "Parent" : "34"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_215", "Parent" : "0", "Child" : ["37"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16387", "EstimateLatencyMax" : "16387",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "A_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln44", "Type" : "None", "Direction" : "I"},
			{"Name" : "denom_row", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_44_2_VITIS_LOOP_46_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_215.flow_control_loop_pipe_sequential_init_U", "Parent" : "36"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240", "Parent" : "0", "Child" : ["39", "40", "41", "42", "43", "44", "45", "46", "47"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4140", "EstimateLatencyMax" : "4140",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_7", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "col_sum_6", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "col_sum_5", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "col_sum_4", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "col_sum_3", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "col_sum_2", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "col_sum_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "col_sum", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "denom_row", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_57_4_VITIS_LOOP_60_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter22", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter22", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240.sdiv_38ns_24s_38_42_1_U20", "Parent" : "38"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240.sdiv_38ns_24s_38_42_1_U21", "Parent" : "38"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240.sdiv_38ns_24s_38_42_1_U22", "Parent" : "38"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240.sdiv_38ns_24s_38_42_1_U23", "Parent" : "38"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240.sdiv_38ns_24s_38_42_1_U24", "Parent" : "38"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240.sdiv_38ns_24s_38_42_1_U25", "Parent" : "38"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240.sdiv_38ns_24s_38_42_1_U26", "Parent" : "38"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240.sdiv_38ns_24s_38_42_1_U27", "Parent" : "38"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_57_4_VITIS_LOOP_60_5_fu_240.flow_control_loop_pipe_sequential_init_U", "Parent" : "38"},
	{"ID" : "48", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_75_7_fu_286", "Parent" : "0", "Child" : ["49"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_75_7",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_75_7", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_75_7_fu_286.flow_control_loop_pipe_sequential_init_U", "Parent" : "48"},
	{"ID" : "50", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314", "Parent" : "0", "Child" : ["51", "52", "53", "54"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16647", "EstimateLatencyMax" : "16647",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "C", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "C_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln87", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_scale_mem", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_87_9_VITIS_LOOP_90_10", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314.sparsemux_17_3_24_1_1_U70", "Parent" : "50"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314.sparsemux_17_3_17_1_1_U71", "Parent" : "50"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314.mul_24s_17s_41_5_1_U72", "Parent" : "50"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_87_9_VITIS_LOOP_90_10_fu_314.flow_control_loop_pipe_sequential_init_U", "Parent" : "50"},
	{"ID" : "55", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "56", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_m_axi_U", "Parent" : "0"},
	{"ID" : "57", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_m_axi_U", "Parent" : "0"}]}
