

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "20", "38", "48", "53", "54", "55"],
		"CDFG" : "top_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "34901", "EstimateLatencyMax" : "34901",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "A_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_657", "Port" : "A", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "C", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "C_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "C_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916", "Port" : "C", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "A_DRAM", "Type" : "None", "Direction" : "I"},
			{"Name" : "C_DRAM", "Type" : "None", "Direction" : "I"},
			{"Name" : "denom_row", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_657", "Port" : "denom_row", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "denom_row", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_7", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_657", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_7", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_7", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_6", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_657", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_6", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_6", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_5", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_657", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_5", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_5", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_4", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_657", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_4", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_4", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_657", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_3", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_3", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_657", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_2", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_2", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_657", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_1", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_1", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_657", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "20", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Inst_start_state" : "17", "Inst_end_state" : "18"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.denom_row_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_7_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_6_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_5_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_4_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_3_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_2_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_1_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_657", "Parent" : "0", "Child" : ["19"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16387", "EstimateLatencyMax" : "16387",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "A_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln44", "Type" : "None", "Direction" : "I"},
			{"Name" : "denom_row", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_44_2_VITIS_LOOP_46_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_44_2_VITIS_LOOP_46_3_fu_657.flow_control_loop_pipe_sequential_init_U", "Parent" : "18"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682", "Parent" : "0", "Child" : ["21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_60_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2091", "EstimateLatencyMax" : "2091",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_1_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_2_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_3_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_4_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_5_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_6_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_7_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_8_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_9_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_10_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_11_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_12_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_13_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_14_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_15_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_16_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_17_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_18_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_19_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_20_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_21_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_22_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_23_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_24_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_25_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_26_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_27_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_28_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_29_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_30_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_31_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_32_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_33_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_34_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_35_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_36_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_37_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_38_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_39_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_40_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_41_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_42_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_43_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_44_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_45_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_46_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_47_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_48_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_49_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_50_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_51_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_52_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_53_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_54_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_55_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_56_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_57_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_58_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_59_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_60_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_61_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_62_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_63_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "denom_row", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_A_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_60_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter42", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter42", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sdiv_38ns_24s_38_42_1_U12", "Parent" : "20"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sdiv_38ns_24s_38_42_1_U13", "Parent" : "20"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sdiv_38ns_24s_38_42_1_U14", "Parent" : "20"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sdiv_38ns_24s_38_42_1_U15", "Parent" : "20"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sdiv_38ns_24s_38_42_1_U16", "Parent" : "20"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sdiv_38ns_24s_38_42_1_U17", "Parent" : "20"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sdiv_38ns_24s_38_42_1_U18", "Parent" : "20"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sdiv_38ns_24s_38_42_1_U19", "Parent" : "20"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sparsemux_17_3_24_1_1_U20", "Parent" : "20"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sparsemux_17_3_24_1_1_U21", "Parent" : "20"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sparsemux_17_3_24_1_1_U22", "Parent" : "20"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sparsemux_17_3_24_1_1_U23", "Parent" : "20"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sparsemux_17_3_24_1_1_U24", "Parent" : "20"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sparsemux_17_3_24_1_1_U25", "Parent" : "20"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sparsemux_17_3_24_1_1_U26", "Parent" : "20"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.sparsemux_17_3_24_1_1_U27", "Parent" : "20"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_4_fu_682.flow_control_loop_pipe_sequential_init_U", "Parent" : "20"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_79_6_fu_784", "Parent" : "0", "Child" : ["39", "40", "41", "42", "43", "44", "45", "46", "47"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_79_6",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_8_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_16_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_24_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_32_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_40_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_48_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_56_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_1_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_9_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_17_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_25_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_33_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_41_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_49_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_57_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_2_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_10_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_18_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_26_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_34_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_42_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_50_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_58_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_3_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_11_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_19_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_27_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_35_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_43_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_51_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_59_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_4_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_12_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_20_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_28_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_36_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_44_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_52_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_60_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_5_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_13_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_21_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_29_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_37_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_45_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_53_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_61_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_6_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_14_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_22_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_30_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_38_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_46_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_54_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_62_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_7_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_15_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_23_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_31_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_39_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_47_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_55_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_63_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_63_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_62_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_61_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_60_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_59_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_58_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_57_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_56_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_55_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_54_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_53_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_52_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_51_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_50_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_49_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_48_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_47_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_46_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_45_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_44_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_43_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_42_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_41_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_40_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_39_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_38_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_37_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_36_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_35_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_34_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_33_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_32_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_31_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_30_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_29_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_28_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_27_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_26_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_25_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_24_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_23_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_22_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_21_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_20_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_19_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_18_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_17_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_16_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_15_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_14_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_12_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_10_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_9_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_7_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_79_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_79_6_fu_784.sparsemux_17_6_24_1_1_U111", "Parent" : "38"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_79_6_fu_784.sparsemux_17_6_24_1_1_U112", "Parent" : "38"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_79_6_fu_784.sparsemux_17_6_24_1_1_U113", "Parent" : "38"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_79_6_fu_784.sparsemux_17_6_24_1_1_U114", "Parent" : "38"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_79_6_fu_784.sparsemux_17_6_24_1_1_U115", "Parent" : "38"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_79_6_fu_784.sparsemux_17_6_24_1_1_U116", "Parent" : "38"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_79_6_fu_784.sparsemux_17_6_24_1_1_U117", "Parent" : "38"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_79_6_fu_784.sparsemux_17_6_24_1_1_U118", "Parent" : "38"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_79_6_fu_784.flow_control_loop_pipe_sequential_init_U", "Parent" : "38"},
	{"ID" : "48", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916", "Parent" : "0", "Child" : ["49", "50", "51", "52"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16391", "EstimateLatencyMax" : "16391",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "C", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "C_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln89", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_3_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_4_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_5_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_6_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_7_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_8_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_9_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_10_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_11_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_12_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_13_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_14_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_15_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_16_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_17_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_18_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_19_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_20_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_21_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_22_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_23_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_24_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_25_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_26_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_27_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_28_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_29_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_30_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_31_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_32_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_33_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_34_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_35_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_36_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_37_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_38_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_39_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_40_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_41_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_42_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_43_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_44_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_45_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_46_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_47_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_48_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_49_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_50_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_51_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_52_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_53_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_54_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_55_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_56_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_57_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_58_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_59_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_60_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_61_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_62_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_63_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_89_8_VITIS_LOOP_90_9", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916.mul_24s_24s_48_5_1_U248", "Parent" : "48"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916.sparsemux_129_6_24_1_1_U249", "Parent" : "48"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916.sparsemux_17_3_24_1_1_U250", "Parent" : "48"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_89_8_VITIS_LOOP_90_9_fu_916.flow_control_loop_pipe_sequential_init_U", "Parent" : "48"},
	{"ID" : "53", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "54", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_m_axi_U", "Parent" : "0"},
	{"ID" : "55", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_m_axi_U", "Parent" : "0"}]}
