

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "19", "29", "47", "54", "55", "56"],
		"CDFG" : "top_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "48160", "EstimateLatencyMax" : "48160",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "A_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "17", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_60_3_fu_709", "Port" : "A", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "C", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "C_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "C_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "47", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951", "Port" : "C", "Inst_start_state" : "16", "Inst_end_state" : "17"}]},
			{"Name" : "A_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "C_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "29", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "47", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Inst_start_state" : "16", "Inst_end_state" : "17"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "29", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "47", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Inst_start_state" : "16", "Inst_end_state" : "17"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "29", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "47", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Inst_start_state" : "16", "Inst_end_state" : "17"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "29", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "47", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Inst_start_state" : "16", "Inst_end_state" : "17"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "29", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "47", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Inst_start_state" : "16", "Inst_end_state" : "17"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "29", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "47", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Inst_start_state" : "16", "Inst_end_state" : "17"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "29", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "47", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Inst_start_state" : "16", "Inst_end_state" : "17"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "29", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "47", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Inst_start_state" : "16", "Inst_end_state" : "17"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_57_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "22", "FirstState" : "ap_ST_fsm_state10", "LastState" : ["ap_ST_fsm_state13"], "QuitState" : ["ap_ST_fsm_state10"], "PreState" : ["ap_ST_fsm_state9"], "PostState" : ["ap_ST_fsm_state14"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_1_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_2_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_3_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_4_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_5_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_6_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_7_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_3_fu_709", "Parent" : "0", "Child" : ["18"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_60_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "67", "EstimateLatencyMax" : "67",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "A_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln57", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_buf_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_buf_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_buf_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_buf_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_buf_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_buf_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_buf", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_60_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_60_3_fu_709.flow_control_loop_pipe_sequential_init_U", "Parent" : "17"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_83_6_fu_725", "Parent" : "0", "Child" : ["20", "21", "22", "23", "24", "25", "26", "27", "28"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_83_6",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_8_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_16_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_24_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_32_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_40_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_48_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_56_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_1_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_9_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_17_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_25_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_33_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_41_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_49_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_57_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_2_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_10_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_18_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_26_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_34_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_42_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_50_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_58_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_3_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_11_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_19_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_27_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_35_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_43_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_51_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_59_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_4_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_12_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_20_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_28_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_36_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_44_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_52_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_60_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_5_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_13_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_21_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_29_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_37_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_45_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_53_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_61_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_6_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_14_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_22_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_30_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_38_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_46_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_54_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_62_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_7_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_15_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_23_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_31_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_39_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_47_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_55_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_63_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_63_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_62_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_61_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_60_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_59_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_58_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_57_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_56_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_55_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_54_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_53_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_52_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_51_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_50_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_49_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_48_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_47_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_46_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_45_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_44_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_43_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_42_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_41_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_40_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_39_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_38_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_37_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_36_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_35_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_34_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_33_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_32_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_31_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_30_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_29_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_28_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_27_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_26_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_25_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_24_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_23_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_22_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_21_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_20_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_19_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_18_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_17_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_16_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_15_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_14_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_12_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_10_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_9_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_7_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_83_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_83_6_fu_725.sparsemux_17_6_24_1_1_U112", "Parent" : "19"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_83_6_fu_725.sparsemux_17_6_24_1_1_U113", "Parent" : "19"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_83_6_fu_725.sparsemux_17_6_24_1_1_U114", "Parent" : "19"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_83_6_fu_725.sparsemux_17_6_24_1_1_U115", "Parent" : "19"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_83_6_fu_725.sparsemux_17_6_24_1_1_U116", "Parent" : "19"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_83_6_fu_725.sparsemux_17_6_24_1_1_U117", "Parent" : "19"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_83_6_fu_725.sparsemux_17_6_24_1_1_U118", "Parent" : "19"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_83_6_fu_725.sparsemux_17_6_24_1_1_U119", "Parent" : "19"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_83_6_fu_725.flow_control_loop_pipe_sequential_init_U", "Parent" : "19"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857", "Parent" : "0", "Child" : ["30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_69_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "53", "EstimateLatencyMax" : "53",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "conv_i343", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_15", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_23", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_31", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_39", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_47", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_55", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_63", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_22", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_30", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_38", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_46", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_54", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_62", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_21", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_29", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_37", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_45", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_53", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_61", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_20", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_28", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_36", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_44", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_52", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_60", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_19", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_27", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_35", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_43", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_51", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_59", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_18", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_26", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_34", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_42", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_50", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_58", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_9", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_17", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_25", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_33", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_41", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_49", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_57", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "i", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_56", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_48", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_40", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_32", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_24", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_16", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_69_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter44", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter44", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sdiv_38ns_24s_38_42_1_U12", "Parent" : "29"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sdiv_38ns_24s_38_42_1_U13", "Parent" : "29"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sdiv_38ns_24s_38_42_1_U14", "Parent" : "29"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sdiv_38ns_24s_38_42_1_U15", "Parent" : "29"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sdiv_38ns_24s_38_42_1_U16", "Parent" : "29"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sdiv_38ns_24s_38_42_1_U17", "Parent" : "29"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sdiv_38ns_24s_38_42_1_U18", "Parent" : "29"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sdiv_38ns_24s_38_42_1_U19", "Parent" : "29"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sparsemux_17_6_24_1_1_U20", "Parent" : "29"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sparsemux_17_6_24_1_1_U21", "Parent" : "29"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sparsemux_17_6_24_1_1_U22", "Parent" : "29"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sparsemux_17_6_24_1_1_U23", "Parent" : "29"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sparsemux_17_6_24_1_1_U24", "Parent" : "29"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sparsemux_17_6_24_1_1_U25", "Parent" : "29"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sparsemux_17_6_24_1_1_U26", "Parent" : "29"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.sparsemux_17_6_24_1_1_U27", "Parent" : "29"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_69_4_fu_857.flow_control_loop_pipe_sequential_init_U", "Parent" : "29"},
	{"ID" : "47", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951", "Parent" : "0", "Child" : ["48", "49", "50", "51", "52", "53"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16388", "EstimateLatencyMax" : "16388",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "C", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "C_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln93", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_4_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_6_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_8_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_10_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_12_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_14_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_16_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_18_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_20_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_22_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_24_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_26_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_28_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_30_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_32_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_34_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_36_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_38_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_40_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_42_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_44_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_46_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_48_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_50_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_52_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_54_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_56_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_58_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_60_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_62_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_3_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_5_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_7_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_9_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_11_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_13_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_15_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_17_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_19_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_21_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_23_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_25_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_27_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_29_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_31_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_33_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_35_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_37_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_39_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_41_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_43_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_45_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_47_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_49_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_51_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_53_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_55_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_57_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_59_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_61_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_63_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_93_8_VITIS_LOOP_94_9", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951.mul_24s_24s_48_1_1_U248", "Parent" : "47"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951.sparsemux_65_6_24_1_1_U249", "Parent" : "47"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951.sparsemux_65_6_24_1_1_U250", "Parent" : "47"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951.sparsemux_9_3_24_1_1_U251", "Parent" : "47"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951.sparsemux_9_3_24_1_1_U252", "Parent" : "47"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_93_8_VITIS_LOOP_94_9_fu_951.flow_control_loop_pipe_sequential_init_U", "Parent" : "47"},
	{"ID" : "54", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "55", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_m_axi_U", "Parent" : "0"},
	{"ID" : "56", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_m_axi_U", "Parent" : "0"}]}
