

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "14", "16", "22", "32", "42", "44", "45", "46"],
		"CDFG" : "top_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "70448", "EstimateLatencyMax" : "70448",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "A_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "12", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_34_2_fu_705", "Port" : "A", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "C", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "C_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "C_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "42", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_114_13_VITIS_LOOP_115_14_fu_1016", "Port" : "C", "Inst_start_state" : "19", "Inst_end_state" : "20"}]},
			{"Name" : "A_DRAM", "Type" : "None", "Direction" : "I"},
			{"Name" : "C_DRAM", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "32", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "32", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "32", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "22", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "32", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Inst_start_state" : "17", "Inst_end_state" : "18"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_63_4", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "25", "FirstState" : "ap_ST_fsm_state12", "LastState" : ["ap_ST_fsm_state15"], "QuitState" : ["ap_ST_fsm_state12"], "PreState" : ["ap_ST_fsm_state11"], "PostState" : ["ap_ST_fsm_state16"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_1_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_1_36_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_1_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_1_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_2_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_buf_3_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_34_2_fu_705", "Parent" : "0", "Child" : ["13"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_34_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16387", "EstimateLatencyMax" : "16387",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "A_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln33", "Type" : "None", "Direction" : "I"},
			{"Name" : "A_1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_33_1_VITIS_LOOP_34_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_34_2_fu_705.flow_control_loop_pipe_sequential_init_U", "Parent" : "12"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_67_5_fu_713", "Parent" : "0", "Child" : ["15"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_67_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "66", "EstimateLatencyMax" : "66",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "zext_ln69", "Type" : "None", "Direction" : "I"},
			{"Name" : "A_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_buf_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_buf_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_buf_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "row_buf", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_67_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_67_5_fu_713.flow_control_loop_pipe_sequential_init_U", "Parent" : "14"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_92_8_fu_724", "Parent" : "0", "Child" : ["17", "18", "19", "20", "21"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_92_8",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "18", "EstimateLatencyMax" : "18",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_4_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_8_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_12_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_16_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_20_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_24_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_28_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_32_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_36_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_40_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_44_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_48_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_52_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_56_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_60_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_1_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_5_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_9_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_13_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_17_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_21_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_25_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_29_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_33_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_37_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_41_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_45_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_49_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_53_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_57_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_61_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_2_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_6_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_10_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_14_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_18_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_22_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_26_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_30_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_34_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_38_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_42_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_46_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_50_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_54_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_58_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_62_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_3_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_7_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_11_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_15_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_19_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_23_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_27_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_31_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_35_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_39_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_43_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_47_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_51_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_55_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_59_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_63_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_63_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_62_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_61_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_60_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_59_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_58_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_57_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_56_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_55_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_54_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_53_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_52_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_51_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_50_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_49_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_48_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_47_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_46_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_45_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_44_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_43_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_42_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_41_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_40_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_39_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_38_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_37_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_36_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_35_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_34_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_33_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_32_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_31_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_30_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_29_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_28_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_27_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_26_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_25_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_24_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_23_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_22_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_21_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_20_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_19_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_18_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_17_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_16_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_15_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_14_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_12_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_10_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_9_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_7_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_92_8", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_92_8_fu_724.sparsemux_33_6_24_1_1_U95", "Parent" : "16"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_92_8_fu_724.sparsemux_33_6_24_1_1_U96", "Parent" : "16"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_92_8_fu_724.sparsemux_33_6_24_1_1_U97", "Parent" : "16"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_92_8_fu_724.sparsemux_33_6_24_1_1_U98", "Parent" : "16"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_92_8_fu_724.flow_control_loop_pipe_sequential_init_U", "Parent" : "16"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856", "Parent" : "0", "Child" : ["23", "24", "25", "26", "27", "28", "29", "30", "31"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_78_6",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "61", "EstimateLatencyMax" : "61",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "conv_i347", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_15", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_19", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_23", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_27", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_31", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_35", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_39", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_43", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_47", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_51", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_55", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_59", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_63", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_18", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_22", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_26", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_30", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_34", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_38", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_42", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_46", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_50", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_54", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_58", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_62", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_9", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_17", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_21", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_25", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_29", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_33", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_37", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_41", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_45", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_49", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_53", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_57", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_61", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "i_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_60", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_56", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_52", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_48", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_44", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_40", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_36", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_32", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_28", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_24", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_20", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_16", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_78_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter44", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter44", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856.sdiv_38ns_24s_38_42_1_U11", "Parent" : "22"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856.sdiv_38ns_24s_38_42_1_U12", "Parent" : "22"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856.sdiv_38ns_24s_38_42_1_U13", "Parent" : "22"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856.sdiv_38ns_24s_38_42_1_U14", "Parent" : "22"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856.sparsemux_33_6_24_1_1_U15", "Parent" : "22"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856.sparsemux_33_6_24_1_1_U16", "Parent" : "22"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856.sparsemux_33_6_24_1_1_U17", "Parent" : "22"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856.sparsemux_33_6_24_1_1_U18", "Parent" : "22"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_78_6_fu_856.flow_control_loop_pipe_sequential_init_U", "Parent" : "22"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938", "Parent" : "0", "Child" : ["33", "34", "35", "36", "37", "38", "39", "40", "41"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4099", "EstimateLatencyMax" : "4099",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "C_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "C_1_16", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "scale_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_4_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_8_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_12_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_16_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_20_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_24_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_28_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_32_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_36_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_40_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_44_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_48_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_52_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_56_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_60_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_5_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_9_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_13_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_17_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_21_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_25_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_29_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_33_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_37_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_41_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_45_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_49_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_53_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_57_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_61_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_6_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_10_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_14_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_18_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_22_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_26_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_30_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_34_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_38_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_42_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_46_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_50_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_54_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_58_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_62_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_3_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_7_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_11_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_15_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_19_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_23_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_27_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_31_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_35_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_39_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_43_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_47_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_51_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_55_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_59_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_63_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_102_10_VITIS_LOOP_103_11", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938.mul_24s_24s_48_1_1_U227", "Parent" : "32"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938.mul_24s_24s_48_1_1_U228", "Parent" : "32"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938.mul_24s_24s_48_1_1_U229", "Parent" : "32"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938.mul_24s_24s_48_1_1_U230", "Parent" : "32"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938.sparsemux_33_6_24_1_1_U231", "Parent" : "32"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938.sparsemux_33_6_24_1_1_U232", "Parent" : "32"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938.sparsemux_33_6_24_1_1_U233", "Parent" : "32"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938.sparsemux_33_6_24_1_1_U234", "Parent" : "32"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_102_10_VITIS_LOOP_103_11_fu_938.flow_control_loop_pipe_sequential_init_U", "Parent" : "32"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_114_13_VITIS_LOOP_115_14_fu_1016", "Parent" : "0", "Child" : ["43"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_114_13_VITIS_LOOP_115_14",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16387", "EstimateLatencyMax" : "16387",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "C", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "C_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln114", "Type" : "None", "Direction" : "I"},
			{"Name" : "C_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "C_1_15", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_114_13_VITIS_LOOP_115_14", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_114_13_VITIS_LOOP_115_14_fu_1016.flow_control_loop_pipe_sequential_init_U", "Parent" : "42"},
	{"ID" : "44", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "45", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_m_axi_U", "Parent" : "0"},
	{"ID" : "46", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.C_m_axi_U", "Parent" : "0"}]}
