-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_kernel_top_kernel_Pipeline_VITIS_LOOP_109_12_VITIS_LOOP_110_1318 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    C_4_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    C_4_ce0 : OUT STD_LOGIC;
    C_4_we0 : OUT STD_LOGIC;
    C_4_d0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    scale_4_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_8_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_12_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_16_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_20_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_24_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_28_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_32_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_36_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_40_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_44_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_48_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_52_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_56_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_60_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_ce0 : OUT STD_LOGIC;
    top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_q0 : IN STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of top_kernel_top_kernel_Pipeline_VITIS_LOOP_109_12_VITIS_LOOP_110_1318 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_4 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_800 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv7_8 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv24_7FFFFF : STD_LOGIC_VECTOR (23 downto 0) := "011111111111111111111111";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln109_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln112_fu_406_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln112_reg_744 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln112_reg_744_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_23_fu_411_p33 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_23_reg_754 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln112_12_fu_711_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln112_12_reg_759 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal j_fu_178 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln110_fu_479_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (6 downto 0);
    signal i_fu_182 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal select_ln109_fu_376_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (8 downto 0);
    signal indvar_flatten139_fu_186 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln109_fu_334_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten139_load : STD_LOGIC_VECTOR (11 downto 0);
    signal top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_ce0_local : STD_LOGIC;
    signal C_4_we0_local : STD_LOGIC;
    signal C_4_ce0_local : STD_LOGIC;
    signal tmp_fu_356_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln109_fu_346_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln110_fu_364_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln109_4_fu_350_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln110_fu_384_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln110_4_fu_388_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_398_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_23_fu_411_p31 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln109_fu_372_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln112_fu_306_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_53_fu_527_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln112_4_fu_517_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln112_4_fu_543_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln112_fu_547_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_55_fu_553_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_fu_535_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_fu_561_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_581_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_25_fu_595_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln112_fu_567_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_9_fu_603_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_10_fu_609_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_56_fu_573_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_13_fu_623_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_16_fu_629_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln112_fu_615_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_14_fu_649_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_52_fu_509_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln112_fu_655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_15_fu_661_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln112_10_fu_635_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_17_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_19_fu_673_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln112_7_fu_679_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_16_fu_685_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_18_fu_667_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_20_fu_691_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln112_8_fu_705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln112_11_fu_697_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_23_fu_411_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p21 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p23 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p25 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_23_fu_411_p29 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component top_kernel_mul_24s_24s_48_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component top_kernel_sparsemux_31_6_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (5 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (5 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (5 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (5 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (5 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (5 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (5 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (5 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (5 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (5 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (5 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (5 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (5 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (5 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (5 downto 0);
        din14_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        din3 : IN STD_LOGIC_VECTOR (23 downto 0);
        din4 : IN STD_LOGIC_VECTOR (23 downto 0);
        din5 : IN STD_LOGIC_VECTOR (23 downto 0);
        din6 : IN STD_LOGIC_VECTOR (23 downto 0);
        din7 : IN STD_LOGIC_VECTOR (23 downto 0);
        din8 : IN STD_LOGIC_VECTOR (23 downto 0);
        din9 : IN STD_LOGIC_VECTOR (23 downto 0);
        din10 : IN STD_LOGIC_VECTOR (23 downto 0);
        din11 : IN STD_LOGIC_VECTOR (23 downto 0);
        din12 : IN STD_LOGIC_VECTOR (23 downto 0);
        din13 : IN STD_LOGIC_VECTOR (23 downto 0);
        din14 : IN STD_LOGIC_VECTOR (23 downto 0);
        def : IN STD_LOGIC_VECTOR (23 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component top_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_24s_24s_48_1_1_U3049 : component top_kernel_mul_24s_24s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        dout_WIDTH => 48)
    port map (
        din0 => tmp_23_reg_754,
        din1 => top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_q0,
        dout => mul_ln112_fu_306_p2);

    sparsemux_31_6_24_1_1_U3050 : component top_kernel_sparsemux_31_6_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000100",
        din0_WIDTH => 24,
        CASE1 => "001000",
        din1_WIDTH => 24,
        CASE2 => "001100",
        din2_WIDTH => 24,
        CASE3 => "010000",
        din3_WIDTH => 24,
        CASE4 => "010100",
        din4_WIDTH => 24,
        CASE5 => "011000",
        din5_WIDTH => 24,
        CASE6 => "011100",
        din6_WIDTH => 24,
        CASE7 => "100000",
        din7_WIDTH => 24,
        CASE8 => "100100",
        din8_WIDTH => 24,
        CASE9 => "101000",
        din9_WIDTH => 24,
        CASE10 => "101100",
        din10_WIDTH => 24,
        CASE11 => "110000",
        din11_WIDTH => 24,
        CASE12 => "110100",
        din12_WIDTH => 24,
        CASE13 => "111000",
        din13_WIDTH => 24,
        CASE14 => "111100",
        din14_WIDTH => 24,
        def_WIDTH => 24,
        sel_WIDTH => 6,
        dout_WIDTH => 24)
    port map (
        din0 => scale_4_reload,
        din1 => scale_8_reload,
        din2 => scale_12_reload,
        din3 => scale_16_reload,
        din4 => scale_20_reload,
        din5 => scale_24_reload,
        din6 => scale_28_reload,
        din7 => scale_32_reload,
        din8 => scale_36_reload,
        din9 => scale_40_reload,
        din10 => scale_44_reload,
        din11 => scale_48_reload,
        din12 => scale_52_reload,
        din13 => scale_56_reload,
        din14 => scale_60_reload,
        def => tmp_23_fu_411_p31,
        sel => select_ln110_fu_364_p3,
        dout => tmp_23_fu_411_p33);

    flow_control_loop_pipe_sequential_init_U : component top_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln109_fu_328_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_182 <= select_ln109_fu_376_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_182 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten139_fu_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln109_fu_328_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten139_fu_186 <= add_ln109_fu_334_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten139_fu_186 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln109_fu_328_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_178 <= add_ln110_fu_479_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_178 <= ap_const_lv7_4;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                select_ln112_12_reg_759 <= select_ln112_12_fu_711_p3;
                tmp_23_reg_754 <= tmp_23_fu_411_p33;
                    zext_ln112_reg_744(10 downto 0) <= zext_ln112_fu_406_p1(10 downto 0);
                    zext_ln112_reg_744_pp0_iter1_reg(10 downto 0) <= zext_ln112_reg_744(10 downto 0);
            end if;
        end if;
    end process;
    zext_ln112_reg_744(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln112_reg_744_pp0_iter1_reg(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    C_4_address0 <= zext_ln112_reg_744_pp0_iter1_reg(11 - 1 downto 0);
    C_4_ce0 <= C_4_ce0_local;

    C_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            C_4_ce0_local <= ap_const_logic_1;
        else 
            C_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_4_d0 <= select_ln112_12_reg_759;
    C_4_we0 <= C_4_we0_local;

    C_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            C_4_we0_local <= ap_const_logic_1;
        else 
            C_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln109_4_fu_350_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv9_1));
    add_ln109_fu_334_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten139_load) + unsigned(ap_const_lv12_1));
    add_ln110_fu_479_p2 <= std_logic_vector(unsigned(zext_ln109_fu_372_p1) + unsigned(ap_const_lv7_8));
    add_ln112_fu_547_p2 <= std_logic_vector(unsigned(trunc_ln112_4_fu_517_p4) + unsigned(zext_ln112_4_fu_543_p1));
    and_ln112_16_fu_629_p2 <= (xor_ln112_13_fu_623_p2 and icmp_ln112_fu_589_p2);
    and_ln112_17_fu_643_p2 <= (icmp_ln112_9_fu_603_p2 and and_ln112_fu_567_p2);
    and_ln112_18_fu_667_p2 <= (xor_ln112_15_fu_661_p2 and or_ln112_fu_655_p2);
    and_ln112_19_fu_673_p2 <= (tmp_55_fu_553_p3 and select_ln112_10_fu_635_p3);
    and_ln112_20_fu_691_p2 <= (xor_ln112_16_fu_685_p2 and tmp_52_fu_509_p3);
    and_ln112_fu_567_p2 <= (xor_ln112_fu_561_p2 and tmp_54_fu_535_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln109_fu_328_p2)
    begin
        if (((icmp_ln109_fu_328_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_182)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_182;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten139_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten139_fu_186)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten139_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten139_load <= indvar_flatten139_fu_186;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_178, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv7_4;
        else 
            ap_sig_allocacmp_j_load <= j_fu_178;
        end if; 
    end process;

    icmp_ln109_fu_328_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten139_load = ap_const_lv12_800) else "0";
    icmp_ln112_10_fu_609_p2 <= "1" when (tmp_25_fu_595_p3 = ap_const_lv8_0) else "0";
    icmp_ln112_9_fu_603_p2 <= "1" when (tmp_25_fu_595_p3 = ap_const_lv8_FF) else "0";
    icmp_ln112_fu_589_p2 <= "1" when (tmp_24_fu_581_p3 = ap_const_lv7_7F) else "0";
    lshr_ln110_4_fu_388_p4 <= select_ln110_fu_364_p3(5 downto 3);
    or_ln112_7_fu_679_p2 <= (and_ln112_19_fu_673_p2 or and_ln112_17_fu_643_p2);
    or_ln112_8_fu_705_p2 <= (and_ln112_20_fu_691_p2 or and_ln112_18_fu_667_p2);
    or_ln112_fu_655_p2 <= (xor_ln112_14_fu_649_p2 or tmp_55_fu_553_p3);
    select_ln109_fu_376_p3 <= 
        add_ln109_4_fu_350_p2 when (tmp_fu_356_p3(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln110_fu_364_p3 <= 
        ap_const_lv6_4 when (tmp_fu_356_p3(0) = '1') else 
        trunc_ln109_fu_346_p1;
    select_ln112_10_fu_635_p3 <= 
        and_ln112_16_fu_629_p2 when (and_ln112_fu_567_p2(0) = '1') else 
        icmp_ln112_9_fu_603_p2;
    select_ln112_11_fu_697_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln112_18_fu_667_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln112_12_fu_711_p3 <= 
        select_ln112_11_fu_697_p3 when (or_ln112_8_fu_705_p2(0) = '1') else 
        add_ln112_fu_547_p2;
    select_ln112_fu_615_p3 <= 
        icmp_ln112_9_fu_603_p2 when (and_ln112_fu_567_p2(0) = '1') else 
        icmp_ln112_10_fu_609_p2;
    tmp_23_fu_411_p31 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_24_fu_581_p3 <= mul_ln112_fu_306_p2(47 downto 41);
    tmp_25_fu_595_p3 <= mul_ln112_fu_306_p2(47 downto 40);
    tmp_52_fu_509_p3 <= mul_ln112_fu_306_p2(47 downto 47);
    tmp_53_fu_527_p3 <= mul_ln112_fu_306_p2(15 downto 15);
    tmp_54_fu_535_p3 <= mul_ln112_fu_306_p2(39 downto 39);
    tmp_55_fu_553_p3 <= add_ln112_fu_547_p2(23 downto 23);
    tmp_56_fu_573_p3 <= mul_ln112_fu_306_p2(40 downto 40);
    tmp_fu_356_p3 <= ap_sig_allocacmp_j_load(6 downto 6);
    tmp_s_fu_398_p3 <= (trunc_ln110_fu_384_p1 & lshr_ln110_4_fu_388_p4);
    top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_address0 <= zext_ln112_fu_406_p1(11 - 1 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_ce0 <= top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_ce0_local;

    top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_ce0_local <= ap_const_logic_1;
        else 
            top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln109_fu_346_p1 <= ap_sig_allocacmp_j_load(6 - 1 downto 0);
    trunc_ln110_fu_384_p1 <= select_ln109_fu_376_p3(8 - 1 downto 0);
    trunc_ln112_4_fu_517_p4 <= mul_ln112_fu_306_p2(39 downto 16);
    xor_ln112_13_fu_623_p2 <= (tmp_56_fu_573_p3 xor ap_const_lv1_1);
    xor_ln112_14_fu_649_p2 <= (select_ln112_fu_615_p3 xor ap_const_lv1_1);
    xor_ln112_15_fu_661_p2 <= (tmp_52_fu_509_p3 xor ap_const_lv1_1);
    xor_ln112_16_fu_685_p2 <= (or_ln112_7_fu_679_p2 xor ap_const_lv1_1);
    xor_ln112_fu_561_p2 <= (tmp_55_fu_553_p3 xor ap_const_lv1_1);
    zext_ln109_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln110_fu_364_p3),7));
    zext_ln112_4_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_53_fu_527_p3),24));
    zext_ln112_fu_406_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_398_p3),64));
end behav;
