-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_kernel_top_kernel_Pipeline_VITIS_LOOP_109_12_VITIS_LOOP_110_1316 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    C_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    C_2_ce0 : OUT STD_LOGIC;
    C_2_we0 : OUT STD_LOGIC;
    C_2_d0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    scale_2_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_4_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_6_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_8_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_10_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_12_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_14_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_16_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_18_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_20_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_22_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_24_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_26_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_28_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_30_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_32_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_34_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_36_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_38_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_40_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_42_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_44_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_46_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_48_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_50_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_52_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_54_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_56_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_58_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_ce0 : OUT STD_LOGIC;
    top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_q0 : IN STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of top_kernel_top_kernel_Pipeline_VITIS_LOOP_109_12_VITIS_LOOP_110_1316 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_800 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv7_8 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv24_7FFFFF : STD_LOGIC_VECTOR (23 downto 0) := "011111111111111111111111";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln109_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln112_fu_546_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln112_reg_940 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln112_reg_940_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_29_fu_551_p61 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_29_reg_950 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln112_11_fu_907_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln112_11_reg_955 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal j_fu_234 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln110_fu_675_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (6 downto 0);
    signal i_fu_238 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal select_ln109_fu_516_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (8 downto 0);
    signal indvar_flatten125_fu_242 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln109_fu_474_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten125_load : STD_LOGIC_VECTOR (11 downto 0);
    signal top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_ce0_local : STD_LOGIC;
    signal C_2_we0_local : STD_LOGIC;
    signal C_2_ce0_local : STD_LOGIC;
    signal tmp_fu_496_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln109_fu_486_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln110_fu_504_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln109_2_fu_490_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln110_fu_524_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln110_2_fu_528_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_538_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_29_fu_551_p59 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln109_fu_512_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln112_fu_446_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_63_fu_723_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln112_2_fu_713_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln112_2_fu_739_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln112_fu_743_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_65_fu_749_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_64_fu_731_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_10_fu_757_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_777_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_31_fu_791_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln112_12_fu_763_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_7_fu_799_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_8_fu_805_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_66_fu_769_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_6_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_11_fu_819_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_13_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln112_8_fu_811_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_12_fu_845_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_62_fu_705_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln112_4_fu_851_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_13_fu_857_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln112_9_fu_831_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_14_fu_839_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_16_fu_869_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln112_fu_875_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_14_fu_881_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_15_fu_863_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_17_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln112_5_fu_901_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln112_10_fu_893_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_29_fu_551_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p21 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p23 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p25 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p29 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p31 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p33 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p35 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p37 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p39 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p41 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p43 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p45 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p47 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p49 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p51 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p53 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p55 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_29_fu_551_p57 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component top_kernel_mul_24s_24s_48_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component top_kernel_sparsemux_59_6_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (5 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (5 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (5 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (5 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (5 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (5 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (5 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (5 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (5 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (5 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (5 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (5 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (5 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (5 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (5 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (5 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (5 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (5 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (5 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (5 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (5 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (5 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (5 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (5 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (5 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (5 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (5 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (5 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (5 downto 0);
        din28_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        din3 : IN STD_LOGIC_VECTOR (23 downto 0);
        din4 : IN STD_LOGIC_VECTOR (23 downto 0);
        din5 : IN STD_LOGIC_VECTOR (23 downto 0);
        din6 : IN STD_LOGIC_VECTOR (23 downto 0);
        din7 : IN STD_LOGIC_VECTOR (23 downto 0);
        din8 : IN STD_LOGIC_VECTOR (23 downto 0);
        din9 : IN STD_LOGIC_VECTOR (23 downto 0);
        din10 : IN STD_LOGIC_VECTOR (23 downto 0);
        din11 : IN STD_LOGIC_VECTOR (23 downto 0);
        din12 : IN STD_LOGIC_VECTOR (23 downto 0);
        din13 : IN STD_LOGIC_VECTOR (23 downto 0);
        din14 : IN STD_LOGIC_VECTOR (23 downto 0);
        din15 : IN STD_LOGIC_VECTOR (23 downto 0);
        din16 : IN STD_LOGIC_VECTOR (23 downto 0);
        din17 : IN STD_LOGIC_VECTOR (23 downto 0);
        din18 : IN STD_LOGIC_VECTOR (23 downto 0);
        din19 : IN STD_LOGIC_VECTOR (23 downto 0);
        din20 : IN STD_LOGIC_VECTOR (23 downto 0);
        din21 : IN STD_LOGIC_VECTOR (23 downto 0);
        din22 : IN STD_LOGIC_VECTOR (23 downto 0);
        din23 : IN STD_LOGIC_VECTOR (23 downto 0);
        din24 : IN STD_LOGIC_VECTOR (23 downto 0);
        din25 : IN STD_LOGIC_VECTOR (23 downto 0);
        din26 : IN STD_LOGIC_VECTOR (23 downto 0);
        din27 : IN STD_LOGIC_VECTOR (23 downto 0);
        din28 : IN STD_LOGIC_VECTOR (23 downto 0);
        def : IN STD_LOGIC_VECTOR (23 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component top_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_24s_24s_48_1_1_U2955 : component top_kernel_mul_24s_24s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        dout_WIDTH => 48)
    port map (
        din0 => tmp_29_reg_950,
        din1 => top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_q0,
        dout => mul_ln112_fu_446_p2);

    sparsemux_59_6_24_1_1_U2956 : component top_kernel_sparsemux_59_6_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000010",
        din0_WIDTH => 24,
        CASE1 => "000100",
        din1_WIDTH => 24,
        CASE2 => "000110",
        din2_WIDTH => 24,
        CASE3 => "001000",
        din3_WIDTH => 24,
        CASE4 => "001010",
        din4_WIDTH => 24,
        CASE5 => "001100",
        din5_WIDTH => 24,
        CASE6 => "001110",
        din6_WIDTH => 24,
        CASE7 => "010000",
        din7_WIDTH => 24,
        CASE8 => "010010",
        din8_WIDTH => 24,
        CASE9 => "010100",
        din9_WIDTH => 24,
        CASE10 => "010110",
        din10_WIDTH => 24,
        CASE11 => "011000",
        din11_WIDTH => 24,
        CASE12 => "011010",
        din12_WIDTH => 24,
        CASE13 => "011100",
        din13_WIDTH => 24,
        CASE14 => "011110",
        din14_WIDTH => 24,
        CASE15 => "100000",
        din15_WIDTH => 24,
        CASE16 => "100010",
        din16_WIDTH => 24,
        CASE17 => "100100",
        din17_WIDTH => 24,
        CASE18 => "100110",
        din18_WIDTH => 24,
        CASE19 => "101000",
        din19_WIDTH => 24,
        CASE20 => "101010",
        din20_WIDTH => 24,
        CASE21 => "101100",
        din21_WIDTH => 24,
        CASE22 => "101110",
        din22_WIDTH => 24,
        CASE23 => "110000",
        din23_WIDTH => 24,
        CASE24 => "110010",
        din24_WIDTH => 24,
        CASE25 => "110100",
        din25_WIDTH => 24,
        CASE26 => "110110",
        din26_WIDTH => 24,
        CASE27 => "111000",
        din27_WIDTH => 24,
        CASE28 => "111010",
        din28_WIDTH => 24,
        def_WIDTH => 24,
        sel_WIDTH => 6,
        dout_WIDTH => 24)
    port map (
        din0 => scale_2_reload,
        din1 => scale_4_reload,
        din2 => scale_6_reload,
        din3 => scale_8_reload,
        din4 => scale_10_reload,
        din5 => scale_12_reload,
        din6 => scale_14_reload,
        din7 => scale_16_reload,
        din8 => scale_18_reload,
        din9 => scale_20_reload,
        din10 => scale_22_reload,
        din11 => scale_24_reload,
        din12 => scale_26_reload,
        din13 => scale_28_reload,
        din14 => scale_30_reload,
        din15 => scale_32_reload,
        din16 => scale_34_reload,
        din17 => scale_36_reload,
        din18 => scale_38_reload,
        din19 => scale_40_reload,
        din20 => scale_42_reload,
        din21 => scale_44_reload,
        din22 => scale_46_reload,
        din23 => scale_48_reload,
        din24 => scale_50_reload,
        din25 => scale_52_reload,
        din26 => scale_54_reload,
        din27 => scale_56_reload,
        din28 => scale_58_reload,
        def => tmp_29_fu_551_p59,
        sel => select_ln110_fu_504_p3,
        dout => tmp_29_fu_551_p61);

    flow_control_loop_pipe_sequential_init_U : component top_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_238_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln109_fu_468_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_238 <= select_ln109_fu_516_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_238 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten125_fu_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln109_fu_468_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten125_fu_242 <= add_ln109_fu_474_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten125_fu_242 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln109_fu_468_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_234 <= add_ln110_fu_675_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_234 <= ap_const_lv7_2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                select_ln112_11_reg_955 <= select_ln112_11_fu_907_p3;
                tmp_29_reg_950 <= tmp_29_fu_551_p61;
                    zext_ln112_reg_940(10 downto 0) <= zext_ln112_fu_546_p1(10 downto 0);
                    zext_ln112_reg_940_pp0_iter1_reg(10 downto 0) <= zext_ln112_reg_940(10 downto 0);
            end if;
        end if;
    end process;
    zext_ln112_reg_940(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln112_reg_940_pp0_iter1_reg(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    C_2_address0 <= zext_ln112_reg_940_pp0_iter1_reg(11 - 1 downto 0);
    C_2_ce0 <= C_2_ce0_local;

    C_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            C_2_ce0_local <= ap_const_logic_1;
        else 
            C_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_2_d0 <= select_ln112_11_reg_955;
    C_2_we0 <= C_2_we0_local;

    C_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            C_2_we0_local <= ap_const_logic_1;
        else 
            C_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln109_2_fu_490_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv9_1));
    add_ln109_fu_474_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten125_load) + unsigned(ap_const_lv12_1));
    add_ln110_fu_675_p2 <= std_logic_vector(unsigned(zext_ln109_fu_512_p1) + unsigned(ap_const_lv7_8));
    add_ln112_fu_743_p2 <= std_logic_vector(unsigned(trunc_ln112_2_fu_713_p4) + unsigned(zext_ln112_2_fu_739_p1));
    and_ln112_12_fu_763_p2 <= (xor_ln112_10_fu_757_p2 and tmp_64_fu_731_p3);
    and_ln112_13_fu_825_p2 <= (xor_ln112_11_fu_819_p2 and icmp_ln112_6_fu_785_p2);
    and_ln112_14_fu_839_p2 <= (icmp_ln112_7_fu_799_p2 and and_ln112_12_fu_763_p2);
    and_ln112_15_fu_863_p2 <= (xor_ln112_13_fu_857_p2 and or_ln112_4_fu_851_p2);
    and_ln112_16_fu_869_p2 <= (tmp_65_fu_749_p3 and select_ln112_9_fu_831_p3);
    and_ln112_17_fu_887_p2 <= (xor_ln112_14_fu_881_p2 and tmp_62_fu_705_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln109_fu_468_p2)
    begin
        if (((icmp_ln109_fu_468_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_238)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_238;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten125_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten125_fu_242)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten125_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten125_load <= indvar_flatten125_fu_242;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_234, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv7_2;
        else 
            ap_sig_allocacmp_j_load <= j_fu_234;
        end if; 
    end process;

    icmp_ln109_fu_468_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten125_load = ap_const_lv12_800) else "0";
    icmp_ln112_6_fu_785_p2 <= "1" when (tmp_30_fu_777_p3 = ap_const_lv7_7F) else "0";
    icmp_ln112_7_fu_799_p2 <= "1" when (tmp_31_fu_791_p3 = ap_const_lv8_FF) else "0";
    icmp_ln112_8_fu_805_p2 <= "1" when (tmp_31_fu_791_p3 = ap_const_lv8_0) else "0";
    lshr_ln110_2_fu_528_p4 <= select_ln110_fu_504_p3(5 downto 3);
    or_ln112_4_fu_851_p2 <= (xor_ln112_12_fu_845_p2 or tmp_65_fu_749_p3);
    or_ln112_5_fu_901_p2 <= (and_ln112_17_fu_887_p2 or and_ln112_15_fu_863_p2);
    or_ln112_fu_875_p2 <= (and_ln112_16_fu_869_p2 or and_ln112_14_fu_839_p2);
    select_ln109_fu_516_p3 <= 
        add_ln109_2_fu_490_p2 when (tmp_fu_496_p3(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln110_fu_504_p3 <= 
        ap_const_lv6_2 when (tmp_fu_496_p3(0) = '1') else 
        trunc_ln109_fu_486_p1;
    select_ln112_10_fu_893_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln112_15_fu_863_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln112_11_fu_907_p3 <= 
        select_ln112_10_fu_893_p3 when (or_ln112_5_fu_901_p2(0) = '1') else 
        add_ln112_fu_743_p2;
    select_ln112_8_fu_811_p3 <= 
        icmp_ln112_7_fu_799_p2 when (and_ln112_12_fu_763_p2(0) = '1') else 
        icmp_ln112_8_fu_805_p2;
    select_ln112_9_fu_831_p3 <= 
        and_ln112_13_fu_825_p2 when (and_ln112_12_fu_763_p2(0) = '1') else 
        icmp_ln112_7_fu_799_p2;
    tmp_29_fu_551_p59 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_30_fu_777_p3 <= mul_ln112_fu_446_p2(47 downto 41);
    tmp_31_fu_791_p3 <= mul_ln112_fu_446_p2(47 downto 40);
    tmp_62_fu_705_p3 <= mul_ln112_fu_446_p2(47 downto 47);
    tmp_63_fu_723_p3 <= mul_ln112_fu_446_p2(15 downto 15);
    tmp_64_fu_731_p3 <= mul_ln112_fu_446_p2(39 downto 39);
    tmp_65_fu_749_p3 <= add_ln112_fu_743_p2(23 downto 23);
    tmp_66_fu_769_p3 <= mul_ln112_fu_446_p2(40 downto 40);
    tmp_fu_496_p3 <= ap_sig_allocacmp_j_load(6 downto 6);
    tmp_s_fu_538_p3 <= (trunc_ln110_fu_524_p1 & lshr_ln110_2_fu_528_p4);
    top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_address0 <= zext_ln112_fu_546_p1(11 - 1 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_ce0 <= top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_ce0_local;

    top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_ce0_local <= ap_const_logic_1;
        else 
            top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln109_fu_486_p1 <= ap_sig_allocacmp_j_load(6 - 1 downto 0);
    trunc_ln110_fu_524_p1 <= select_ln109_fu_516_p3(8 - 1 downto 0);
    trunc_ln112_2_fu_713_p4 <= mul_ln112_fu_446_p2(39 downto 16);
    xor_ln112_10_fu_757_p2 <= (tmp_65_fu_749_p3 xor ap_const_lv1_1);
    xor_ln112_11_fu_819_p2 <= (tmp_66_fu_769_p3 xor ap_const_lv1_1);
    xor_ln112_12_fu_845_p2 <= (select_ln112_8_fu_811_p3 xor ap_const_lv1_1);
    xor_ln112_13_fu_857_p2 <= (tmp_62_fu_705_p3 xor ap_const_lv1_1);
    xor_ln112_14_fu_881_p2 <= (or_ln112_fu_875_p2 xor ap_const_lv1_1);
    zext_ln109_fu_512_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln110_fu_504_p3),7));
    zext_ln112_2_fu_739_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_63_fu_723_p3),24));
    zext_ln112_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_538_p3),64));
end behav;
