// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_top_kernel_Pipeline_VITIS_LOOP_60_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i,
        A_0_address0,
        A_0_ce0,
        A_0_q0,
        A_1_address0,
        A_1_ce0,
        A_1_q0,
        A_2_address0,
        A_2_ce0,
        A_2_q0,
        A_3_address0,
        A_3_ce0,
        A_3_q0,
        A_4_address0,
        A_4_ce0,
        A_4_q0,
        A_5_address0,
        A_5_ce0,
        A_5_q0,
        A_6_address0,
        A_6_ce0,
        A_6_q0,
        A_7_address0,
        A_7_ce0,
        A_7_q0,
        A_8_address0,
        A_8_ce0,
        A_8_q0,
        A_9_address0,
        A_9_ce0,
        A_9_q0,
        A_10_address0,
        A_10_ce0,
        A_10_q0,
        A_11_address0,
        A_11_ce0,
        A_11_q0,
        A_12_address0,
        A_12_ce0,
        A_12_q0,
        A_13_address0,
        A_13_ce0,
        A_13_q0,
        A_14_address0,
        A_14_ce0,
        A_14_q0,
        A_15_address0,
        A_15_ce0,
        A_15_q0,
        row_buf_63_out,
        row_buf_63_out_ap_vld,
        row_buf_62_out,
        row_buf_62_out_ap_vld,
        row_buf_61_out,
        row_buf_61_out_ap_vld,
        row_buf_60_out,
        row_buf_60_out_ap_vld,
        row_buf_59_out,
        row_buf_59_out_ap_vld,
        row_buf_58_out,
        row_buf_58_out_ap_vld,
        row_buf_57_out,
        row_buf_57_out_ap_vld,
        row_buf_56_out,
        row_buf_56_out_ap_vld,
        row_buf_55_out,
        row_buf_55_out_ap_vld,
        row_buf_54_out,
        row_buf_54_out_ap_vld,
        row_buf_53_out,
        row_buf_53_out_ap_vld,
        row_buf_52_out,
        row_buf_52_out_ap_vld,
        row_buf_51_out,
        row_buf_51_out_ap_vld,
        row_buf_50_out,
        row_buf_50_out_ap_vld,
        row_buf_49_out,
        row_buf_49_out_ap_vld,
        row_buf_48_out,
        row_buf_48_out_ap_vld,
        row_buf_47_out,
        row_buf_47_out_ap_vld,
        row_buf_46_out,
        row_buf_46_out_ap_vld,
        row_buf_45_out,
        row_buf_45_out_ap_vld,
        row_buf_44_out,
        row_buf_44_out_ap_vld,
        row_buf_43_out,
        row_buf_43_out_ap_vld,
        row_buf_42_out,
        row_buf_42_out_ap_vld,
        row_buf_41_out,
        row_buf_41_out_ap_vld,
        row_buf_40_out,
        row_buf_40_out_ap_vld,
        row_buf_39_out,
        row_buf_39_out_ap_vld,
        row_buf_38_out,
        row_buf_38_out_ap_vld,
        row_buf_37_out,
        row_buf_37_out_ap_vld,
        row_buf_36_out,
        row_buf_36_out_ap_vld,
        row_buf_35_out,
        row_buf_35_out_ap_vld,
        row_buf_34_out,
        row_buf_34_out_ap_vld,
        row_buf_33_out,
        row_buf_33_out_ap_vld,
        row_buf_32_out,
        row_buf_32_out_ap_vld,
        row_buf_31_out,
        row_buf_31_out_ap_vld,
        row_buf_30_out,
        row_buf_30_out_ap_vld,
        row_buf_29_out,
        row_buf_29_out_ap_vld,
        row_buf_28_out,
        row_buf_28_out_ap_vld,
        row_buf_27_out,
        row_buf_27_out_ap_vld,
        row_buf_26_out,
        row_buf_26_out_ap_vld,
        row_buf_25_out,
        row_buf_25_out_ap_vld,
        row_buf_24_out,
        row_buf_24_out_ap_vld,
        row_buf_23_out,
        row_buf_23_out_ap_vld,
        row_buf_22_out,
        row_buf_22_out_ap_vld,
        row_buf_21_out,
        row_buf_21_out_ap_vld,
        row_buf_20_out,
        row_buf_20_out_ap_vld,
        row_buf_19_out,
        row_buf_19_out_ap_vld,
        row_buf_18_out,
        row_buf_18_out_ap_vld,
        row_buf_17_out,
        row_buf_17_out_ap_vld,
        row_buf_16_out,
        row_buf_16_out_ap_vld,
        row_buf_15_out,
        row_buf_15_out_ap_vld,
        row_buf_14_out,
        row_buf_14_out_ap_vld,
        row_buf_13_out,
        row_buf_13_out_ap_vld,
        row_buf_12_out,
        row_buf_12_out_ap_vld,
        row_buf_11_out,
        row_buf_11_out_ap_vld,
        row_buf_10_out,
        row_buf_10_out_ap_vld,
        row_buf_9_out,
        row_buf_9_out_ap_vld,
        row_buf_8_out,
        row_buf_8_out_ap_vld,
        row_buf_7_out,
        row_buf_7_out_ap_vld,
        row_buf_6_out,
        row_buf_6_out_ap_vld,
        row_buf_5_out,
        row_buf_5_out_ap_vld,
        row_buf_4_out,
        row_buf_4_out_ap_vld,
        row_buf_3_out,
        row_buf_3_out_ap_vld,
        row_buf_2_out,
        row_buf_2_out_ap_vld,
        row_buf_1_out,
        row_buf_1_out_ap_vld,
        row_buf_out,
        row_buf_out_ap_vld,
        acc_out,
        acc_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] i;
output  [9:0] A_0_address0;
output   A_0_ce0;
input  [23:0] A_0_q0;
output  [9:0] A_1_address0;
output   A_1_ce0;
input  [23:0] A_1_q0;
output  [9:0] A_2_address0;
output   A_2_ce0;
input  [23:0] A_2_q0;
output  [9:0] A_3_address0;
output   A_3_ce0;
input  [23:0] A_3_q0;
output  [9:0] A_4_address0;
output   A_4_ce0;
input  [23:0] A_4_q0;
output  [9:0] A_5_address0;
output   A_5_ce0;
input  [23:0] A_5_q0;
output  [9:0] A_6_address0;
output   A_6_ce0;
input  [23:0] A_6_q0;
output  [9:0] A_7_address0;
output   A_7_ce0;
input  [23:0] A_7_q0;
output  [9:0] A_8_address0;
output   A_8_ce0;
input  [23:0] A_8_q0;
output  [9:0] A_9_address0;
output   A_9_ce0;
input  [23:0] A_9_q0;
output  [9:0] A_10_address0;
output   A_10_ce0;
input  [23:0] A_10_q0;
output  [9:0] A_11_address0;
output   A_11_ce0;
input  [23:0] A_11_q0;
output  [9:0] A_12_address0;
output   A_12_ce0;
input  [23:0] A_12_q0;
output  [9:0] A_13_address0;
output   A_13_ce0;
input  [23:0] A_13_q0;
output  [9:0] A_14_address0;
output   A_14_ce0;
input  [23:0] A_14_q0;
output  [9:0] A_15_address0;
output   A_15_ce0;
input  [23:0] A_15_q0;
output  [23:0] row_buf_63_out;
output   row_buf_63_out_ap_vld;
output  [23:0] row_buf_62_out;
output   row_buf_62_out_ap_vld;
output  [23:0] row_buf_61_out;
output   row_buf_61_out_ap_vld;
output  [23:0] row_buf_60_out;
output   row_buf_60_out_ap_vld;
output  [23:0] row_buf_59_out;
output   row_buf_59_out_ap_vld;
output  [23:0] row_buf_58_out;
output   row_buf_58_out_ap_vld;
output  [23:0] row_buf_57_out;
output   row_buf_57_out_ap_vld;
output  [23:0] row_buf_56_out;
output   row_buf_56_out_ap_vld;
output  [23:0] row_buf_55_out;
output   row_buf_55_out_ap_vld;
output  [23:0] row_buf_54_out;
output   row_buf_54_out_ap_vld;
output  [23:0] row_buf_53_out;
output   row_buf_53_out_ap_vld;
output  [23:0] row_buf_52_out;
output   row_buf_52_out_ap_vld;
output  [23:0] row_buf_51_out;
output   row_buf_51_out_ap_vld;
output  [23:0] row_buf_50_out;
output   row_buf_50_out_ap_vld;
output  [23:0] row_buf_49_out;
output   row_buf_49_out_ap_vld;
output  [23:0] row_buf_48_out;
output   row_buf_48_out_ap_vld;
output  [23:0] row_buf_47_out;
output   row_buf_47_out_ap_vld;
output  [23:0] row_buf_46_out;
output   row_buf_46_out_ap_vld;
output  [23:0] row_buf_45_out;
output   row_buf_45_out_ap_vld;
output  [23:0] row_buf_44_out;
output   row_buf_44_out_ap_vld;
output  [23:0] row_buf_43_out;
output   row_buf_43_out_ap_vld;
output  [23:0] row_buf_42_out;
output   row_buf_42_out_ap_vld;
output  [23:0] row_buf_41_out;
output   row_buf_41_out_ap_vld;
output  [23:0] row_buf_40_out;
output   row_buf_40_out_ap_vld;
output  [23:0] row_buf_39_out;
output   row_buf_39_out_ap_vld;
output  [23:0] row_buf_38_out;
output   row_buf_38_out_ap_vld;
output  [23:0] row_buf_37_out;
output   row_buf_37_out_ap_vld;
output  [23:0] row_buf_36_out;
output   row_buf_36_out_ap_vld;
output  [23:0] row_buf_35_out;
output   row_buf_35_out_ap_vld;
output  [23:0] row_buf_34_out;
output   row_buf_34_out_ap_vld;
output  [23:0] row_buf_33_out;
output   row_buf_33_out_ap_vld;
output  [23:0] row_buf_32_out;
output   row_buf_32_out_ap_vld;
output  [23:0] row_buf_31_out;
output   row_buf_31_out_ap_vld;
output  [23:0] row_buf_30_out;
output   row_buf_30_out_ap_vld;
output  [23:0] row_buf_29_out;
output   row_buf_29_out_ap_vld;
output  [23:0] row_buf_28_out;
output   row_buf_28_out_ap_vld;
output  [23:0] row_buf_27_out;
output   row_buf_27_out_ap_vld;
output  [23:0] row_buf_26_out;
output   row_buf_26_out_ap_vld;
output  [23:0] row_buf_25_out;
output   row_buf_25_out_ap_vld;
output  [23:0] row_buf_24_out;
output   row_buf_24_out_ap_vld;
output  [23:0] row_buf_23_out;
output   row_buf_23_out_ap_vld;
output  [23:0] row_buf_22_out;
output   row_buf_22_out_ap_vld;
output  [23:0] row_buf_21_out;
output   row_buf_21_out_ap_vld;
output  [23:0] row_buf_20_out;
output   row_buf_20_out_ap_vld;
output  [23:0] row_buf_19_out;
output   row_buf_19_out_ap_vld;
output  [23:0] row_buf_18_out;
output   row_buf_18_out_ap_vld;
output  [23:0] row_buf_17_out;
output   row_buf_17_out_ap_vld;
output  [23:0] row_buf_16_out;
output   row_buf_16_out_ap_vld;
output  [23:0] row_buf_15_out;
output   row_buf_15_out_ap_vld;
output  [23:0] row_buf_14_out;
output   row_buf_14_out_ap_vld;
output  [23:0] row_buf_13_out;
output   row_buf_13_out_ap_vld;
output  [23:0] row_buf_12_out;
output   row_buf_12_out_ap_vld;
output  [23:0] row_buf_11_out;
output   row_buf_11_out_ap_vld;
output  [23:0] row_buf_10_out;
output   row_buf_10_out_ap_vld;
output  [23:0] row_buf_9_out;
output   row_buf_9_out_ap_vld;
output  [23:0] row_buf_8_out;
output   row_buf_8_out_ap_vld;
output  [23:0] row_buf_7_out;
output   row_buf_7_out_ap_vld;
output  [23:0] row_buf_6_out;
output   row_buf_6_out_ap_vld;
output  [23:0] row_buf_5_out;
output   row_buf_5_out_ap_vld;
output  [23:0] row_buf_4_out;
output   row_buf_4_out_ap_vld;
output  [23:0] row_buf_3_out;
output   row_buf_3_out_ap_vld;
output  [23:0] row_buf_2_out;
output   row_buf_2_out_ap_vld;
output  [23:0] row_buf_1_out;
output   row_buf_1_out_ap_vld;
output  [23:0] row_buf_out;
output   row_buf_out_ap_vld;
output  [23:0] acc_out;
output   acc_out_ap_vld;

reg ap_idle;
reg row_buf_63_out_ap_vld;
reg row_buf_62_out_ap_vld;
reg row_buf_61_out_ap_vld;
reg row_buf_60_out_ap_vld;
reg row_buf_59_out_ap_vld;
reg row_buf_58_out_ap_vld;
reg row_buf_57_out_ap_vld;
reg row_buf_56_out_ap_vld;
reg row_buf_55_out_ap_vld;
reg row_buf_54_out_ap_vld;
reg row_buf_53_out_ap_vld;
reg row_buf_52_out_ap_vld;
reg row_buf_51_out_ap_vld;
reg row_buf_50_out_ap_vld;
reg row_buf_49_out_ap_vld;
reg row_buf_48_out_ap_vld;
reg row_buf_47_out_ap_vld;
reg row_buf_46_out_ap_vld;
reg row_buf_45_out_ap_vld;
reg row_buf_44_out_ap_vld;
reg row_buf_43_out_ap_vld;
reg row_buf_42_out_ap_vld;
reg row_buf_41_out_ap_vld;
reg row_buf_40_out_ap_vld;
reg row_buf_39_out_ap_vld;
reg row_buf_38_out_ap_vld;
reg row_buf_37_out_ap_vld;
reg row_buf_36_out_ap_vld;
reg row_buf_35_out_ap_vld;
reg row_buf_34_out_ap_vld;
reg row_buf_33_out_ap_vld;
reg row_buf_32_out_ap_vld;
reg row_buf_31_out_ap_vld;
reg row_buf_30_out_ap_vld;
reg row_buf_29_out_ap_vld;
reg row_buf_28_out_ap_vld;
reg row_buf_27_out_ap_vld;
reg row_buf_26_out_ap_vld;
reg row_buf_25_out_ap_vld;
reg row_buf_24_out_ap_vld;
reg row_buf_23_out_ap_vld;
reg row_buf_22_out_ap_vld;
reg row_buf_21_out_ap_vld;
reg row_buf_20_out_ap_vld;
reg row_buf_19_out_ap_vld;
reg row_buf_18_out_ap_vld;
reg row_buf_17_out_ap_vld;
reg row_buf_16_out_ap_vld;
reg row_buf_15_out_ap_vld;
reg row_buf_14_out_ap_vld;
reg row_buf_13_out_ap_vld;
reg row_buf_12_out_ap_vld;
reg row_buf_11_out_ap_vld;
reg row_buf_10_out_ap_vld;
reg row_buf_9_out_ap_vld;
reg row_buf_8_out_ap_vld;
reg row_buf_7_out_ap_vld;
reg row_buf_6_out_ap_vld;
reg row_buf_5_out_ap_vld;
reg row_buf_4_out_ap_vld;
reg row_buf_3_out_ap_vld;
reg row_buf_2_out_ap_vld;
reg row_buf_1_out_ap_vld;
reg row_buf_out_ap_vld;
reg acc_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_1176_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_reg_3333;
wire   [5:0] trunc_ln60_fu_1184_p1;
reg   [5:0] trunc_ln60_reg_3337;
wire   [63:0] zext_ln66_fu_1206_p1;
reg   [63:0] zext_ln66_reg_3341;
reg  signed [23:0] a_reg_3440;
wire    ap_block_pp0_stage0;
reg   [23:0] acc_fu_230;
wire   [23:0] acc_32_fu_2661_p3;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [6:0] j_fu_234;
wire   [6:0] add_ln60_fu_1221_p2;
reg   [6:0] ap_sig_allocacmp_jb;
reg   [23:0] row_buf_fu_238;
reg    ap_predicate_pred555_state3;
reg   [23:0] row_buf_1_fu_242;
reg   [23:0] row_buf_2_fu_246;
reg   [23:0] row_buf_3_fu_250;
reg   [23:0] row_buf_4_fu_254;
reg   [23:0] row_buf_5_fu_258;
reg   [23:0] row_buf_6_fu_262;
reg   [23:0] row_buf_7_fu_266;
reg   [23:0] row_buf_8_fu_270;
reg   [23:0] row_buf_9_fu_274;
reg   [23:0] row_buf_10_fu_278;
reg   [23:0] row_buf_11_fu_282;
reg   [23:0] row_buf_12_fu_286;
reg   [23:0] row_buf_13_fu_290;
reg   [23:0] row_buf_14_fu_294;
reg   [23:0] row_buf_15_fu_298;
reg   [23:0] row_buf_16_fu_302;
reg    ap_predicate_pred624_state3;
reg   [23:0] row_buf_17_fu_306;
reg   [23:0] row_buf_18_fu_310;
reg   [23:0] row_buf_19_fu_314;
reg   [23:0] row_buf_20_fu_318;
reg   [23:0] row_buf_21_fu_322;
reg   [23:0] row_buf_22_fu_326;
reg   [23:0] row_buf_23_fu_330;
reg   [23:0] row_buf_24_fu_334;
reg   [23:0] row_buf_25_fu_338;
reg   [23:0] row_buf_26_fu_342;
reg   [23:0] row_buf_27_fu_346;
reg   [23:0] row_buf_28_fu_350;
reg   [23:0] row_buf_29_fu_354;
reg   [23:0] row_buf_30_fu_358;
reg   [23:0] row_buf_31_fu_362;
reg   [23:0] row_buf_32_fu_366;
reg    ap_predicate_pred678_state3;
reg   [23:0] row_buf_33_fu_370;
reg   [23:0] row_buf_34_fu_374;
reg   [23:0] row_buf_35_fu_378;
reg   [23:0] row_buf_36_fu_382;
reg   [23:0] row_buf_37_fu_386;
reg   [23:0] row_buf_38_fu_390;
reg   [23:0] row_buf_39_fu_394;
reg   [23:0] row_buf_40_fu_398;
reg   [23:0] row_buf_41_fu_402;
reg   [23:0] row_buf_42_fu_406;
reg   [23:0] row_buf_43_fu_410;
reg   [23:0] row_buf_44_fu_414;
reg   [23:0] row_buf_45_fu_418;
reg   [23:0] row_buf_46_fu_422;
reg   [23:0] row_buf_47_fu_426;
reg   [23:0] row_buf_48_fu_430;
reg    ap_predicate_pred735_state3;
reg   [23:0] row_buf_49_fu_434;
reg   [23:0] row_buf_50_fu_438;
reg   [23:0] row_buf_51_fu_442;
reg   [23:0] row_buf_52_fu_446;
reg   [23:0] row_buf_53_fu_450;
reg   [23:0] row_buf_54_fu_454;
reg   [23:0] row_buf_55_fu_458;
reg   [23:0] row_buf_56_fu_462;
reg   [23:0] row_buf_57_fu_466;
reg   [23:0] row_buf_58_fu_470;
reg   [23:0] row_buf_59_fu_474;
reg   [23:0] row_buf_60_fu_478;
reg   [23:0] row_buf_61_fu_482;
reg   [23:0] row_buf_62_fu_486;
reg   [23:0] row_buf_63_fu_490;
wire    ap_block_pp0_stage0_01001;
reg    A_0_ce0_local;
reg    A_1_ce0_local;
reg    A_2_ce0_local;
reg    A_3_ce0_local;
reg    A_4_ce0_local;
reg    A_5_ce0_local;
reg    A_6_ce0_local;
reg    A_7_ce0_local;
reg    A_8_ce0_local;
reg    A_9_ce0_local;
reg    A_10_ce0_local;
reg    A_11_ce0_local;
reg    A_12_ce0_local;
reg    A_13_ce0_local;
reg    A_14_ce0_local;
reg    A_15_ce0_local;
wire   [1:0] lshr_ln_fu_1188_p4;
wire   [9:0] tmp_s_fu_1198_p3;
wire  signed [23:0] sext_ln68_fu_1235_p0;
wire  signed [23:0] acc_1_fu_1242_p1;
wire  signed [24:0] sext_ln68_1_fu_1239_p1;
wire  signed [24:0] sext_ln68_fu_1235_p1;
wire   [24:0] add_ln68_1_fu_1247_p2;
wire   [23:0] acc_1_fu_1242_p2;
wire   [0:0] tmp_168_fu_1253_p3;
wire   [0:0] tmp_169_fu_1261_p3;
wire   [0:0] xor_ln68_fu_1269_p2;
wire   [0:0] and_ln68_fu_1275_p2;
wire   [0:0] xor_ln68_1_fu_1281_p2;
wire   [23:0] select_ln68_fu_1287_p3;
wire  signed [23:0] acc_2_fu_1295_p3;
wire  signed [23:0] sext_ln68_3_fu_1307_p0;
wire  signed [23:0] acc_3_fu_1311_p0;
wire  signed [24:0] sext_ln68_2_fu_1303_p1;
wire  signed [24:0] sext_ln68_3_fu_1307_p1;
wire   [24:0] add_ln68_2_fu_1317_p2;
wire   [23:0] acc_3_fu_1311_p2;
wire   [0:0] tmp_170_fu_1323_p3;
wire   [0:0] tmp_171_fu_1331_p3;
wire   [0:0] xor_ln68_2_fu_1339_p2;
wire   [0:0] and_ln68_1_fu_1345_p2;
wire   [0:0] xor_ln68_3_fu_1351_p2;
wire   [23:0] select_ln68_2_fu_1357_p3;
wire  signed [23:0] acc_4_fu_1365_p3;
wire  signed [23:0] sext_ln68_5_fu_1377_p0;
wire  signed [23:0] acc_5_fu_1381_p0;
wire  signed [24:0] sext_ln68_4_fu_1373_p1;
wire  signed [24:0] sext_ln68_5_fu_1377_p1;
wire   [24:0] add_ln68_3_fu_1387_p2;
wire   [23:0] acc_5_fu_1381_p2;
wire   [0:0] tmp_172_fu_1393_p3;
wire   [0:0] tmp_173_fu_1401_p3;
wire   [0:0] xor_ln68_4_fu_1409_p2;
wire   [0:0] and_ln68_2_fu_1415_p2;
wire   [0:0] xor_ln68_5_fu_1421_p2;
wire   [23:0] select_ln68_4_fu_1427_p3;
wire  signed [23:0] acc_6_fu_1435_p3;
wire  signed [23:0] sext_ln68_7_fu_1447_p0;
wire  signed [23:0] acc_7_fu_1451_p0;
wire  signed [24:0] sext_ln68_6_fu_1443_p1;
wire  signed [24:0] sext_ln68_7_fu_1447_p1;
wire   [24:0] add_ln68_4_fu_1457_p2;
wire   [23:0] acc_7_fu_1451_p2;
wire   [0:0] tmp_174_fu_1463_p3;
wire   [0:0] tmp_175_fu_1471_p3;
wire   [0:0] xor_ln68_6_fu_1479_p2;
wire   [0:0] and_ln68_3_fu_1485_p2;
wire   [0:0] xor_ln68_7_fu_1491_p2;
wire   [23:0] select_ln68_6_fu_1497_p3;
wire  signed [23:0] acc_8_fu_1505_p3;
wire  signed [23:0] sext_ln68_9_fu_1517_p0;
wire  signed [23:0] acc_9_fu_1521_p0;
wire  signed [24:0] sext_ln68_8_fu_1513_p1;
wire  signed [24:0] sext_ln68_9_fu_1517_p1;
wire   [24:0] add_ln68_5_fu_1527_p2;
wire   [23:0] acc_9_fu_1521_p2;
wire   [0:0] tmp_176_fu_1533_p3;
wire   [0:0] tmp_177_fu_1541_p3;
wire   [0:0] xor_ln68_8_fu_1549_p2;
wire   [0:0] and_ln68_4_fu_1555_p2;
wire   [0:0] xor_ln68_9_fu_1561_p2;
wire   [23:0] select_ln68_8_fu_1567_p3;
wire  signed [23:0] acc_10_fu_1575_p3;
wire  signed [23:0] sext_ln68_11_fu_1587_p0;
wire  signed [23:0] acc_11_fu_1591_p0;
wire  signed [24:0] sext_ln68_10_fu_1583_p1;
wire  signed [24:0] sext_ln68_11_fu_1587_p1;
wire   [24:0] add_ln68_6_fu_1597_p2;
wire   [23:0] acc_11_fu_1591_p2;
wire   [0:0] tmp_178_fu_1603_p3;
wire   [0:0] tmp_179_fu_1611_p3;
wire   [0:0] xor_ln68_10_fu_1619_p2;
wire   [0:0] and_ln68_5_fu_1625_p2;
wire   [0:0] xor_ln68_11_fu_1631_p2;
wire   [23:0] select_ln68_10_fu_1637_p3;
wire  signed [23:0] acc_12_fu_1645_p3;
wire  signed [23:0] sext_ln68_13_fu_1657_p0;
wire  signed [23:0] acc_13_fu_1661_p0;
wire  signed [24:0] sext_ln68_12_fu_1653_p1;
wire  signed [24:0] sext_ln68_13_fu_1657_p1;
wire   [24:0] add_ln68_7_fu_1667_p2;
wire   [23:0] acc_13_fu_1661_p2;
wire   [0:0] tmp_180_fu_1673_p3;
wire   [0:0] tmp_181_fu_1681_p3;
wire   [0:0] xor_ln68_12_fu_1689_p2;
wire   [0:0] and_ln68_6_fu_1695_p2;
wire   [0:0] xor_ln68_13_fu_1701_p2;
wire   [23:0] select_ln68_12_fu_1707_p3;
wire  signed [23:0] acc_14_fu_1715_p3;
wire  signed [23:0] sext_ln68_15_fu_1727_p0;
wire  signed [23:0] acc_15_fu_1731_p0;
wire  signed [24:0] sext_ln68_14_fu_1723_p1;
wire  signed [24:0] sext_ln68_15_fu_1727_p1;
wire   [24:0] add_ln68_8_fu_1737_p2;
wire   [23:0] acc_15_fu_1731_p2;
wire   [0:0] tmp_182_fu_1743_p3;
wire   [0:0] tmp_183_fu_1751_p3;
wire   [0:0] xor_ln68_14_fu_1759_p2;
wire   [0:0] and_ln68_7_fu_1765_p2;
wire   [0:0] xor_ln68_15_fu_1771_p2;
wire   [23:0] select_ln68_14_fu_1777_p3;
wire  signed [23:0] acc_16_fu_1785_p3;
wire  signed [23:0] sext_ln68_17_fu_1797_p0;
wire  signed [23:0] acc_17_fu_1801_p0;
wire  signed [24:0] sext_ln68_16_fu_1793_p1;
wire  signed [24:0] sext_ln68_17_fu_1797_p1;
wire   [24:0] add_ln68_9_fu_1807_p2;
wire   [23:0] acc_17_fu_1801_p2;
wire   [0:0] tmp_184_fu_1813_p3;
wire   [0:0] tmp_185_fu_1821_p3;
wire   [0:0] xor_ln68_16_fu_1829_p2;
wire   [0:0] and_ln68_8_fu_1835_p2;
wire   [0:0] xor_ln68_17_fu_1841_p2;
wire   [23:0] select_ln68_16_fu_1847_p3;
wire  signed [23:0] acc_18_fu_1855_p3;
wire  signed [23:0] sext_ln68_19_fu_1867_p0;
wire  signed [23:0] acc_19_fu_1871_p0;
wire  signed [24:0] sext_ln68_18_fu_1863_p1;
wire  signed [24:0] sext_ln68_19_fu_1867_p1;
wire   [24:0] add_ln68_10_fu_1877_p2;
wire   [23:0] acc_19_fu_1871_p2;
wire   [0:0] tmp_186_fu_1883_p3;
wire   [0:0] tmp_187_fu_1891_p3;
wire   [0:0] xor_ln68_18_fu_1899_p2;
wire   [0:0] and_ln68_9_fu_1905_p2;
wire   [0:0] xor_ln68_19_fu_1911_p2;
wire   [23:0] select_ln68_18_fu_1917_p3;
wire  signed [23:0] acc_20_fu_1925_p3;
wire  signed [23:0] sext_ln68_21_fu_1937_p0;
wire  signed [23:0] acc_21_fu_1941_p0;
wire  signed [24:0] sext_ln68_20_fu_1933_p1;
wire  signed [24:0] sext_ln68_21_fu_1937_p1;
wire   [24:0] add_ln68_11_fu_1947_p2;
wire   [23:0] acc_21_fu_1941_p2;
wire   [0:0] tmp_188_fu_1953_p3;
wire   [0:0] tmp_189_fu_1961_p3;
wire   [0:0] xor_ln68_20_fu_1969_p2;
wire   [0:0] and_ln68_10_fu_1975_p2;
wire   [0:0] xor_ln68_21_fu_1981_p2;
wire   [23:0] select_ln68_20_fu_1987_p3;
wire  signed [23:0] acc_22_fu_1995_p3;
wire  signed [23:0] sext_ln68_23_fu_2007_p0;
wire  signed [23:0] acc_23_fu_2011_p0;
wire  signed [24:0] sext_ln68_22_fu_2003_p1;
wire  signed [24:0] sext_ln68_23_fu_2007_p1;
wire   [24:0] add_ln68_12_fu_2017_p2;
wire   [23:0] acc_23_fu_2011_p2;
wire   [0:0] tmp_190_fu_2023_p3;
wire   [0:0] tmp_191_fu_2031_p3;
wire   [0:0] xor_ln68_22_fu_2039_p2;
wire   [0:0] and_ln68_11_fu_2045_p2;
wire   [0:0] xor_ln68_23_fu_2051_p2;
wire   [23:0] select_ln68_22_fu_2057_p3;
wire  signed [23:0] acc_24_fu_2065_p3;
wire  signed [23:0] sext_ln68_25_fu_2077_p0;
wire  signed [23:0] acc_25_fu_2081_p0;
wire  signed [24:0] sext_ln68_24_fu_2073_p1;
wire  signed [24:0] sext_ln68_25_fu_2077_p1;
wire   [24:0] add_ln68_13_fu_2087_p2;
wire   [23:0] acc_25_fu_2081_p2;
wire   [0:0] tmp_192_fu_2093_p3;
wire   [0:0] tmp_193_fu_2101_p3;
wire   [0:0] xor_ln68_24_fu_2109_p2;
wire   [0:0] and_ln68_12_fu_2115_p2;
wire   [0:0] xor_ln68_25_fu_2121_p2;
wire   [23:0] select_ln68_24_fu_2127_p3;
wire  signed [23:0] acc_26_fu_2135_p3;
wire  signed [23:0] sext_ln68_27_fu_2147_p0;
wire  signed [23:0] acc_27_fu_2151_p0;
wire  signed [24:0] sext_ln68_26_fu_2143_p1;
wire  signed [24:0] sext_ln68_27_fu_2147_p1;
wire   [24:0] add_ln68_14_fu_2157_p2;
wire   [23:0] acc_27_fu_2151_p2;
wire   [0:0] tmp_194_fu_2163_p3;
wire   [0:0] tmp_195_fu_2171_p3;
wire   [0:0] xor_ln68_26_fu_2179_p2;
wire   [0:0] and_ln68_13_fu_2185_p2;
wire   [0:0] xor_ln68_27_fu_2191_p2;
wire   [23:0] select_ln68_26_fu_2197_p3;
wire  signed [23:0] acc_28_fu_2205_p3;
wire  signed [23:0] sext_ln68_29_fu_2217_p0;
wire  signed [23:0] acc_29_fu_2221_p0;
wire  signed [24:0] sext_ln68_28_fu_2213_p1;
wire  signed [24:0] sext_ln68_29_fu_2217_p1;
wire   [24:0] add_ln68_15_fu_2227_p2;
wire   [23:0] acc_29_fu_2221_p2;
wire   [0:0] tmp_196_fu_2233_p3;
wire   [0:0] tmp_197_fu_2241_p3;
wire   [0:0] xor_ln68_28_fu_2249_p2;
wire   [0:0] and_ln68_14_fu_2255_p2;
wire   [0:0] xor_ln68_29_fu_2261_p2;
wire   [23:0] select_ln68_28_fu_2267_p3;
wire  signed [23:0] acc_30_fu_2275_p3;
wire  signed [23:0] sext_ln68_31_fu_2603_p0;
wire  signed [23:0] acc_31_fu_2607_p0;
wire  signed [24:0] sext_ln68_30_fu_2599_p1;
wire  signed [24:0] sext_ln68_31_fu_2603_p1;
wire   [24:0] add_ln68_16_fu_2613_p2;
wire   [23:0] acc_31_fu_2607_p2;
wire   [0:0] tmp_198_fu_2619_p3;
wire   [0:0] tmp_199_fu_2627_p3;
wire   [0:0] xor_ln68_30_fu_2635_p2;
wire   [0:0] and_ln68_15_fu_2641_p2;
wire   [0:0] xor_ln68_31_fu_2647_p2;
wire   [23:0] select_ln68_30_fu_2653_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 acc_fu_230 = 24'd0;
#0 j_fu_234 = 7'd0;
#0 row_buf_fu_238 = 24'd0;
#0 row_buf_1_fu_242 = 24'd0;
#0 row_buf_2_fu_246 = 24'd0;
#0 row_buf_3_fu_250 = 24'd0;
#0 row_buf_4_fu_254 = 24'd0;
#0 row_buf_5_fu_258 = 24'd0;
#0 row_buf_6_fu_262 = 24'd0;
#0 row_buf_7_fu_266 = 24'd0;
#0 row_buf_8_fu_270 = 24'd0;
#0 row_buf_9_fu_274 = 24'd0;
#0 row_buf_10_fu_278 = 24'd0;
#0 row_buf_11_fu_282 = 24'd0;
#0 row_buf_12_fu_286 = 24'd0;
#0 row_buf_13_fu_290 = 24'd0;
#0 row_buf_14_fu_294 = 24'd0;
#0 row_buf_15_fu_298 = 24'd0;
#0 row_buf_16_fu_302 = 24'd0;
#0 row_buf_17_fu_306 = 24'd0;
#0 row_buf_18_fu_310 = 24'd0;
#0 row_buf_19_fu_314 = 24'd0;
#0 row_buf_20_fu_318 = 24'd0;
#0 row_buf_21_fu_322 = 24'd0;
#0 row_buf_22_fu_326 = 24'd0;
#0 row_buf_23_fu_330 = 24'd0;
#0 row_buf_24_fu_334 = 24'd0;
#0 row_buf_25_fu_338 = 24'd0;
#0 row_buf_26_fu_342 = 24'd0;
#0 row_buf_27_fu_346 = 24'd0;
#0 row_buf_28_fu_350 = 24'd0;
#0 row_buf_29_fu_354 = 24'd0;
#0 row_buf_30_fu_358 = 24'd0;
#0 row_buf_31_fu_362 = 24'd0;
#0 row_buf_32_fu_366 = 24'd0;
#0 row_buf_33_fu_370 = 24'd0;
#0 row_buf_34_fu_374 = 24'd0;
#0 row_buf_35_fu_378 = 24'd0;
#0 row_buf_36_fu_382 = 24'd0;
#0 row_buf_37_fu_386 = 24'd0;
#0 row_buf_38_fu_390 = 24'd0;
#0 row_buf_39_fu_394 = 24'd0;
#0 row_buf_40_fu_398 = 24'd0;
#0 row_buf_41_fu_402 = 24'd0;
#0 row_buf_42_fu_406 = 24'd0;
#0 row_buf_43_fu_410 = 24'd0;
#0 row_buf_44_fu_414 = 24'd0;
#0 row_buf_45_fu_418 = 24'd0;
#0 row_buf_46_fu_422 = 24'd0;
#0 row_buf_47_fu_426 = 24'd0;
#0 row_buf_48_fu_430 = 24'd0;
#0 row_buf_49_fu_434 = 24'd0;
#0 row_buf_50_fu_438 = 24'd0;
#0 row_buf_51_fu_442 = 24'd0;
#0 row_buf_52_fu_446 = 24'd0;
#0 row_buf_53_fu_450 = 24'd0;
#0 row_buf_54_fu_454 = 24'd0;
#0 row_buf_55_fu_458 = 24'd0;
#0 row_buf_56_fu_462 = 24'd0;
#0 row_buf_57_fu_466 = 24'd0;
#0 row_buf_58_fu_470 = 24'd0;
#0 row_buf_59_fu_474 = 24'd0;
#0 row_buf_60_fu_478 = 24'd0;
#0 row_buf_61_fu_482 = 24'd0;
#0 row_buf_62_fu_486 = 24'd0;
#0 row_buf_63_fu_490 = 24'd0;
#0 ap_done_reg = 1'b0;
end

top_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            acc_fu_230 <= 24'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            acc_fu_230 <= acc_32_fu_2661_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_fu_1176_p3 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_234 <= add_ln60_fu_1221_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_234 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_reg_3440 <= A_0_q0;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_predicate_pred555_state3 <= (trunc_ln60_reg_3337 == 6'd0);
        ap_predicate_pred624_state3 <= (trunc_ln60_reg_3337 == 6'd16);
        ap_predicate_pred678_state3 <= (trunc_ln60_reg_3337 == 6'd32);
        ap_predicate_pred735_state3 <= (~(trunc_ln60_reg_3337 == 6'd32) & ~(trunc_ln60_reg_3337 == 6'd16) & ~(trunc_ln60_reg_3337 == 6'd0));
        tmp_reg_3333 <= ap_sig_allocacmp_jb[32'd6];
        trunc_ln60_reg_3337 <= trunc_ln60_fu_1184_p1;
        zext_ln66_reg_3341[9 : 0] <= zext_ln66_fu_1206_p1[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred555_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        row_buf_10_fu_278 <= A_10_q0;
        row_buf_11_fu_282 <= A_11_q0;
        row_buf_12_fu_286 <= A_12_q0;
        row_buf_13_fu_290 <= A_13_q0;
        row_buf_14_fu_294 <= A_14_q0;
        row_buf_15_fu_298 <= A_15_q0;
        row_buf_1_fu_242 <= A_1_q0;
        row_buf_2_fu_246 <= A_2_q0;
        row_buf_3_fu_250 <= A_3_q0;
        row_buf_4_fu_254 <= A_4_q0;
        row_buf_5_fu_258 <= A_5_q0;
        row_buf_6_fu_262 <= A_6_q0;
        row_buf_7_fu_266 <= A_7_q0;
        row_buf_8_fu_270 <= A_8_q0;
        row_buf_9_fu_274 <= A_9_q0;
        row_buf_fu_238 <= a_reg_3440;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred624_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        row_buf_16_fu_302 <= a_reg_3440;
        row_buf_17_fu_306 <= A_1_q0;
        row_buf_18_fu_310 <= A_2_q0;
        row_buf_19_fu_314 <= A_3_q0;
        row_buf_20_fu_318 <= A_4_q0;
        row_buf_21_fu_322 <= A_5_q0;
        row_buf_22_fu_326 <= A_6_q0;
        row_buf_23_fu_330 <= A_7_q0;
        row_buf_24_fu_334 <= A_8_q0;
        row_buf_25_fu_338 <= A_9_q0;
        row_buf_26_fu_342 <= A_10_q0;
        row_buf_27_fu_346 <= A_11_q0;
        row_buf_28_fu_350 <= A_12_q0;
        row_buf_29_fu_354 <= A_13_q0;
        row_buf_30_fu_358 <= A_14_q0;
        row_buf_31_fu_362 <= A_15_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred678_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        row_buf_32_fu_366 <= a_reg_3440;
        row_buf_33_fu_370 <= A_1_q0;
        row_buf_34_fu_374 <= A_2_q0;
        row_buf_35_fu_378 <= A_3_q0;
        row_buf_36_fu_382 <= A_4_q0;
        row_buf_37_fu_386 <= A_5_q0;
        row_buf_38_fu_390 <= A_6_q0;
        row_buf_39_fu_394 <= A_7_q0;
        row_buf_40_fu_398 <= A_8_q0;
        row_buf_41_fu_402 <= A_9_q0;
        row_buf_42_fu_406 <= A_10_q0;
        row_buf_43_fu_410 <= A_11_q0;
        row_buf_44_fu_414 <= A_12_q0;
        row_buf_45_fu_418 <= A_13_q0;
        row_buf_46_fu_422 <= A_14_q0;
        row_buf_47_fu_426 <= A_15_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred735_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        row_buf_48_fu_430 <= a_reg_3440;
        row_buf_49_fu_434 <= A_1_q0;
        row_buf_50_fu_438 <= A_2_q0;
        row_buf_51_fu_442 <= A_3_q0;
        row_buf_52_fu_446 <= A_4_q0;
        row_buf_53_fu_450 <= A_5_q0;
        row_buf_54_fu_454 <= A_6_q0;
        row_buf_55_fu_458 <= A_7_q0;
        row_buf_56_fu_462 <= A_8_q0;
        row_buf_57_fu_466 <= A_9_q0;
        row_buf_58_fu_470 <= A_10_q0;
        row_buf_59_fu_474 <= A_11_q0;
        row_buf_60_fu_478 <= A_12_q0;
        row_buf_61_fu_482 <= A_13_q0;
        row_buf_62_fu_486 <= A_14_q0;
        row_buf_63_fu_490 <= A_15_q0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_0_ce0_local = 1'b1;
    end else begin
        A_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_10_ce0_local = 1'b1;
    end else begin
        A_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_11_ce0_local = 1'b1;
    end else begin
        A_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_12_ce0_local = 1'b1;
    end else begin
        A_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_13_ce0_local = 1'b1;
    end else begin
        A_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_14_ce0_local = 1'b1;
    end else begin
        A_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_15_ce0_local = 1'b1;
    end else begin
        A_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_1_ce0_local = 1'b1;
    end else begin
        A_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_2_ce0_local = 1'b1;
    end else begin
        A_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_3_ce0_local = 1'b1;
    end else begin
        A_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_4_ce0_local = 1'b1;
    end else begin
        A_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_5_ce0_local = 1'b1;
    end else begin
        A_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_6_ce0_local = 1'b1;
    end else begin
        A_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_7_ce0_local = 1'b1;
    end else begin
        A_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_8_ce0_local = 1'b1;
    end else begin
        A_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_9_ce0_local = 1'b1;
    end else begin
        A_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_out_ap_vld = 1'b1;
    end else begin
        acc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_1176_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_jb = 7'd0;
    end else begin
        ap_sig_allocacmp_jb = j_fu_234;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_10_out_ap_vld = 1'b1;
    end else begin
        row_buf_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_11_out_ap_vld = 1'b1;
    end else begin
        row_buf_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_12_out_ap_vld = 1'b1;
    end else begin
        row_buf_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_13_out_ap_vld = 1'b1;
    end else begin
        row_buf_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_14_out_ap_vld = 1'b1;
    end else begin
        row_buf_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_15_out_ap_vld = 1'b1;
    end else begin
        row_buf_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_16_out_ap_vld = 1'b1;
    end else begin
        row_buf_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_17_out_ap_vld = 1'b1;
    end else begin
        row_buf_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_18_out_ap_vld = 1'b1;
    end else begin
        row_buf_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_19_out_ap_vld = 1'b1;
    end else begin
        row_buf_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_1_out_ap_vld = 1'b1;
    end else begin
        row_buf_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_20_out_ap_vld = 1'b1;
    end else begin
        row_buf_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_21_out_ap_vld = 1'b1;
    end else begin
        row_buf_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_22_out_ap_vld = 1'b1;
    end else begin
        row_buf_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_23_out_ap_vld = 1'b1;
    end else begin
        row_buf_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_24_out_ap_vld = 1'b1;
    end else begin
        row_buf_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_25_out_ap_vld = 1'b1;
    end else begin
        row_buf_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_26_out_ap_vld = 1'b1;
    end else begin
        row_buf_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_27_out_ap_vld = 1'b1;
    end else begin
        row_buf_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_28_out_ap_vld = 1'b1;
    end else begin
        row_buf_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_29_out_ap_vld = 1'b1;
    end else begin
        row_buf_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_2_out_ap_vld = 1'b1;
    end else begin
        row_buf_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_30_out_ap_vld = 1'b1;
    end else begin
        row_buf_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_31_out_ap_vld = 1'b1;
    end else begin
        row_buf_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_32_out_ap_vld = 1'b1;
    end else begin
        row_buf_32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_33_out_ap_vld = 1'b1;
    end else begin
        row_buf_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_34_out_ap_vld = 1'b1;
    end else begin
        row_buf_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_35_out_ap_vld = 1'b1;
    end else begin
        row_buf_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_36_out_ap_vld = 1'b1;
    end else begin
        row_buf_36_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_37_out_ap_vld = 1'b1;
    end else begin
        row_buf_37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_38_out_ap_vld = 1'b1;
    end else begin
        row_buf_38_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_39_out_ap_vld = 1'b1;
    end else begin
        row_buf_39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_3_out_ap_vld = 1'b1;
    end else begin
        row_buf_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_40_out_ap_vld = 1'b1;
    end else begin
        row_buf_40_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_41_out_ap_vld = 1'b1;
    end else begin
        row_buf_41_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_42_out_ap_vld = 1'b1;
    end else begin
        row_buf_42_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_43_out_ap_vld = 1'b1;
    end else begin
        row_buf_43_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_44_out_ap_vld = 1'b1;
    end else begin
        row_buf_44_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_45_out_ap_vld = 1'b1;
    end else begin
        row_buf_45_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_46_out_ap_vld = 1'b1;
    end else begin
        row_buf_46_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_47_out_ap_vld = 1'b1;
    end else begin
        row_buf_47_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_48_out_ap_vld = 1'b1;
    end else begin
        row_buf_48_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_49_out_ap_vld = 1'b1;
    end else begin
        row_buf_49_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_4_out_ap_vld = 1'b1;
    end else begin
        row_buf_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_50_out_ap_vld = 1'b1;
    end else begin
        row_buf_50_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_51_out_ap_vld = 1'b1;
    end else begin
        row_buf_51_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_52_out_ap_vld = 1'b1;
    end else begin
        row_buf_52_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_53_out_ap_vld = 1'b1;
    end else begin
        row_buf_53_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_54_out_ap_vld = 1'b1;
    end else begin
        row_buf_54_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_55_out_ap_vld = 1'b1;
    end else begin
        row_buf_55_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_56_out_ap_vld = 1'b1;
    end else begin
        row_buf_56_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_57_out_ap_vld = 1'b1;
    end else begin
        row_buf_57_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_58_out_ap_vld = 1'b1;
    end else begin
        row_buf_58_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_59_out_ap_vld = 1'b1;
    end else begin
        row_buf_59_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_5_out_ap_vld = 1'b1;
    end else begin
        row_buf_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_60_out_ap_vld = 1'b1;
    end else begin
        row_buf_60_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_61_out_ap_vld = 1'b1;
    end else begin
        row_buf_61_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_62_out_ap_vld = 1'b1;
    end else begin
        row_buf_62_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_63_out_ap_vld = 1'b1;
    end else begin
        row_buf_63_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_6_out_ap_vld = 1'b1;
    end else begin
        row_buf_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_7_out_ap_vld = 1'b1;
    end else begin
        row_buf_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_8_out_ap_vld = 1'b1;
    end else begin
        row_buf_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_9_out_ap_vld = 1'b1;
    end else begin
        row_buf_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (tmp_reg_3333 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_out_ap_vld = 1'b1;
    end else begin
        row_buf_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_0_address0 = zext_ln66_fu_1206_p1;

assign A_0_ce0 = A_0_ce0_local;

assign A_10_address0 = zext_ln66_reg_3341;

assign A_10_ce0 = A_10_ce0_local;

assign A_11_address0 = zext_ln66_reg_3341;

assign A_11_ce0 = A_11_ce0_local;

assign A_12_address0 = zext_ln66_reg_3341;

assign A_12_ce0 = A_12_ce0_local;

assign A_13_address0 = zext_ln66_reg_3341;

assign A_13_ce0 = A_13_ce0_local;

assign A_14_address0 = zext_ln66_reg_3341;

assign A_14_ce0 = A_14_ce0_local;

assign A_15_address0 = zext_ln66_reg_3341;

assign A_15_ce0 = A_15_ce0_local;

assign A_1_address0 = zext_ln66_reg_3341;

assign A_1_ce0 = A_1_ce0_local;

assign A_2_address0 = zext_ln66_reg_3341;

assign A_2_ce0 = A_2_ce0_local;

assign A_3_address0 = zext_ln66_reg_3341;

assign A_3_ce0 = A_3_ce0_local;

assign A_4_address0 = zext_ln66_reg_3341;

assign A_4_ce0 = A_4_ce0_local;

assign A_5_address0 = zext_ln66_reg_3341;

assign A_5_ce0 = A_5_ce0_local;

assign A_6_address0 = zext_ln66_reg_3341;

assign A_6_ce0 = A_6_ce0_local;

assign A_7_address0 = zext_ln66_reg_3341;

assign A_7_ce0 = A_7_ce0_local;

assign A_8_address0 = zext_ln66_reg_3341;

assign A_8_ce0 = A_8_ce0_local;

assign A_9_address0 = zext_ln66_reg_3341;

assign A_9_ce0 = A_9_ce0_local;

assign acc_10_fu_1575_p3 = ((xor_ln68_9_fu_1561_p2[0:0] == 1'b1) ? select_ln68_8_fu_1567_p3 : acc_9_fu_1521_p2);

assign acc_11_fu_1591_p0 = A_5_q0;

assign acc_11_fu_1591_p2 = ($signed(acc_11_fu_1591_p0) + $signed(acc_10_fu_1575_p3));

assign acc_12_fu_1645_p3 = ((xor_ln68_11_fu_1631_p2[0:0] == 1'b1) ? select_ln68_10_fu_1637_p3 : acc_11_fu_1591_p2);

assign acc_13_fu_1661_p0 = A_6_q0;

assign acc_13_fu_1661_p2 = ($signed(acc_13_fu_1661_p0) + $signed(acc_12_fu_1645_p3));

assign acc_14_fu_1715_p3 = ((xor_ln68_13_fu_1701_p2[0:0] == 1'b1) ? select_ln68_12_fu_1707_p3 : acc_13_fu_1661_p2);

assign acc_15_fu_1731_p0 = A_7_q0;

assign acc_15_fu_1731_p2 = ($signed(acc_15_fu_1731_p0) + $signed(acc_14_fu_1715_p3));

assign acc_16_fu_1785_p3 = ((xor_ln68_15_fu_1771_p2[0:0] == 1'b1) ? select_ln68_14_fu_1777_p3 : acc_15_fu_1731_p2);

assign acc_17_fu_1801_p0 = A_8_q0;

assign acc_17_fu_1801_p2 = ($signed(acc_17_fu_1801_p0) + $signed(acc_16_fu_1785_p3));

assign acc_18_fu_1855_p3 = ((xor_ln68_17_fu_1841_p2[0:0] == 1'b1) ? select_ln68_16_fu_1847_p3 : acc_17_fu_1801_p2);

assign acc_19_fu_1871_p0 = A_9_q0;

assign acc_19_fu_1871_p2 = ($signed(acc_19_fu_1871_p0) + $signed(acc_18_fu_1855_p3));

assign acc_1_fu_1242_p1 = acc_fu_230;

assign acc_1_fu_1242_p2 = ($signed(a_reg_3440) + $signed(acc_1_fu_1242_p1));

assign acc_20_fu_1925_p3 = ((xor_ln68_19_fu_1911_p2[0:0] == 1'b1) ? select_ln68_18_fu_1917_p3 : acc_19_fu_1871_p2);

assign acc_21_fu_1941_p0 = A_10_q0;

assign acc_21_fu_1941_p2 = ($signed(acc_21_fu_1941_p0) + $signed(acc_20_fu_1925_p3));

assign acc_22_fu_1995_p3 = ((xor_ln68_21_fu_1981_p2[0:0] == 1'b1) ? select_ln68_20_fu_1987_p3 : acc_21_fu_1941_p2);

assign acc_23_fu_2011_p0 = A_11_q0;

assign acc_23_fu_2011_p2 = ($signed(acc_23_fu_2011_p0) + $signed(acc_22_fu_1995_p3));

assign acc_24_fu_2065_p3 = ((xor_ln68_23_fu_2051_p2[0:0] == 1'b1) ? select_ln68_22_fu_2057_p3 : acc_23_fu_2011_p2);

assign acc_25_fu_2081_p0 = A_12_q0;

assign acc_25_fu_2081_p2 = ($signed(acc_25_fu_2081_p0) + $signed(acc_24_fu_2065_p3));

assign acc_26_fu_2135_p3 = ((xor_ln68_25_fu_2121_p2[0:0] == 1'b1) ? select_ln68_24_fu_2127_p3 : acc_25_fu_2081_p2);

assign acc_27_fu_2151_p0 = A_13_q0;

assign acc_27_fu_2151_p2 = ($signed(acc_27_fu_2151_p0) + $signed(acc_26_fu_2135_p3));

assign acc_28_fu_2205_p3 = ((xor_ln68_27_fu_2191_p2[0:0] == 1'b1) ? select_ln68_26_fu_2197_p3 : acc_27_fu_2151_p2);

assign acc_29_fu_2221_p0 = A_14_q0;

assign acc_29_fu_2221_p2 = ($signed(acc_29_fu_2221_p0) + $signed(acc_28_fu_2205_p3));

assign acc_2_fu_1295_p3 = ((xor_ln68_1_fu_1281_p2[0:0] == 1'b1) ? select_ln68_fu_1287_p3 : acc_1_fu_1242_p2);

assign acc_30_fu_2275_p3 = ((xor_ln68_29_fu_2261_p2[0:0] == 1'b1) ? select_ln68_28_fu_2267_p3 : acc_29_fu_2221_p2);

assign acc_31_fu_2607_p0 = A_15_q0;

assign acc_31_fu_2607_p2 = ($signed(acc_31_fu_2607_p0) + $signed(acc_30_fu_2275_p3));

assign acc_32_fu_2661_p3 = ((xor_ln68_31_fu_2647_p2[0:0] == 1'b1) ? select_ln68_30_fu_2653_p3 : acc_31_fu_2607_p2);

assign acc_3_fu_1311_p0 = A_1_q0;

assign acc_3_fu_1311_p2 = ($signed(acc_3_fu_1311_p0) + $signed(acc_2_fu_1295_p3));

assign acc_4_fu_1365_p3 = ((xor_ln68_3_fu_1351_p2[0:0] == 1'b1) ? select_ln68_2_fu_1357_p3 : acc_3_fu_1311_p2);

assign acc_5_fu_1381_p0 = A_2_q0;

assign acc_5_fu_1381_p2 = ($signed(acc_5_fu_1381_p0) + $signed(acc_4_fu_1365_p3));

assign acc_6_fu_1435_p3 = ((xor_ln68_5_fu_1421_p2[0:0] == 1'b1) ? select_ln68_4_fu_1427_p3 : acc_5_fu_1381_p2);

assign acc_7_fu_1451_p0 = A_3_q0;

assign acc_7_fu_1451_p2 = ($signed(acc_7_fu_1451_p0) + $signed(acc_6_fu_1435_p3));

assign acc_8_fu_1505_p3 = ((xor_ln68_7_fu_1491_p2[0:0] == 1'b1) ? select_ln68_6_fu_1497_p3 : acc_7_fu_1451_p2);

assign acc_9_fu_1521_p0 = A_4_q0;

assign acc_9_fu_1521_p2 = ($signed(acc_9_fu_1521_p0) + $signed(acc_8_fu_1505_p3));

assign acc_out = acc_fu_230;

assign add_ln60_fu_1221_p2 = (ap_sig_allocacmp_jb + 7'd16);

assign add_ln68_10_fu_1877_p2 = ($signed(sext_ln68_18_fu_1863_p1) + $signed(sext_ln68_19_fu_1867_p1));

assign add_ln68_11_fu_1947_p2 = ($signed(sext_ln68_20_fu_1933_p1) + $signed(sext_ln68_21_fu_1937_p1));

assign add_ln68_12_fu_2017_p2 = ($signed(sext_ln68_22_fu_2003_p1) + $signed(sext_ln68_23_fu_2007_p1));

assign add_ln68_13_fu_2087_p2 = ($signed(sext_ln68_24_fu_2073_p1) + $signed(sext_ln68_25_fu_2077_p1));

assign add_ln68_14_fu_2157_p2 = ($signed(sext_ln68_26_fu_2143_p1) + $signed(sext_ln68_27_fu_2147_p1));

assign add_ln68_15_fu_2227_p2 = ($signed(sext_ln68_28_fu_2213_p1) + $signed(sext_ln68_29_fu_2217_p1));

assign add_ln68_16_fu_2613_p2 = ($signed(sext_ln68_30_fu_2599_p1) + $signed(sext_ln68_31_fu_2603_p1));

assign add_ln68_1_fu_1247_p2 = ($signed(sext_ln68_1_fu_1239_p1) + $signed(sext_ln68_fu_1235_p1));

assign add_ln68_2_fu_1317_p2 = ($signed(sext_ln68_2_fu_1303_p1) + $signed(sext_ln68_3_fu_1307_p1));

assign add_ln68_3_fu_1387_p2 = ($signed(sext_ln68_4_fu_1373_p1) + $signed(sext_ln68_5_fu_1377_p1));

assign add_ln68_4_fu_1457_p2 = ($signed(sext_ln68_6_fu_1443_p1) + $signed(sext_ln68_7_fu_1447_p1));

assign add_ln68_5_fu_1527_p2 = ($signed(sext_ln68_8_fu_1513_p1) + $signed(sext_ln68_9_fu_1517_p1));

assign add_ln68_6_fu_1597_p2 = ($signed(sext_ln68_10_fu_1583_p1) + $signed(sext_ln68_11_fu_1587_p1));

assign add_ln68_7_fu_1667_p2 = ($signed(sext_ln68_12_fu_1653_p1) + $signed(sext_ln68_13_fu_1657_p1));

assign add_ln68_8_fu_1737_p2 = ($signed(sext_ln68_14_fu_1723_p1) + $signed(sext_ln68_15_fu_1727_p1));

assign add_ln68_9_fu_1807_p2 = ($signed(sext_ln68_16_fu_1793_p1) + $signed(sext_ln68_17_fu_1797_p1));

assign and_ln68_10_fu_1975_p2 = (xor_ln68_20_fu_1969_p2 & tmp_189_fu_1961_p3);

assign and_ln68_11_fu_2045_p2 = (xor_ln68_22_fu_2039_p2 & tmp_191_fu_2031_p3);

assign and_ln68_12_fu_2115_p2 = (xor_ln68_24_fu_2109_p2 & tmp_193_fu_2101_p3);

assign and_ln68_13_fu_2185_p2 = (xor_ln68_26_fu_2179_p2 & tmp_195_fu_2171_p3);

assign and_ln68_14_fu_2255_p2 = (xor_ln68_28_fu_2249_p2 & tmp_197_fu_2241_p3);

assign and_ln68_15_fu_2641_p2 = (xor_ln68_30_fu_2635_p2 & tmp_199_fu_2627_p3);

assign and_ln68_1_fu_1345_p2 = (xor_ln68_2_fu_1339_p2 & tmp_171_fu_1331_p3);

assign and_ln68_2_fu_1415_p2 = (xor_ln68_4_fu_1409_p2 & tmp_173_fu_1401_p3);

assign and_ln68_3_fu_1485_p2 = (xor_ln68_6_fu_1479_p2 & tmp_175_fu_1471_p3);

assign and_ln68_4_fu_1555_p2 = (xor_ln68_8_fu_1549_p2 & tmp_177_fu_1541_p3);

assign and_ln68_5_fu_1625_p2 = (xor_ln68_10_fu_1619_p2 & tmp_179_fu_1611_p3);

assign and_ln68_6_fu_1695_p2 = (xor_ln68_12_fu_1689_p2 & tmp_181_fu_1681_p3);

assign and_ln68_7_fu_1765_p2 = (xor_ln68_14_fu_1759_p2 & tmp_183_fu_1751_p3);

assign and_ln68_8_fu_1835_p2 = (xor_ln68_16_fu_1829_p2 & tmp_185_fu_1821_p3);

assign and_ln68_9_fu_1905_p2 = (xor_ln68_18_fu_1899_p2 & tmp_187_fu_1891_p3);

assign and_ln68_fu_1275_p2 = (xor_ln68_fu_1269_p2 & tmp_169_fu_1261_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign lshr_ln_fu_1188_p4 = {{ap_sig_allocacmp_jb[5:4]}};

assign row_buf_10_out = row_buf_10_fu_278;

assign row_buf_11_out = row_buf_11_fu_282;

assign row_buf_12_out = row_buf_12_fu_286;

assign row_buf_13_out = row_buf_13_fu_290;

assign row_buf_14_out = row_buf_14_fu_294;

assign row_buf_15_out = row_buf_15_fu_298;

assign row_buf_16_out = row_buf_16_fu_302;

assign row_buf_17_out = row_buf_17_fu_306;

assign row_buf_18_out = row_buf_18_fu_310;

assign row_buf_19_out = row_buf_19_fu_314;

assign row_buf_1_out = row_buf_1_fu_242;

assign row_buf_20_out = row_buf_20_fu_318;

assign row_buf_21_out = row_buf_21_fu_322;

assign row_buf_22_out = row_buf_22_fu_326;

assign row_buf_23_out = row_buf_23_fu_330;

assign row_buf_24_out = row_buf_24_fu_334;

assign row_buf_25_out = row_buf_25_fu_338;

assign row_buf_26_out = row_buf_26_fu_342;

assign row_buf_27_out = row_buf_27_fu_346;

assign row_buf_28_out = row_buf_28_fu_350;

assign row_buf_29_out = row_buf_29_fu_354;

assign row_buf_2_out = row_buf_2_fu_246;

assign row_buf_30_out = row_buf_30_fu_358;

assign row_buf_31_out = row_buf_31_fu_362;

assign row_buf_32_out = row_buf_32_fu_366;

assign row_buf_33_out = row_buf_33_fu_370;

assign row_buf_34_out = row_buf_34_fu_374;

assign row_buf_35_out = row_buf_35_fu_378;

assign row_buf_36_out = row_buf_36_fu_382;

assign row_buf_37_out = row_buf_37_fu_386;

assign row_buf_38_out = row_buf_38_fu_390;

assign row_buf_39_out = row_buf_39_fu_394;

assign row_buf_3_out = row_buf_3_fu_250;

assign row_buf_40_out = row_buf_40_fu_398;

assign row_buf_41_out = row_buf_41_fu_402;

assign row_buf_42_out = row_buf_42_fu_406;

assign row_buf_43_out = row_buf_43_fu_410;

assign row_buf_44_out = row_buf_44_fu_414;

assign row_buf_45_out = row_buf_45_fu_418;

assign row_buf_46_out = row_buf_46_fu_422;

assign row_buf_47_out = row_buf_47_fu_426;

assign row_buf_48_out = row_buf_48_fu_430;

assign row_buf_49_out = row_buf_49_fu_434;

assign row_buf_4_out = row_buf_4_fu_254;

assign row_buf_50_out = row_buf_50_fu_438;

assign row_buf_51_out = row_buf_51_fu_442;

assign row_buf_52_out = row_buf_52_fu_446;

assign row_buf_53_out = row_buf_53_fu_450;

assign row_buf_54_out = row_buf_54_fu_454;

assign row_buf_55_out = row_buf_55_fu_458;

assign row_buf_56_out = row_buf_56_fu_462;

assign row_buf_57_out = row_buf_57_fu_466;

assign row_buf_58_out = row_buf_58_fu_470;

assign row_buf_59_out = row_buf_59_fu_474;

assign row_buf_5_out = row_buf_5_fu_258;

assign row_buf_60_out = row_buf_60_fu_478;

assign row_buf_61_out = row_buf_61_fu_482;

assign row_buf_62_out = row_buf_62_fu_486;

assign row_buf_63_out = row_buf_63_fu_490;

assign row_buf_6_out = row_buf_6_fu_262;

assign row_buf_7_out = row_buf_7_fu_266;

assign row_buf_8_out = row_buf_8_fu_270;

assign row_buf_9_out = row_buf_9_fu_274;

assign row_buf_out = row_buf_fu_238;

assign select_ln68_10_fu_1637_p3 = ((and_ln68_5_fu_1625_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_12_fu_1707_p3 = ((and_ln68_6_fu_1695_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_14_fu_1777_p3 = ((and_ln68_7_fu_1765_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_16_fu_1847_p3 = ((and_ln68_8_fu_1835_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_18_fu_1917_p3 = ((and_ln68_9_fu_1905_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_20_fu_1987_p3 = ((and_ln68_10_fu_1975_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_22_fu_2057_p3 = ((and_ln68_11_fu_2045_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_24_fu_2127_p3 = ((and_ln68_12_fu_2115_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_26_fu_2197_p3 = ((and_ln68_13_fu_2185_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_28_fu_2267_p3 = ((and_ln68_14_fu_2255_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_2_fu_1357_p3 = ((and_ln68_1_fu_1345_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_30_fu_2653_p3 = ((and_ln68_15_fu_2641_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_4_fu_1427_p3 = ((and_ln68_2_fu_1415_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_6_fu_1497_p3 = ((and_ln68_3_fu_1485_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_8_fu_1567_p3 = ((and_ln68_4_fu_1555_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln68_fu_1287_p3 = ((and_ln68_fu_1275_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign sext_ln68_10_fu_1583_p1 = acc_10_fu_1575_p3;

assign sext_ln68_11_fu_1587_p0 = A_5_q0;

assign sext_ln68_11_fu_1587_p1 = sext_ln68_11_fu_1587_p0;

assign sext_ln68_12_fu_1653_p1 = acc_12_fu_1645_p3;

assign sext_ln68_13_fu_1657_p0 = A_6_q0;

assign sext_ln68_13_fu_1657_p1 = sext_ln68_13_fu_1657_p0;

assign sext_ln68_14_fu_1723_p1 = acc_14_fu_1715_p3;

assign sext_ln68_15_fu_1727_p0 = A_7_q0;

assign sext_ln68_15_fu_1727_p1 = sext_ln68_15_fu_1727_p0;

assign sext_ln68_16_fu_1793_p1 = acc_16_fu_1785_p3;

assign sext_ln68_17_fu_1797_p0 = A_8_q0;

assign sext_ln68_17_fu_1797_p1 = sext_ln68_17_fu_1797_p0;

assign sext_ln68_18_fu_1863_p1 = acc_18_fu_1855_p3;

assign sext_ln68_19_fu_1867_p0 = A_9_q0;

assign sext_ln68_19_fu_1867_p1 = sext_ln68_19_fu_1867_p0;

assign sext_ln68_1_fu_1239_p1 = a_reg_3440;

assign sext_ln68_20_fu_1933_p1 = acc_20_fu_1925_p3;

assign sext_ln68_21_fu_1937_p0 = A_10_q0;

assign sext_ln68_21_fu_1937_p1 = sext_ln68_21_fu_1937_p0;

assign sext_ln68_22_fu_2003_p1 = acc_22_fu_1995_p3;

assign sext_ln68_23_fu_2007_p0 = A_11_q0;

assign sext_ln68_23_fu_2007_p1 = sext_ln68_23_fu_2007_p0;

assign sext_ln68_24_fu_2073_p1 = acc_24_fu_2065_p3;

assign sext_ln68_25_fu_2077_p0 = A_12_q0;

assign sext_ln68_25_fu_2077_p1 = sext_ln68_25_fu_2077_p0;

assign sext_ln68_26_fu_2143_p1 = acc_26_fu_2135_p3;

assign sext_ln68_27_fu_2147_p0 = A_13_q0;

assign sext_ln68_27_fu_2147_p1 = sext_ln68_27_fu_2147_p0;

assign sext_ln68_28_fu_2213_p1 = acc_28_fu_2205_p3;

assign sext_ln68_29_fu_2217_p0 = A_14_q0;

assign sext_ln68_29_fu_2217_p1 = sext_ln68_29_fu_2217_p0;

assign sext_ln68_2_fu_1303_p1 = acc_2_fu_1295_p3;

assign sext_ln68_30_fu_2599_p1 = acc_30_fu_2275_p3;

assign sext_ln68_31_fu_2603_p0 = A_15_q0;

assign sext_ln68_31_fu_2603_p1 = sext_ln68_31_fu_2603_p0;

assign sext_ln68_3_fu_1307_p0 = A_1_q0;

assign sext_ln68_3_fu_1307_p1 = sext_ln68_3_fu_1307_p0;

assign sext_ln68_4_fu_1373_p1 = acc_4_fu_1365_p3;

assign sext_ln68_5_fu_1377_p0 = A_2_q0;

assign sext_ln68_5_fu_1377_p1 = sext_ln68_5_fu_1377_p0;

assign sext_ln68_6_fu_1443_p1 = acc_6_fu_1435_p3;

assign sext_ln68_7_fu_1447_p0 = A_3_q0;

assign sext_ln68_7_fu_1447_p1 = sext_ln68_7_fu_1447_p0;

assign sext_ln68_8_fu_1513_p1 = acc_8_fu_1505_p3;

assign sext_ln68_9_fu_1517_p0 = A_4_q0;

assign sext_ln68_9_fu_1517_p1 = sext_ln68_9_fu_1517_p0;

assign sext_ln68_fu_1235_p0 = acc_fu_230;

assign sext_ln68_fu_1235_p1 = sext_ln68_fu_1235_p0;

assign tmp_168_fu_1253_p3 = add_ln68_1_fu_1247_p2[32'd24];

assign tmp_169_fu_1261_p3 = acc_1_fu_1242_p2[32'd23];

assign tmp_170_fu_1323_p3 = add_ln68_2_fu_1317_p2[32'd24];

assign tmp_171_fu_1331_p3 = acc_3_fu_1311_p2[32'd23];

assign tmp_172_fu_1393_p3 = add_ln68_3_fu_1387_p2[32'd24];

assign tmp_173_fu_1401_p3 = acc_5_fu_1381_p2[32'd23];

assign tmp_174_fu_1463_p3 = add_ln68_4_fu_1457_p2[32'd24];

assign tmp_175_fu_1471_p3 = acc_7_fu_1451_p2[32'd23];

assign tmp_176_fu_1533_p3 = add_ln68_5_fu_1527_p2[32'd24];

assign tmp_177_fu_1541_p3 = acc_9_fu_1521_p2[32'd23];

assign tmp_178_fu_1603_p3 = add_ln68_6_fu_1597_p2[32'd24];

assign tmp_179_fu_1611_p3 = acc_11_fu_1591_p2[32'd23];

assign tmp_180_fu_1673_p3 = add_ln68_7_fu_1667_p2[32'd24];

assign tmp_181_fu_1681_p3 = acc_13_fu_1661_p2[32'd23];

assign tmp_182_fu_1743_p3 = add_ln68_8_fu_1737_p2[32'd24];

assign tmp_183_fu_1751_p3 = acc_15_fu_1731_p2[32'd23];

assign tmp_184_fu_1813_p3 = add_ln68_9_fu_1807_p2[32'd24];

assign tmp_185_fu_1821_p3 = acc_17_fu_1801_p2[32'd23];

assign tmp_186_fu_1883_p3 = add_ln68_10_fu_1877_p2[32'd24];

assign tmp_187_fu_1891_p3 = acc_19_fu_1871_p2[32'd23];

assign tmp_188_fu_1953_p3 = add_ln68_11_fu_1947_p2[32'd24];

assign tmp_189_fu_1961_p3 = acc_21_fu_1941_p2[32'd23];

assign tmp_190_fu_2023_p3 = add_ln68_12_fu_2017_p2[32'd24];

assign tmp_191_fu_2031_p3 = acc_23_fu_2011_p2[32'd23];

assign tmp_192_fu_2093_p3 = add_ln68_13_fu_2087_p2[32'd24];

assign tmp_193_fu_2101_p3 = acc_25_fu_2081_p2[32'd23];

assign tmp_194_fu_2163_p3 = add_ln68_14_fu_2157_p2[32'd24];

assign tmp_195_fu_2171_p3 = acc_27_fu_2151_p2[32'd23];

assign tmp_196_fu_2233_p3 = add_ln68_15_fu_2227_p2[32'd24];

assign tmp_197_fu_2241_p3 = acc_29_fu_2221_p2[32'd23];

assign tmp_198_fu_2619_p3 = add_ln68_16_fu_2613_p2[32'd24];

assign tmp_199_fu_2627_p3 = acc_31_fu_2607_p2[32'd23];

assign tmp_fu_1176_p3 = ap_sig_allocacmp_jb[32'd6];

assign tmp_s_fu_1198_p3 = {{i}, {lshr_ln_fu_1188_p4}};

assign trunc_ln60_fu_1184_p1 = ap_sig_allocacmp_jb[5:0];

assign xor_ln68_10_fu_1619_p2 = (tmp_178_fu_1603_p3 ^ 1'd1);

assign xor_ln68_11_fu_1631_p2 = (tmp_179_fu_1611_p3 ^ tmp_178_fu_1603_p3);

assign xor_ln68_12_fu_1689_p2 = (tmp_180_fu_1673_p3 ^ 1'd1);

assign xor_ln68_13_fu_1701_p2 = (tmp_181_fu_1681_p3 ^ tmp_180_fu_1673_p3);

assign xor_ln68_14_fu_1759_p2 = (tmp_182_fu_1743_p3 ^ 1'd1);

assign xor_ln68_15_fu_1771_p2 = (tmp_183_fu_1751_p3 ^ tmp_182_fu_1743_p3);

assign xor_ln68_16_fu_1829_p2 = (tmp_184_fu_1813_p3 ^ 1'd1);

assign xor_ln68_17_fu_1841_p2 = (tmp_185_fu_1821_p3 ^ tmp_184_fu_1813_p3);

assign xor_ln68_18_fu_1899_p2 = (tmp_186_fu_1883_p3 ^ 1'd1);

assign xor_ln68_19_fu_1911_p2 = (tmp_187_fu_1891_p3 ^ tmp_186_fu_1883_p3);

assign xor_ln68_1_fu_1281_p2 = (tmp_169_fu_1261_p3 ^ tmp_168_fu_1253_p3);

assign xor_ln68_20_fu_1969_p2 = (tmp_188_fu_1953_p3 ^ 1'd1);

assign xor_ln68_21_fu_1981_p2 = (tmp_189_fu_1961_p3 ^ tmp_188_fu_1953_p3);

assign xor_ln68_22_fu_2039_p2 = (tmp_190_fu_2023_p3 ^ 1'd1);

assign xor_ln68_23_fu_2051_p2 = (tmp_191_fu_2031_p3 ^ tmp_190_fu_2023_p3);

assign xor_ln68_24_fu_2109_p2 = (tmp_192_fu_2093_p3 ^ 1'd1);

assign xor_ln68_25_fu_2121_p2 = (tmp_193_fu_2101_p3 ^ tmp_192_fu_2093_p3);

assign xor_ln68_26_fu_2179_p2 = (tmp_194_fu_2163_p3 ^ 1'd1);

assign xor_ln68_27_fu_2191_p2 = (tmp_195_fu_2171_p3 ^ tmp_194_fu_2163_p3);

assign xor_ln68_28_fu_2249_p2 = (tmp_196_fu_2233_p3 ^ 1'd1);

assign xor_ln68_29_fu_2261_p2 = (tmp_197_fu_2241_p3 ^ tmp_196_fu_2233_p3);

assign xor_ln68_2_fu_1339_p2 = (tmp_170_fu_1323_p3 ^ 1'd1);

assign xor_ln68_30_fu_2635_p2 = (tmp_198_fu_2619_p3 ^ 1'd1);

assign xor_ln68_31_fu_2647_p2 = (tmp_199_fu_2627_p3 ^ tmp_198_fu_2619_p3);

assign xor_ln68_3_fu_1351_p2 = (tmp_171_fu_1331_p3 ^ tmp_170_fu_1323_p3);

assign xor_ln68_4_fu_1409_p2 = (tmp_172_fu_1393_p3 ^ 1'd1);

assign xor_ln68_5_fu_1421_p2 = (tmp_173_fu_1401_p3 ^ tmp_172_fu_1393_p3);

assign xor_ln68_6_fu_1479_p2 = (tmp_174_fu_1463_p3 ^ 1'd1);

assign xor_ln68_7_fu_1491_p2 = (tmp_175_fu_1471_p3 ^ tmp_174_fu_1463_p3);

assign xor_ln68_8_fu_1549_p2 = (tmp_176_fu_1533_p3 ^ 1'd1);

assign xor_ln68_9_fu_1561_p2 = (tmp_177_fu_1541_p3 ^ tmp_176_fu_1533_p3);

assign xor_ln68_fu_1269_p2 = (tmp_168_fu_1253_p3 ^ 1'd1);

assign zext_ln66_fu_1206_p1 = tmp_s_fu_1198_p3;

always @ (posedge ap_clk) begin
    zext_ln66_reg_3341[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
end

endmodule //top_kernel_top_kernel_Pipeline_VITIS_LOOP_60_3
