// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_top_kernel_Pipeline_VITIS_LOOP_92_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i_2,
        rowC_7_address0,
        rowC_7_ce0,
        rowC_7_we0,
        rowC_7_d0,
        rowC_6_address0,
        rowC_6_ce0,
        rowC_6_we0,
        rowC_6_d0,
        rowC_5_address0,
        rowC_5_ce0,
        rowC_5_we0,
        rowC_5_d0,
        rowC_4_address0,
        rowC_4_ce0,
        rowC_4_we0,
        rowC_4_d0,
        rowC_3_address0,
        rowC_3_ce0,
        rowC_3_we0,
        rowC_3_d0,
        rowC_2_address0,
        rowC_2_ce0,
        rowC_2_we0,
        rowC_2_d0,
        rowC_1_address0,
        rowC_1_ce0,
        rowC_1_we0,
        rowC_1_d0,
        rowC_address0,
        rowC_ce0,
        rowC_we0,
        rowC_d0,
        scale_reload,
        scale_1_reload,
        scale_2_reload,
        scale_3_reload,
        scale_4_reload,
        scale_5_reload,
        scale_6_reload,
        scale_7_reload,
        scale_8_reload,
        scale_9_reload,
        scale_10_reload,
        scale_11_reload,
        scale_12_reload,
        scale_13_reload,
        scale_14_reload,
        scale_15_reload,
        scale_16_reload,
        scale_17_reload,
        scale_18_reload,
        scale_19_reload,
        scale_20_reload,
        scale_21_reload,
        scale_22_reload,
        scale_23_reload,
        scale_24_reload,
        scale_25_reload,
        scale_26_reload,
        scale_27_reload,
        scale_28_reload,
        scale_29_reload,
        scale_30_reload,
        scale_31_reload,
        scale_32_reload,
        scale_33_reload,
        scale_34_reload,
        scale_35_reload,
        scale_36_reload,
        scale_37_reload,
        scale_38_reload,
        scale_39_reload,
        scale_40_reload,
        scale_41_reload,
        scale_42_reload,
        scale_43_reload,
        scale_44_reload,
        scale_45_reload,
        scale_46_reload,
        scale_47_reload,
        scale_48_reload,
        scale_49_reload,
        scale_50_reload,
        scale_51_reload,
        scale_52_reload,
        scale_53_reload,
        scale_54_reload,
        scale_55_reload,
        scale_56_reload,
        scale_57_reload,
        scale_58_reload,
        scale_59_reload,
        scale_60_reload,
        scale_61_reload,
        scale_62_reload,
        scale_63_reload,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_address0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_q0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_address0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_q0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_address0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_q0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_address0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_q0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_address0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_q0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_address0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_q0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_address0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_q0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_address0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0,
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] i_2;
output  [2:0] rowC_7_address0;
output   rowC_7_ce0;
output   rowC_7_we0;
output  [23:0] rowC_7_d0;
output  [2:0] rowC_6_address0;
output   rowC_6_ce0;
output   rowC_6_we0;
output  [23:0] rowC_6_d0;
output  [2:0] rowC_5_address0;
output   rowC_5_ce0;
output   rowC_5_we0;
output  [23:0] rowC_5_d0;
output  [2:0] rowC_4_address0;
output   rowC_4_ce0;
output   rowC_4_we0;
output  [23:0] rowC_4_d0;
output  [2:0] rowC_3_address0;
output   rowC_3_ce0;
output   rowC_3_we0;
output  [23:0] rowC_3_d0;
output  [2:0] rowC_2_address0;
output   rowC_2_ce0;
output   rowC_2_we0;
output  [23:0] rowC_2_d0;
output  [2:0] rowC_1_address0;
output   rowC_1_ce0;
output   rowC_1_we0;
output  [23:0] rowC_1_d0;
output  [2:0] rowC_address0;
output   rowC_ce0;
output   rowC_we0;
output  [23:0] rowC_d0;
input  [23:0] scale_reload;
input  [23:0] scale_1_reload;
input  [23:0] scale_2_reload;
input  [23:0] scale_3_reload;
input  [23:0] scale_4_reload;
input  [23:0] scale_5_reload;
input  [23:0] scale_6_reload;
input  [23:0] scale_7_reload;
input  [23:0] scale_8_reload;
input  [23:0] scale_9_reload;
input  [23:0] scale_10_reload;
input  [23:0] scale_11_reload;
input  [23:0] scale_12_reload;
input  [23:0] scale_13_reload;
input  [23:0] scale_14_reload;
input  [23:0] scale_15_reload;
input  [23:0] scale_16_reload;
input  [23:0] scale_17_reload;
input  [23:0] scale_18_reload;
input  [23:0] scale_19_reload;
input  [23:0] scale_20_reload;
input  [23:0] scale_21_reload;
input  [23:0] scale_22_reload;
input  [23:0] scale_23_reload;
input  [23:0] scale_24_reload;
input  [23:0] scale_25_reload;
input  [23:0] scale_26_reload;
input  [23:0] scale_27_reload;
input  [23:0] scale_28_reload;
input  [23:0] scale_29_reload;
input  [23:0] scale_30_reload;
input  [23:0] scale_31_reload;
input  [23:0] scale_32_reload;
input  [23:0] scale_33_reload;
input  [23:0] scale_34_reload;
input  [23:0] scale_35_reload;
input  [23:0] scale_36_reload;
input  [23:0] scale_37_reload;
input  [23:0] scale_38_reload;
input  [23:0] scale_39_reload;
input  [23:0] scale_40_reload;
input  [23:0] scale_41_reload;
input  [23:0] scale_42_reload;
input  [23:0] scale_43_reload;
input  [23:0] scale_44_reload;
input  [23:0] scale_45_reload;
input  [23:0] scale_46_reload;
input  [23:0] scale_47_reload;
input  [23:0] scale_48_reload;
input  [23:0] scale_49_reload;
input  [23:0] scale_50_reload;
input  [23:0] scale_51_reload;
input  [23:0] scale_52_reload;
input  [23:0] scale_53_reload;
input  [23:0] scale_54_reload;
input  [23:0] scale_55_reload;
input  [23:0] scale_56_reload;
input  [23:0] scale_57_reload;
input  [23:0] scale_58_reload;
input  [23:0] scale_59_reload;
input  [23:0] scale_60_reload;
input  [23:0] scale_61_reload;
input  [23:0] scale_62_reload;
input  [23:0] scale_63_reload;
output  [10:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_address0;
output   top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0;
input  [23:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_q0;
output  [10:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_address0;
output   top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0;
input  [23:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_q0;
output  [10:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_address0;
output   top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0;
input  [23:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_q0;
output  [10:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_address0;
output   top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0;
input  [23:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_q0;
output  [10:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_address0;
output   top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0;
input  [23:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_q0;
output  [10:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_address0;
output   top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0;
input  [23:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_q0;
output  [10:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_address0;
output   top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0;
input  [23:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_q0;
output  [10:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_address0;
output   top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0;
input  [23:0] top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln92_fu_1006_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] trunc_ln92_1_fu_1022_p1;
reg   [2:0] trunc_ln92_1_reg_1630;
reg   [2:0] trunc_ln92_1_reg_1630_pp0_iter1_reg;
wire   [2:0] lshr_ln1_fu_1026_p4;
reg   [2:0] lshr_ln1_reg_1635;
reg   [2:0] lshr_ln1_reg_1635_pp0_iter1_reg;
wire   [23:0] tmp_2_fu_1056_p131;
reg   [23:0] tmp_2_reg_1680;
reg  signed [23:0] tmp_2_reg_1680_pp0_iter1_reg;
wire   [23:0] tmp_1_fu_1343_p19;
reg  signed [23:0] tmp_1_reg_1685;
wire   [63:0] zext_ln94_1_fu_1044_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln92_fu_1382_p1;
reg   [6:0] j_fu_392;
wire   [6:0] add_ln92_fu_1012_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_1;
reg    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0_local;
reg    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0_local;
reg    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0_local;
reg    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0_local;
reg    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0_local;
reg    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0_local;
reg    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0_local;
reg    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0_local;
reg    rowC_6_we0_local;
wire   [23:0] select_ln94_3_fu_1603_p3;
reg    rowC_6_ce0_local;
reg    rowC_5_we0_local;
reg    rowC_5_ce0_local;
reg    rowC_4_we0_local;
reg    rowC_4_ce0_local;
reg    rowC_3_we0_local;
reg    rowC_3_ce0_local;
reg    rowC_2_we0_local;
reg    rowC_2_ce0_local;
reg    rowC_1_we0_local;
reg    rowC_1_ce0_local;
reg    rowC_we0_local;
reg    rowC_ce0_local;
reg    rowC_7_we0_local;
reg    rowC_7_ce0_local;
wire   [10:0] tmp_s_fu_1036_p3;
wire   [23:0] tmp_2_fu_1056_p129;
wire   [5:0] tmp_2_fu_1056_p130;
wire   [23:0] tmp_1_fu_1343_p17;
wire   [47:0] mul_ln94_fu_994_p2;
wire   [0:0] tmp_3_fu_1419_p3;
wire   [23:0] trunc_ln5_fu_1409_p4;
wire   [23:0] zext_ln94_fu_1435_p1;
wire   [23:0] add_ln94_fu_1439_p2;
wire   [0:0] tmp_5_fu_1445_p3;
wire   [0:0] tmp_4_fu_1427_p3;
wire   [0:0] xor_ln94_fu_1453_p2;
wire   [8:0] tmp_7_fu_1473_p3;
wire   [9:0] tmp_8_fu_1487_p3;
wire   [0:0] and_ln94_fu_1459_p2;
wire   [0:0] icmp_ln94_1_fu_1495_p2;
wire   [0:0] icmp_ln94_2_fu_1501_p2;
wire   [0:0] tmp_6_fu_1465_p3;
wire   [0:0] icmp_ln94_fu_1481_p2;
wire   [0:0] xor_ln94_1_fu_1515_p2;
wire   [0:0] and_ln94_1_fu_1521_p2;
wire   [0:0] select_ln94_fu_1507_p3;
wire   [0:0] xor_ln94_2_fu_1541_p2;
wire   [0:0] tmp_fu_1401_p3;
wire   [0:0] or_ln94_fu_1547_p2;
wire   [0:0] xor_ln94_3_fu_1553_p2;
wire   [0:0] select_ln94_1_fu_1527_p3;
wire   [0:0] and_ln94_2_fu_1535_p2;
wire   [0:0] and_ln94_4_fu_1565_p2;
wire   [0:0] or_ln94_2_fu_1571_p2;
wire   [0:0] xor_ln94_4_fu_1577_p2;
wire   [0:0] and_ln94_3_fu_1559_p2;
wire   [0:0] and_ln94_5_fu_1583_p2;
wire   [0:0] or_ln94_1_fu_1597_p2;
wire   [23:0] select_ln94_2_fu_1589_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [5:0] tmp_2_fu_1056_p1;
wire   [5:0] tmp_2_fu_1056_p3;
wire   [5:0] tmp_2_fu_1056_p5;
wire   [5:0] tmp_2_fu_1056_p7;
wire   [5:0] tmp_2_fu_1056_p9;
wire   [5:0] tmp_2_fu_1056_p11;
wire   [5:0] tmp_2_fu_1056_p13;
wire   [5:0] tmp_2_fu_1056_p15;
wire   [5:0] tmp_2_fu_1056_p17;
wire   [5:0] tmp_2_fu_1056_p19;
wire   [5:0] tmp_2_fu_1056_p21;
wire   [5:0] tmp_2_fu_1056_p23;
wire   [5:0] tmp_2_fu_1056_p25;
wire   [5:0] tmp_2_fu_1056_p27;
wire   [5:0] tmp_2_fu_1056_p29;
wire   [5:0] tmp_2_fu_1056_p31;
wire   [5:0] tmp_2_fu_1056_p33;
wire   [5:0] tmp_2_fu_1056_p35;
wire   [5:0] tmp_2_fu_1056_p37;
wire   [5:0] tmp_2_fu_1056_p39;
wire   [5:0] tmp_2_fu_1056_p41;
wire   [5:0] tmp_2_fu_1056_p43;
wire   [5:0] tmp_2_fu_1056_p45;
wire   [5:0] tmp_2_fu_1056_p47;
wire   [5:0] tmp_2_fu_1056_p49;
wire   [5:0] tmp_2_fu_1056_p51;
wire   [5:0] tmp_2_fu_1056_p53;
wire   [5:0] tmp_2_fu_1056_p55;
wire   [5:0] tmp_2_fu_1056_p57;
wire   [5:0] tmp_2_fu_1056_p59;
wire   [5:0] tmp_2_fu_1056_p61;
wire   [5:0] tmp_2_fu_1056_p63;
wire  signed [5:0] tmp_2_fu_1056_p65;
wire  signed [5:0] tmp_2_fu_1056_p67;
wire  signed [5:0] tmp_2_fu_1056_p69;
wire  signed [5:0] tmp_2_fu_1056_p71;
wire  signed [5:0] tmp_2_fu_1056_p73;
wire  signed [5:0] tmp_2_fu_1056_p75;
wire  signed [5:0] tmp_2_fu_1056_p77;
wire  signed [5:0] tmp_2_fu_1056_p79;
wire  signed [5:0] tmp_2_fu_1056_p81;
wire  signed [5:0] tmp_2_fu_1056_p83;
wire  signed [5:0] tmp_2_fu_1056_p85;
wire  signed [5:0] tmp_2_fu_1056_p87;
wire  signed [5:0] tmp_2_fu_1056_p89;
wire  signed [5:0] tmp_2_fu_1056_p91;
wire  signed [5:0] tmp_2_fu_1056_p93;
wire  signed [5:0] tmp_2_fu_1056_p95;
wire  signed [5:0] tmp_2_fu_1056_p97;
wire  signed [5:0] tmp_2_fu_1056_p99;
wire  signed [5:0] tmp_2_fu_1056_p101;
wire  signed [5:0] tmp_2_fu_1056_p103;
wire  signed [5:0] tmp_2_fu_1056_p105;
wire  signed [5:0] tmp_2_fu_1056_p107;
wire  signed [5:0] tmp_2_fu_1056_p109;
wire  signed [5:0] tmp_2_fu_1056_p111;
wire  signed [5:0] tmp_2_fu_1056_p113;
wire  signed [5:0] tmp_2_fu_1056_p115;
wire  signed [5:0] tmp_2_fu_1056_p117;
wire  signed [5:0] tmp_2_fu_1056_p119;
wire  signed [5:0] tmp_2_fu_1056_p121;
wire  signed [5:0] tmp_2_fu_1056_p123;
wire  signed [5:0] tmp_2_fu_1056_p125;
wire  signed [5:0] tmp_2_fu_1056_p127;
wire   [2:0] tmp_1_fu_1343_p1;
wire   [2:0] tmp_1_fu_1343_p3;
wire   [2:0] tmp_1_fu_1343_p5;
wire   [2:0] tmp_1_fu_1343_p7;
wire  signed [2:0] tmp_1_fu_1343_p9;
wire  signed [2:0] tmp_1_fu_1343_p11;
wire  signed [2:0] tmp_1_fu_1343_p13;
wire  signed [2:0] tmp_1_fu_1343_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_392 = 7'd0;
#0 ap_done_reg = 1'b0;
end

top_kernel_mul_24s_24s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 48 ))
mul_24s_24s_48_1_1_U248(
    .din0(tmp_2_reg_1680_pp0_iter1_reg),
    .din1(tmp_1_reg_1685),
    .dout(mul_ln94_fu_994_p2)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_129_6_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h0 ),
    .din0_WIDTH( 24 ),
    .CASE1( 6'h1 ),
    .din1_WIDTH( 24 ),
    .CASE2( 6'h2 ),
    .din2_WIDTH( 24 ),
    .CASE3( 6'h3 ),
    .din3_WIDTH( 24 ),
    .CASE4( 6'h4 ),
    .din4_WIDTH( 24 ),
    .CASE5( 6'h5 ),
    .din5_WIDTH( 24 ),
    .CASE6( 6'h6 ),
    .din6_WIDTH( 24 ),
    .CASE7( 6'h7 ),
    .din7_WIDTH( 24 ),
    .CASE8( 6'h8 ),
    .din8_WIDTH( 24 ),
    .CASE9( 6'h9 ),
    .din9_WIDTH( 24 ),
    .CASE10( 6'hA ),
    .din10_WIDTH( 24 ),
    .CASE11( 6'hB ),
    .din11_WIDTH( 24 ),
    .CASE12( 6'hC ),
    .din12_WIDTH( 24 ),
    .CASE13( 6'hD ),
    .din13_WIDTH( 24 ),
    .CASE14( 6'hE ),
    .din14_WIDTH( 24 ),
    .CASE15( 6'hF ),
    .din15_WIDTH( 24 ),
    .CASE16( 6'h10 ),
    .din16_WIDTH( 24 ),
    .CASE17( 6'h11 ),
    .din17_WIDTH( 24 ),
    .CASE18( 6'h12 ),
    .din18_WIDTH( 24 ),
    .CASE19( 6'h13 ),
    .din19_WIDTH( 24 ),
    .CASE20( 6'h14 ),
    .din20_WIDTH( 24 ),
    .CASE21( 6'h15 ),
    .din21_WIDTH( 24 ),
    .CASE22( 6'h16 ),
    .din22_WIDTH( 24 ),
    .CASE23( 6'h17 ),
    .din23_WIDTH( 24 ),
    .CASE24( 6'h18 ),
    .din24_WIDTH( 24 ),
    .CASE25( 6'h19 ),
    .din25_WIDTH( 24 ),
    .CASE26( 6'h1A ),
    .din26_WIDTH( 24 ),
    .CASE27( 6'h1B ),
    .din27_WIDTH( 24 ),
    .CASE28( 6'h1C ),
    .din28_WIDTH( 24 ),
    .CASE29( 6'h1D ),
    .din29_WIDTH( 24 ),
    .CASE30( 6'h1E ),
    .din30_WIDTH( 24 ),
    .CASE31( 6'h1F ),
    .din31_WIDTH( 24 ),
    .CASE32( 6'h20 ),
    .din32_WIDTH( 24 ),
    .CASE33( 6'h21 ),
    .din33_WIDTH( 24 ),
    .CASE34( 6'h22 ),
    .din34_WIDTH( 24 ),
    .CASE35( 6'h23 ),
    .din35_WIDTH( 24 ),
    .CASE36( 6'h24 ),
    .din36_WIDTH( 24 ),
    .CASE37( 6'h25 ),
    .din37_WIDTH( 24 ),
    .CASE38( 6'h26 ),
    .din38_WIDTH( 24 ),
    .CASE39( 6'h27 ),
    .din39_WIDTH( 24 ),
    .CASE40( 6'h28 ),
    .din40_WIDTH( 24 ),
    .CASE41( 6'h29 ),
    .din41_WIDTH( 24 ),
    .CASE42( 6'h2A ),
    .din42_WIDTH( 24 ),
    .CASE43( 6'h2B ),
    .din43_WIDTH( 24 ),
    .CASE44( 6'h2C ),
    .din44_WIDTH( 24 ),
    .CASE45( 6'h2D ),
    .din45_WIDTH( 24 ),
    .CASE46( 6'h2E ),
    .din46_WIDTH( 24 ),
    .CASE47( 6'h2F ),
    .din47_WIDTH( 24 ),
    .CASE48( 6'h30 ),
    .din48_WIDTH( 24 ),
    .CASE49( 6'h31 ),
    .din49_WIDTH( 24 ),
    .CASE50( 6'h32 ),
    .din50_WIDTH( 24 ),
    .CASE51( 6'h33 ),
    .din51_WIDTH( 24 ),
    .CASE52( 6'h34 ),
    .din52_WIDTH( 24 ),
    .CASE53( 6'h35 ),
    .din53_WIDTH( 24 ),
    .CASE54( 6'h36 ),
    .din54_WIDTH( 24 ),
    .CASE55( 6'h37 ),
    .din55_WIDTH( 24 ),
    .CASE56( 6'h38 ),
    .din56_WIDTH( 24 ),
    .CASE57( 6'h39 ),
    .din57_WIDTH( 24 ),
    .CASE58( 6'h3A ),
    .din58_WIDTH( 24 ),
    .CASE59( 6'h3B ),
    .din59_WIDTH( 24 ),
    .CASE60( 6'h3C ),
    .din60_WIDTH( 24 ),
    .CASE61( 6'h3D ),
    .din61_WIDTH( 24 ),
    .CASE62( 6'h3E ),
    .din62_WIDTH( 24 ),
    .CASE63( 6'h3F ),
    .din63_WIDTH( 24 ),
    .def_WIDTH( 24 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 24 ))
sparsemux_129_6_24_1_1_U249(
    .din0(scale_reload),
    .din1(scale_1_reload),
    .din2(scale_2_reload),
    .din3(scale_3_reload),
    .din4(scale_4_reload),
    .din5(scale_5_reload),
    .din6(scale_6_reload),
    .din7(scale_7_reload),
    .din8(scale_8_reload),
    .din9(scale_9_reload),
    .din10(scale_10_reload),
    .din11(scale_11_reload),
    .din12(scale_12_reload),
    .din13(scale_13_reload),
    .din14(scale_14_reload),
    .din15(scale_15_reload),
    .din16(scale_16_reload),
    .din17(scale_17_reload),
    .din18(scale_18_reload),
    .din19(scale_19_reload),
    .din20(scale_20_reload),
    .din21(scale_21_reload),
    .din22(scale_22_reload),
    .din23(scale_23_reload),
    .din24(scale_24_reload),
    .din25(scale_25_reload),
    .din26(scale_26_reload),
    .din27(scale_27_reload),
    .din28(scale_28_reload),
    .din29(scale_29_reload),
    .din30(scale_30_reload),
    .din31(scale_31_reload),
    .din32(scale_32_reload),
    .din33(scale_33_reload),
    .din34(scale_34_reload),
    .din35(scale_35_reload),
    .din36(scale_36_reload),
    .din37(scale_37_reload),
    .din38(scale_38_reload),
    .din39(scale_39_reload),
    .din40(scale_40_reload),
    .din41(scale_41_reload),
    .din42(scale_42_reload),
    .din43(scale_43_reload),
    .din44(scale_44_reload),
    .din45(scale_45_reload),
    .din46(scale_46_reload),
    .din47(scale_47_reload),
    .din48(scale_48_reload),
    .din49(scale_49_reload),
    .din50(scale_50_reload),
    .din51(scale_51_reload),
    .din52(scale_52_reload),
    .din53(scale_53_reload),
    .din54(scale_54_reload),
    .din55(scale_55_reload),
    .din56(scale_56_reload),
    .din57(scale_57_reload),
    .din58(scale_58_reload),
    .din59(scale_59_reload),
    .din60(scale_60_reload),
    .din61(scale_61_reload),
    .din62(scale_62_reload),
    .din63(scale_63_reload),
    .def(tmp_2_fu_1056_p129),
    .sel(tmp_2_fu_1056_p130),
    .dout(tmp_2_fu_1056_p131)
);

(* dissolve_hierarchy = "yes" *) top_kernel_sparsemux_17_3_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 24 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 24 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 24 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 24 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 24 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 24 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 24 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 24 ),
    .def_WIDTH( 24 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 24 ))
sparsemux_17_3_24_1_1_U250(
    .din0(top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_q0),
    .din1(top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_q0),
    .din2(top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_q0),
    .din3(top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_q0),
    .din4(top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_q0),
    .din5(top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_q0),
    .din6(top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_q0),
    .din7(top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_q0),
    .def(tmp_1_fu_1343_p17),
    .sel(trunc_ln92_1_reg_1630),
    .dout(tmp_1_fu_1343_p19)
);

top_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln92_fu_1006_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_392 <= add_ln92_fu_1012_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_392 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        lshr_ln1_reg_1635 <= {{ap_sig_allocacmp_j_1[5:3]}};
        lshr_ln1_reg_1635_pp0_iter1_reg <= lshr_ln1_reg_1635;
        tmp_1_reg_1685 <= tmp_1_fu_1343_p19;
        tmp_2_reg_1680 <= tmp_2_fu_1056_p131;
        tmp_2_reg_1680_pp0_iter1_reg <= tmp_2_reg_1680;
        trunc_ln92_1_reg_1630 <= trunc_ln92_1_fu_1022_p1;
        trunc_ln92_1_reg_1630_pp0_iter1_reg <= trunc_ln92_1_reg_1630;
    end
end

always @ (*) begin
    if (((icmp_ln92_fu_1006_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_392;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rowC_1_ce0_local = 1'b1;
    end else begin
        rowC_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln92_1_reg_1630_pp0_iter1_reg == 3'd1))) begin
        rowC_1_we0_local = 1'b1;
    end else begin
        rowC_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rowC_2_ce0_local = 1'b1;
    end else begin
        rowC_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln92_1_reg_1630_pp0_iter1_reg == 3'd2))) begin
        rowC_2_we0_local = 1'b1;
    end else begin
        rowC_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rowC_3_ce0_local = 1'b1;
    end else begin
        rowC_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln92_1_reg_1630_pp0_iter1_reg == 3'd3))) begin
        rowC_3_we0_local = 1'b1;
    end else begin
        rowC_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rowC_4_ce0_local = 1'b1;
    end else begin
        rowC_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln92_1_reg_1630_pp0_iter1_reg == 3'd4))) begin
        rowC_4_we0_local = 1'b1;
    end else begin
        rowC_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rowC_5_ce0_local = 1'b1;
    end else begin
        rowC_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln92_1_reg_1630_pp0_iter1_reg == 3'd5))) begin
        rowC_5_we0_local = 1'b1;
    end else begin
        rowC_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rowC_6_ce0_local = 1'b1;
    end else begin
        rowC_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln92_1_reg_1630_pp0_iter1_reg == 3'd6))) begin
        rowC_6_we0_local = 1'b1;
    end else begin
        rowC_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rowC_7_ce0_local = 1'b1;
    end else begin
        rowC_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln92_1_reg_1630_pp0_iter1_reg == 3'd7))) begin
        rowC_7_we0_local = 1'b1;
    end else begin
        rowC_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        rowC_ce0_local = 1'b1;
    end else begin
        rowC_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln92_1_reg_1630_pp0_iter1_reg == 3'd0))) begin
        rowC_we0_local = 1'b1;
    end else begin
        rowC_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0_local = 1'b1;
    end else begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0_local = 1'b1;
    end else begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0_local = 1'b1;
    end else begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0_local = 1'b1;
    end else begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0_local = 1'b1;
    end else begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0_local = 1'b1;
    end else begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0_local = 1'b1;
    end else begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0_local = 1'b1;
    end else begin
        top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln92_fu_1012_p2 = (ap_sig_allocacmp_j_1 + 7'd1);

assign add_ln94_fu_1439_p2 = (trunc_ln5_fu_1409_p4 + zext_ln94_fu_1435_p1);

assign and_ln94_1_fu_1521_p2 = (xor_ln94_1_fu_1515_p2 & icmp_ln94_fu_1481_p2);

assign and_ln94_2_fu_1535_p2 = (icmp_ln94_1_fu_1495_p2 & and_ln94_fu_1459_p2);

assign and_ln94_3_fu_1559_p2 = (xor_ln94_3_fu_1553_p2 & or_ln94_fu_1547_p2);

assign and_ln94_4_fu_1565_p2 = (tmp_5_fu_1445_p3 & select_ln94_1_fu_1527_p3);

assign and_ln94_5_fu_1583_p2 = (xor_ln94_4_fu_1577_p2 & tmp_fu_1401_p3);

assign and_ln94_fu_1459_p2 = (xor_ln94_fu_1453_p2 & tmp_4_fu_1427_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln92_fu_1006_p2 = ((ap_sig_allocacmp_j_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln94_1_fu_1495_p2 = ((tmp_8_fu_1487_p3 == 10'd1023) ? 1'b1 : 1'b0);

assign icmp_ln94_2_fu_1501_p2 = ((tmp_8_fu_1487_p3 == 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln94_fu_1481_p2 = ((tmp_7_fu_1473_p3 == 9'd511) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_1026_p4 = {{ap_sig_allocacmp_j_1[5:3]}};

assign or_ln94_1_fu_1597_p2 = (and_ln94_5_fu_1583_p2 | and_ln94_3_fu_1559_p2);

assign or_ln94_2_fu_1571_p2 = (and_ln94_4_fu_1565_p2 | and_ln94_2_fu_1535_p2);

assign or_ln94_fu_1547_p2 = (xor_ln94_2_fu_1541_p2 | tmp_5_fu_1445_p3);

assign rowC_1_address0 = zext_ln92_fu_1382_p1;

assign rowC_1_ce0 = rowC_1_ce0_local;

assign rowC_1_d0 = select_ln94_3_fu_1603_p3;

assign rowC_1_we0 = rowC_1_we0_local;

assign rowC_2_address0 = zext_ln92_fu_1382_p1;

assign rowC_2_ce0 = rowC_2_ce0_local;

assign rowC_2_d0 = select_ln94_3_fu_1603_p3;

assign rowC_2_we0 = rowC_2_we0_local;

assign rowC_3_address0 = zext_ln92_fu_1382_p1;

assign rowC_3_ce0 = rowC_3_ce0_local;

assign rowC_3_d0 = select_ln94_3_fu_1603_p3;

assign rowC_3_we0 = rowC_3_we0_local;

assign rowC_4_address0 = zext_ln92_fu_1382_p1;

assign rowC_4_ce0 = rowC_4_ce0_local;

assign rowC_4_d0 = select_ln94_3_fu_1603_p3;

assign rowC_4_we0 = rowC_4_we0_local;

assign rowC_5_address0 = zext_ln92_fu_1382_p1;

assign rowC_5_ce0 = rowC_5_ce0_local;

assign rowC_5_d0 = select_ln94_3_fu_1603_p3;

assign rowC_5_we0 = rowC_5_we0_local;

assign rowC_6_address0 = zext_ln92_fu_1382_p1;

assign rowC_6_ce0 = rowC_6_ce0_local;

assign rowC_6_d0 = select_ln94_3_fu_1603_p3;

assign rowC_6_we0 = rowC_6_we0_local;

assign rowC_7_address0 = zext_ln92_fu_1382_p1;

assign rowC_7_ce0 = rowC_7_ce0_local;

assign rowC_7_d0 = select_ln94_3_fu_1603_p3;

assign rowC_7_we0 = rowC_7_we0_local;

assign rowC_address0 = zext_ln92_fu_1382_p1;

assign rowC_ce0 = rowC_ce0_local;

assign rowC_d0 = select_ln94_3_fu_1603_p3;

assign rowC_we0 = rowC_we0_local;

assign select_ln94_1_fu_1527_p3 = ((and_ln94_fu_1459_p2[0:0] == 1'b1) ? and_ln94_1_fu_1521_p2 : icmp_ln94_1_fu_1495_p2);

assign select_ln94_2_fu_1589_p3 = ((and_ln94_3_fu_1559_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln94_3_fu_1603_p3 = ((or_ln94_1_fu_1597_p2[0:0] == 1'b1) ? select_ln94_2_fu_1589_p3 : add_ln94_fu_1439_p2);

assign select_ln94_fu_1507_p3 = ((and_ln94_fu_1459_p2[0:0] == 1'b1) ? icmp_ln94_1_fu_1495_p2 : icmp_ln94_2_fu_1501_p2);

assign tmp_1_fu_1343_p17 = 'bx;

assign tmp_2_fu_1056_p129 = 'bx;

assign tmp_2_fu_1056_p130 = ap_sig_allocacmp_j_1[5:0];

assign tmp_3_fu_1419_p3 = mul_ln94_fu_994_p2[32'd13];

assign tmp_4_fu_1427_p3 = mul_ln94_fu_994_p2[32'd37];

assign tmp_5_fu_1445_p3 = add_ln94_fu_1439_p2[32'd23];

assign tmp_6_fu_1465_p3 = mul_ln94_fu_994_p2[32'd38];

assign tmp_7_fu_1473_p3 = {{mul_ln94_fu_994_p2[47:39]}};

assign tmp_8_fu_1487_p3 = {{mul_ln94_fu_994_p2[47:38]}};

assign tmp_fu_1401_p3 = mul_ln94_fu_994_p2[32'd47];

assign tmp_s_fu_1036_p3 = {{i_2}, {lshr_ln1_fu_1026_p4}};

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_address0 = zext_ln94_1_fu_1044_p1;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0 = top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0_local;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_address0 = zext_ln94_1_fu_1044_p1;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0 = top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0_local;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_address0 = zext_ln94_1_fu_1044_p1;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0 = top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0_local;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_address0 = zext_ln94_1_fu_1044_p1;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0 = top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0_local;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_address0 = zext_ln94_1_fu_1044_p1;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0 = top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0_local;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_address0 = zext_ln94_1_fu_1044_p1;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0 = top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0_local;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_address0 = zext_ln94_1_fu_1044_p1;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0 = top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0_local;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_address0 = zext_ln94_1_fu_1044_p1;

assign top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0 = top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0_local;

assign trunc_ln5_fu_1409_p4 = {{mul_ln94_fu_994_p2[37:14]}};

assign trunc_ln92_1_fu_1022_p1 = ap_sig_allocacmp_j_1[2:0];

assign xor_ln94_1_fu_1515_p2 = (tmp_6_fu_1465_p3 ^ 1'd1);

assign xor_ln94_2_fu_1541_p2 = (select_ln94_fu_1507_p3 ^ 1'd1);

assign xor_ln94_3_fu_1553_p2 = (tmp_fu_1401_p3 ^ 1'd1);

assign xor_ln94_4_fu_1577_p2 = (or_ln94_2_fu_1571_p2 ^ 1'd1);

assign xor_ln94_fu_1453_p2 = (tmp_5_fu_1445_p3 ^ 1'd1);

assign zext_ln92_fu_1382_p1 = lshr_ln1_reg_1635_pp0_iter1_reg;

assign zext_ln94_1_fu_1044_p1 = tmp_s_fu_1036_p3;

assign zext_ln94_fu_1435_p1 = tmp_3_fu_1419_p3;

endmodule //top_kernel_top_kernel_Pipeline_VITIS_LOOP_92_9
