

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "4", "7", "10", "14"],
		"CDFG" : "top_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "78669", "EstimateLatencyMax" : "78669",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "2", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_31_2_fu_596", "Port" : "A", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "7", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_39_3_fu_674", "Port" : "A", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "C", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "14", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_71_8_VITIS_LOOP_72_9_fu_816", "Port" : "C", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "tmp", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_55_5_VITIS_LOOP_56_6_fu_604", "Port" : "tmp", "Inst_start_state" : "2", "Inst_end_state" : "6"},
					{"ID" : "7", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_39_3_fu_674", "Port" : "tmp", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "14", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_71_8_VITIS_LOOP_72_9_fu_816", "Port" : "tmp", "Inst_start_state" : "9", "Inst_end_state" : "10"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_27_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "10", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state5"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state6"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.tmp_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_31_2_fu_596", "Parent" : "0", "Child" : ["3"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_31_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "66", "EstimateLatencyMax" : "66",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "zext_ln41", "Type" : "None", "Direction" : "I"},
			{"Name" : "A", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_31_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_31_2_fu_596.flow_control_loop_pipe_sequential_init_U", "Parent" : "2"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_55_5_VITIS_LOOP_56_6_fu_604", "Parent" : "0", "Child" : ["5", "6"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_55_5_VITIS_LOOP_56_6",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16386", "EstimateLatencyMax" : "16386",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_1_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_2_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_3_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_4_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_5_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_6_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_7_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_8_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_9_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_10_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_11_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_12_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_13_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_14_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_15_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_16_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_17_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_18_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_19_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_20_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_21_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_22_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_23_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_24_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_25_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_26_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_27_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_28_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_29_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_30_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_31_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_32_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_33_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_34_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_35_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_36_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_37_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_38_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_39_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_40_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_41_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_42_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_43_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_44_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_45_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_46_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_47_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_48_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_49_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_50_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_51_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_52_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_53_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_54_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_55_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_56_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_57_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_58_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_59_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_60_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_61_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_62_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "col_sum_63_load_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "tmp", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_55_5_VITIS_LOOP_56_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_55_5_VITIS_LOOP_56_6_fu_604.sparsemux_129_6_24_1_1_U10", "Parent" : "4"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_55_5_VITIS_LOOP_56_6_fu_604.flow_control_loop_pipe_sequential_init_U", "Parent" : "4"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_39_3_fu_674", "Parent" : "0", "Child" : ["8", "9"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_39_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "109", "EstimateLatencyMax" : "109",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "zext_ln41", "Type" : "None", "Direction" : "I"},
			{"Name" : "A", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "conv_i362", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_39_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter44", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter44", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_39_3_fu_674.sdiv_40ns_24s_40_44_1_U4", "Parent" : "7"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_39_3_fu_674.flow_control_loop_pipe_sequential_init_U", "Parent" : "7"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_63_7_fu_684", "Parent" : "0", "Child" : ["11", "12", "13"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_63_7",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "66", "EstimateLatencyMax" : "66",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_1_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_2_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_3_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_4_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_5_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_6_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_7_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_8_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_9_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_10_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_11_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_12_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_13_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_14_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_15_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_16_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_17_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_18_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_19_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_20_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_21_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_22_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_23_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_24_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_25_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_26_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_27_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_28_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_29_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_30_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_31_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_32_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_33_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_34_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_35_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_36_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_37_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_38_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_39_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_40_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_41_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_42_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_43_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_44_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_45_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_46_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_47_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_48_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_49_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_50_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_51_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_52_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_53_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_54_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_55_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_56_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_57_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_58_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_59_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_60_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_61_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_62_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_63_load_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_63_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_62_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_61_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_60_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_59_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_58_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_57_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_56_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_55_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_54_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_53_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_52_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_51_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_50_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_49_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_48_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_47_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_46_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_45_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_44_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_43_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_42_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_41_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_40_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_39_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_38_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_37_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_36_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_35_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_34_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_33_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_32_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_31_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_30_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_29_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_28_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_27_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_26_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_25_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_24_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_23_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_22_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_21_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_20_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_19_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_18_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_17_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_16_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_15_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_14_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_12_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_10_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_9_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_7_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_63_7", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_63_7_fu_684.mul_40s_42ns_81_1_1_U77", "Parent" : "10"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_63_7_fu_684.sparsemux_129_6_24_1_1_U78", "Parent" : "10"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_63_7_fu_684.flow_control_loop_pipe_sequential_init_U", "Parent" : "10"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_71_8_VITIS_LOOP_72_9_fu_816", "Parent" : "0", "Child" : ["15", "16", "17"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_71_8_VITIS_LOOP_72_9",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16387", "EstimateLatencyMax" : "16387",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "C", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "scale_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_3_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_4_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_5_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_6_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_7_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_8_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_9_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_10_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_11_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_12_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_13_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_14_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_15_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_16_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_17_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_18_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_19_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_20_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_21_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_22_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_23_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_24_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_25_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_26_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_27_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_28_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_29_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_30_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_31_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_32_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_33_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_34_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_35_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_36_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_37_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_38_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_39_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_40_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_41_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_42_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_43_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_44_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_45_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_46_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_47_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_48_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_49_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_50_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_51_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_52_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_53_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_54_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_55_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_56_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_57_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_58_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_59_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_60_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_61_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_62_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_63_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "tmp", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_71_8_VITIS_LOOP_72_9", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_71_8_VITIS_LOOP_72_9_fu_816.mul_24s_24s_48_1_1_U208", "Parent" : "14"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_71_8_VITIS_LOOP_72_9_fu_816.sparsemux_129_6_24_1_1_U209", "Parent" : "14"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_71_8_VITIS_LOOP_72_9_fu_816.flow_control_loop_pipe_sequential_init_U", "Parent" : "14"}]}
