

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "12", "30", "48"],
		"CDFG" : "top_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "34065", "EstimateLatencyMax" : "34065",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_66_4_fu_630", "Port" : "A_0", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "A_0", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "A_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_66_4_fu_630", "Port" : "A_1", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "A_1", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "A_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_66_4_fu_630", "Port" : "A_2", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "A_2", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "A_3", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_66_4_fu_630", "Port" : "A_3", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "A_3", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "A_4", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_66_4_fu_630", "Port" : "A_4", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "A_4", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "A_5", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_66_4_fu_630", "Port" : "A_5", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "A_5", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "A_6", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_66_4_fu_630", "Port" : "A_6", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "A_6", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "A_7", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_66_4_fu_630", "Port" : "A_7", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "A_7", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "C_0", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "C_0", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "C_1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "C_1", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "C_2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "C_2", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "C_3", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "C_3", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "C_4", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "C_4", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "C_5", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "C_5", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "C_6", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "C_6", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "C_7", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "C_7", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_1", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_1", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_2", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_2", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_4", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_4", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_6", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_6", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_7", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "48", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_7", "Inst_start_state" : "7", "Inst_end_state" : "8"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_62_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "8", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state5"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state6"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_4_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_6_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_7_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_66_4_fu_630", "Parent" : "0", "Child" : ["10", "11"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_66_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "66", "EstimateLatencyMax" : "66",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "i", "Type" : "None", "Direction" : "I"},
			{"Name" : "A_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_66_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_66_4_fu_630.sparsemux_17_3_24_1_1_U1", "Parent" : "9"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_66_4_fu_630.flow_control_loop_pipe_sequential_init_U", "Parent" : "9"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652", "Parent" : "0", "Child" : ["13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_88_7",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_bank_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_1_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_2_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_3_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_4_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_5_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_6_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_7_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_8_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_9_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_10_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_11_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_12_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_13_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_14_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_15_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_16_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_17_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_18_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_19_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_20_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_21_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_22_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_23_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_24_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_25_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_26_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_27_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_28_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_29_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_30_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_31_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_32_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_33_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_34_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_35_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_36_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_37_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_38_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_39_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_40_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_41_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_42_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_43_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_44_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_45_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_46_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_47_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_48_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_49_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_50_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_51_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_52_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_53_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_54_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_55_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_56_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_57_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_58_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_59_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_60_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_61_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_62_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_63_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_63_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_62_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_61_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_60_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_59_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_58_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_57_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_56_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_55_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_54_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_53_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_52_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_51_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_50_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_49_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_48_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_47_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_46_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_45_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_44_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_43_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_42_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_41_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_40_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_39_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_38_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_37_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_36_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_35_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_34_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_33_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_32_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_31_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_30_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_29_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_28_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_27_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_26_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_25_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_24_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_23_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_22_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_21_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_20_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_19_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_18_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_17_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_16_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_15_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_14_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_12_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_10_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_9_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_7_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_bank_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_88_7", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.mul_40s_42ns_81_1_1_U112", "Parent" : "12"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.mul_40s_42ns_81_1_1_U113", "Parent" : "12"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.mul_40s_42ns_81_1_1_U114", "Parent" : "12"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.mul_40s_42ns_81_1_1_U115", "Parent" : "12"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.mul_40s_42ns_81_1_1_U116", "Parent" : "12"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.mul_40s_42ns_81_1_1_U117", "Parent" : "12"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.mul_40s_42ns_81_1_1_U118", "Parent" : "12"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.mul_40s_42ns_81_1_1_U119", "Parent" : "12"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.sparsemux_17_3_24_1_1_U120", "Parent" : "12"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.sparsemux_17_3_24_1_1_U121", "Parent" : "12"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.sparsemux_17_3_24_1_1_U122", "Parent" : "12"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.sparsemux_17_3_24_1_1_U123", "Parent" : "12"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.sparsemux_17_3_24_1_1_U124", "Parent" : "12"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.sparsemux_17_3_24_1_1_U125", "Parent" : "12"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.sparsemux_17_3_24_1_1_U126", "Parent" : "12"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.sparsemux_17_3_24_1_1_U127", "Parent" : "12"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_88_7_fu_652.flow_control_loop_pipe_sequential_init_U", "Parent" : "12"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784", "Parent" : "0", "Child" : ["31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_74_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "55", "EstimateLatencyMax" : "55",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_bank_56", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "conv_i349", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_bank_57", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_58", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_59", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_60", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_61", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_62", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_63", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_48", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_49", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_50", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_51", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_52", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_53", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_54", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_55", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_40", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_41", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_42", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_43", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_44", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_45", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_46", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_47", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_32", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_33", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_34", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_35", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_36", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_37", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_38", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_39", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_24", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_25", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_26", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_27", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_28", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_29", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_30", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_31", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_16", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_17", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_18", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_19", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_20", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_21", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_22", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_23", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_9", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_15", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "zext_ln80", "Type" : "None", "Direction" : "I"},
			{"Name" : "A_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "A_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "col_sum_bank_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_bank_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_74_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter46", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter46", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sdiv_40ns_24s_40_44_1_U13", "Parent" : "30"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sdiv_40ns_24s_40_44_1_U14", "Parent" : "30"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sdiv_40ns_24s_40_44_1_U15", "Parent" : "30"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sdiv_40ns_24s_40_44_1_U16", "Parent" : "30"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sdiv_40ns_24s_40_44_1_U17", "Parent" : "30"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sdiv_40ns_24s_40_44_1_U18", "Parent" : "30"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sdiv_40ns_24s_40_44_1_U19", "Parent" : "30"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sdiv_40ns_24s_40_44_1_U20", "Parent" : "30"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sparsemux_17_3_24_1_1_U21", "Parent" : "30"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sparsemux_17_3_24_1_1_U22", "Parent" : "30"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sparsemux_17_3_24_1_1_U23", "Parent" : "30"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sparsemux_17_3_24_1_1_U24", "Parent" : "30"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sparsemux_17_3_24_1_1_U25", "Parent" : "30"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sparsemux_17_3_24_1_1_U26", "Parent" : "30"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sparsemux_17_3_24_1_1_U27", "Parent" : "30"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.sparsemux_17_3_24_1_1_U28", "Parent" : "30"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_74_5_fu_784.flow_control_loop_pipe_sequential_init_U", "Parent" : "30"},
	{"ID" : "48", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886", "Parent" : "0", "Child" : ["49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2051", "EstimateLatencyMax" : "2051",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "C_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "C_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "C_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "C_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "C_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "C_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "C_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "C_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "scale_bank_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_3_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_4_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_5_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_6_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_7_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_8_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_9_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_10_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_11_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_12_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_13_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_14_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_15_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_16_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_17_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_18_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_19_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_20_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_21_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_22_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_23_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_24_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_25_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_26_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_27_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_28_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_29_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_30_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_31_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_32_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_33_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_34_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_35_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_36_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_37_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_38_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_39_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_40_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_41_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_42_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_43_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_44_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_45_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_46_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_47_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_48_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_49_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_50_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_51_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_52_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_53_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_54_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_55_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_56_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_57_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_58_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_59_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_60_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_61_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_62_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_bank_63_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_100_9_VITIS_LOOP_101_10", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.mul_24s_24s_48_1_1_U257", "Parent" : "48"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.mul_24s_24s_48_1_1_U258", "Parent" : "48"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.mul_24s_24s_48_1_1_U259", "Parent" : "48"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.mul_24s_24s_48_1_1_U260", "Parent" : "48"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.mul_24s_24s_48_1_1_U261", "Parent" : "48"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.mul_24s_24s_48_1_1_U262", "Parent" : "48"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.mul_24s_24s_48_1_1_U263", "Parent" : "48"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.mul_24s_24s_48_1_1_U264", "Parent" : "48"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.sparsemux_17_3_24_1_1_U265", "Parent" : "48"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.sparsemux_17_3_24_1_1_U266", "Parent" : "48"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.sparsemux_17_3_24_1_1_U267", "Parent" : "48"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.sparsemux_17_3_24_1_1_U268", "Parent" : "48"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.sparsemux_17_3_24_1_1_U269", "Parent" : "48"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.sparsemux_17_3_24_1_1_U270", "Parent" : "48"},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.sparsemux_17_3_24_1_1_U271", "Parent" : "48"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.sparsemux_17_3_24_1_1_U272", "Parent" : "48"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_100_9_VITIS_LOOP_101_10_fu_886.flow_control_loop_pipe_sequential_init_U", "Parent" : "48"}]}
