

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "11", "15", "41"],
		"CDFG" : "top_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "40009", "EstimateLatencyMax" : "40009",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_43_3_fu_858", "Port" : "A", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "C", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "41", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212", "Port" : "C", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "41", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_1", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "41", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_1", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_2", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "41", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_2", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "41", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_4", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "41", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_4", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "41", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_6", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "41", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_6", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "15", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_7", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "41", "SubInstance" : "grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212", "Port" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_7", "Inst_start_state" : "7", "Inst_end_state" : "8"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_36_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "8", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state5"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state6"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_4_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_6_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_7_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_43_3_fu_858", "Parent" : "0", "Child" : ["10"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_43_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "66", "EstimateLatencyMax" : "66",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "zext_ln45", "Type" : "None", "Direction" : "I"},
			{"Name" : "A", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "row_buf_63_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_62_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_61_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_60_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_59_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_58_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_57_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_56_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_55_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_54_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_53_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_52_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_51_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_50_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_49_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_48_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_47_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_46_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_45_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_44_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_43_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_42_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_41_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_40_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_39_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_38_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_37_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_36_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_35_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_34_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_33_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_32_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_31_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_30_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_29_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_28_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_27_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_26_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_25_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_24_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_23_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_22_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_21_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_20_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_19_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_18_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_17_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_16_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_15_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_14_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_12_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_10_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_9_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_7_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "row_buf_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_43_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_43_3_fu_858.flow_control_loop_pipe_sequential_init_U", "Parent" : "9"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_67_5_fu_930", "Parent" : "0", "Child" : ["12", "13", "14"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_67_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "66", "EstimateLatencyMax" : "66",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_1_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_2_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_3_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_4_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_5_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_6_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_7_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_8_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_9_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_10_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_11_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_12_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_13_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_14_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_15_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_16_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_17_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_18_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_19_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_20_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_21_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_22_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_23_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_24_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_25_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_26_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_27_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_28_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_29_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_30_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_31_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_32_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_33_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_34_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_35_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_36_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_37_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_38_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_39_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_40_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_41_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_42_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_43_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_44_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_45_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_46_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_47_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_48_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_49_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_50_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_51_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_52_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_53_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_54_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_55_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_56_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_57_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_58_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_59_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_60_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_61_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_62_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_63_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_63_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_62_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_61_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_60_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_59_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_58_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_57_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_56_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_55_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_54_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_53_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_52_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_51_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_50_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_49_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_48_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_47_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_46_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_45_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_44_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_43_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_42_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_41_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_40_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_39_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_38_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_37_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_36_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_35_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_34_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_33_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_32_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_31_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_30_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_29_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_28_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_27_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_26_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_25_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_24_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_23_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_22_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_21_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_20_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_19_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_18_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_17_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_16_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_15_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_14_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_13_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_12_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_11_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_10_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_9_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_7_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_6_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_4_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_2_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_1_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "scale_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_67_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_67_5_fu_930.mul_40s_42ns_81_1_1_U232", "Parent" : "11"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_67_5_fu_930.sparsemux_129_6_24_1_1_U233", "Parent" : "11"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_67_5_fu_930.flow_control_loop_pipe_sequential_init_U", "Parent" : "11"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062", "Parent" : "0", "Child" : ["16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_54_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "54", "EstimateLatencyMax" : "54",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "col_sum_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_7_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_15_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_23_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_31_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_39_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_47_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_55_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_63_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv_i343", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_15", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_23", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_31", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_39", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_47", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_55", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_63", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_6_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_14_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_22_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_30_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_38_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_46_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_54_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_62_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_22", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_30", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_38", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_46", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_54", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_62", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_5_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_13_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_21_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_29_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_37_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_45_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_53_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_61_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_21", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_29", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_37", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_45", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_53", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_61", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_4_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_12_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_20_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_28_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_36_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_44_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_52_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_60_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_20", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_28", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_36", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_44", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_52", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_60", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_3_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_11_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_19_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_27_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_35_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_43_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_51_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_59_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_19", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_27", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_35", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_43", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_51", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_59", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_10_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_18_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_26_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_34_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_42_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_50_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_58_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_18", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_26", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_34", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_42", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_50", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_58", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_9_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_17_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_25_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_33_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_41_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_49_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_57_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_9", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_17", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_25", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_33", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_41", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_49", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_57", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "i", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_sum_56", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_48", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_40", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_32", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_24", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_16", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "col_sum_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "row_buf_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_8_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_16_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_24_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_32_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_40_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_48_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_buf_56_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_54_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter45", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter45", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U68", "Parent" : "15"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sdiv_40ns_24s_40_44_1_U69", "Parent" : "15"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U70", "Parent" : "15"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sdiv_40ns_24s_40_44_1_U71", "Parent" : "15"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U72", "Parent" : "15"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sdiv_40ns_24s_40_44_1_U73", "Parent" : "15"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U74", "Parent" : "15"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sdiv_40ns_24s_40_44_1_U75", "Parent" : "15"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U76", "Parent" : "15"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sdiv_40ns_24s_40_44_1_U77", "Parent" : "15"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U78", "Parent" : "15"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sdiv_40ns_24s_40_44_1_U79", "Parent" : "15"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U80", "Parent" : "15"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sdiv_40ns_24s_40_44_1_U81", "Parent" : "15"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U82", "Parent" : "15"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sdiv_40ns_24s_40_44_1_U83", "Parent" : "15"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U84", "Parent" : "15"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U85", "Parent" : "15"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U86", "Parent" : "15"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U87", "Parent" : "15"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U88", "Parent" : "15"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U89", "Parent" : "15"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U90", "Parent" : "15"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.sparsemux_17_6_24_1_1_U91", "Parent" : "15"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_54_4_fu_1062.flow_control_loop_pipe_sequential_init_U", "Parent" : "15"},
	{"ID" : "41", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212", "Parent" : "0", "Child" : ["42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52"],
		"CDFG" : "top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "8195", "EstimateLatencyMax" : "8195",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "C", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "scale_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_8_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_16_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_24_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_32_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_40_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_48_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_56_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_1_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_9_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_17_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_25_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_33_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_41_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_49_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_57_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_2_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_10_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_18_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_26_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_34_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_42_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_50_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_58_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_3_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_11_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_19_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_27_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_35_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_43_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_51_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_59_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_4_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_12_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_20_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_28_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_36_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_44_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_52_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_60_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_5_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_13_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_21_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_29_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_37_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_45_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_53_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_61_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_6_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_14_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_22_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_30_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_38_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_46_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_54_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_62_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_7_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_15_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_23_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_31_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_39_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_47_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_55_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "scale_63_reload", "Type" : "None", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "top_kernel_ap_fixed_64_ap_fixed_24_8_0_0_0_64_tmp", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_73_6_VITIS_LOOP_74_7", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212.mul_24s_24s_48_1_1_U364", "Parent" : "41"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212.mul_24s_24s_48_1_1_U365", "Parent" : "41"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212.sparsemux_17_6_24_1_1_U366", "Parent" : "41"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212.sparsemux_17_6_24_1_1_U367", "Parent" : "41"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212.sparsemux_17_6_24_1_1_U368", "Parent" : "41"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212.sparsemux_17_6_24_1_1_U369", "Parent" : "41"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212.sparsemux_17_6_24_1_1_U370", "Parent" : "41"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212.sparsemux_17_6_24_1_1_U371", "Parent" : "41"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212.sparsemux_17_6_24_1_1_U372", "Parent" : "41"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212.sparsemux_17_6_24_1_1_U373", "Parent" : "41"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_top_kernel_Pipeline_VITIS_LOOP_73_6_VITIS_LOOP_74_7_fu_1212.flow_control_loop_pipe_sequential_init_U", "Parent" : "41"}]}
