// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2025.1.1 (64-bit)
// Tool Version Limit: 2025.05
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// 
// ==============================================================

extern "C" void AESL_WRAP_top_kernel (
volatile void* A_0,
volatile void* A_1,
volatile void* A_2,
volatile void* A_3,
volatile void* A_4,
volatile void* A_5,
volatile void* A_6,
volatile void* A_7,
volatile void* A_8,
volatile void* A_9,
volatile void* A_10,
volatile void* A_11,
volatile void* A_12,
volatile void* A_13,
volatile void* A_14,
volatile void* A_15,
volatile void* A_16,
volatile void* A_17,
volatile void* A_18,
volatile void* A_19,
volatile void* A_20,
volatile void* A_21,
volatile void* A_22,
volatile void* A_23,
volatile void* A_24,
volatile void* A_25,
volatile void* A_26,
volatile void* A_27,
volatile void* A_28,
volatile void* A_29,
volatile void* A_30,
volatile void* A_31,
volatile void* C_0,
volatile void* C_1,
volatile void* C_2,
volatile void* C_3,
volatile void* C_4,
volatile void* C_5,
volatile void* C_6,
volatile void* C_7,
volatile void* C_8,
volatile void* C_9,
volatile void* C_10,
volatile void* C_11,
volatile void* C_12,
volatile void* C_13,
volatile void* C_14,
volatile void* C_15,
volatile void* C_16,
volatile void* C_17,
volatile void* C_18,
volatile void* C_19,
volatile void* C_20,
volatile void* C_21,
volatile void* C_22,
volatile void* C_23,
volatile void* C_24,
volatile void* C_25,
volatile void* C_26,
volatile void* C_27,
volatile void* C_28,
volatile void* C_29,
volatile void* C_30,
volatile void* C_31);
