-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_kernel_top_kernel_Pipeline_VITIS_LOOP_87_8_VITIS_LOOP_88_9 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_C_0_AWVALID : OUT STD_LOGIC;
    m_axi_C_0_AWREADY : IN STD_LOGIC;
    m_axi_C_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_C_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_C_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_C_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_C_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_C_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_C_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_C_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_C_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_C_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_C_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_C_0_WVALID : OUT STD_LOGIC;
    m_axi_C_0_WREADY : IN STD_LOGIC;
    m_axi_C_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_C_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_C_0_WLAST : OUT STD_LOGIC;
    m_axi_C_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_C_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_C_0_ARVALID : OUT STD_LOGIC;
    m_axi_C_0_ARREADY : IN STD_LOGIC;
    m_axi_C_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_C_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_C_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_C_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_C_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_C_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_C_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_C_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_C_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_C_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_C_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_C_0_RVALID : IN STD_LOGIC;
    m_axi_C_0_RREADY : OUT STD_LOGIC;
    m_axi_C_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_C_0_RLAST : IN STD_LOGIC;
    m_axi_C_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_C_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_C_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_C_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_C_0_BVALID : IN STD_LOGIC;
    m_axi_C_0_BREADY : OUT STD_LOGIC;
    m_axi_C_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_C_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_C_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln87 : IN STD_LOGIC_VECTOR (61 downto 0);
    scale_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_1_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_2_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_3_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_4_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_5_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_6_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_7_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_8_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_9_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_10_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_11_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_12_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_13_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_14_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_15_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_16_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_17_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_18_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_19_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_20_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_21_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_22_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_23_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_24_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_25_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_26_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_27_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_28_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_29_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_30_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_31_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_32_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_33_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_34_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_35_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_36_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_37_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_38_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_39_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_40_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_41_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_42_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_43_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_44_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_45_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_46_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_47_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_48_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_49_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_50_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_51_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_52_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_53_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_54_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_55_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_56_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_57_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_58_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_59_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_60_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_61_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_62_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    scale_63_reload : IN STD_LOGIC_VECTOR (23 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_9_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_9_ce0 : OUT STD_LOGIC;
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_9_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_8_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_8_ce0 : OUT STD_LOGIC;
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_8_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0 : OUT STD_LOGIC;
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0 : OUT STD_LOGIC;
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0 : OUT STD_LOGIC;
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0 : OUT STD_LOGIC;
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0 : OUT STD_LOGIC;
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0 : OUT STD_LOGIC;
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0 : OUT STD_LOGIC;
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0 : OUT STD_LOGIC;
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_5_ce0 : OUT STD_LOGIC;
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_5_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_4_ce0 : OUT STD_LOGIC;
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_4_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_3_ce0 : OUT STD_LOGIC;
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_3_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_2_ce0 : OUT STD_LOGIC;
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_2_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_1_ce0 : OUT STD_LOGIC;
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_1_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_s_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_s_ce0 : OUT STD_LOGIC;
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_s_q0 : IN STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of top_kernel_top_kernel_Pipeline_VITIS_LOOP_87_8_VITIS_LOOP_88_9 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv15_4000 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv24_7FFFFF : STD_LOGIC_VECTOR (23 downto 0) := "011111111111111111111111";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln87_fu_1080_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal C_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln88_2_fu_1134_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln88_2_reg_1784 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_1176_p131 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_2_reg_1869 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_fu_1541_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_1874 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln90_fu_1579_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal add_ln90_reg_1879 : STD_LOGIC_VECTOR (23 downto 0);
    signal and_ln90_fu_1599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln90_reg_1884 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_1_fu_1635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_1_reg_1889 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln90_3_fu_1693_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln90_3_reg_1894 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln90_4_fu_1699_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln90_4_reg_1900 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln90_3_fu_1737_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln90_3_reg_1905 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln90_2_fu_1156_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal j_fu_436 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln88_fu_1440_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (6 downto 0);
    signal i_fu_440 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal select_ln87_1_fu_1118_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (8 downto 0);
    signal indvar_flatten6_fu_444 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln87_1_fu_1086_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (14 downto 0);
    signal top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_9_ce0_local : STD_LOGIC;
    signal top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_8_ce0_local : STD_LOGIC;
    signal top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0_local : STD_LOGIC;
    signal top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0_local : STD_LOGIC;
    signal top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0_local : STD_LOGIC;
    signal top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0_local : STD_LOGIC;
    signal top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0_local : STD_LOGIC;
    signal top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0_local : STD_LOGIC;
    signal top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0_local : STD_LOGIC;
    signal top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0_local : STD_LOGIC;
    signal p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_5_ce0_local : STD_LOGIC;
    signal p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_4_ce0_local : STD_LOGIC;
    signal p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_3_ce0_local : STD_LOGIC;
    signal p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_2_ce0_local : STD_LOGIC;
    signal p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_1_ce0_local : STD_LOGIC;
    signal p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_s_ce0_local : STD_LOGIC;
    signal icmp_ln88_fu_1104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln87_fu_1098_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln87_fu_1110_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln88_fu_1126_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln1_fu_1138_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_1148_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_2_fu_1176_p129 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_2_fu_1176_p130 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_1461_p33 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_1_fu_1461_p35 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln90_fu_1054_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_3_fu_1559_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln5_fu_1549_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln90_fu_1575_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_5_fu_1585_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_1567_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln90_fu_1593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_1613_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_8_fu_1627_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln90_2_fu_1641_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_1605_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_fu_1621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln90_1_fu_1655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln90_1_fu_1661_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln90_fu_1647_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln90_2_fu_1675_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln90_fu_1681_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln90_3_fu_1687_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln90_1_fu_1667_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln90_2_fu_1705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln90_2_fu_1709_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln90_4_fu_1714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln90_5_fu_1720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln90_1_fu_1732_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln90_2_fu_1725_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_2_fu_1176_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p13 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p15 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p17 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p19 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p21 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p23 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p25 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p27 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p29 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p31 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p33 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p35 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p37 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p39 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p41 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p43 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p45 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p47 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p49 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p51 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p53 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p55 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p57 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p59 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p61 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p63 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p65 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p67 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p69 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p71 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p73 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p75 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p77 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p79 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p81 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p83 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p85 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p87 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p89 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p91 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p93 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p95 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p97 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p99 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p101 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p103 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p105 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p107 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p109 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p111 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p113 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p115 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p117 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p119 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p121 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p123 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p125 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_2_fu_1176_p127 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_1461_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_1461_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component top_kernel_mul_24s_24s_48_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component top_kernel_sparsemux_129_6_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (5 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (5 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (5 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (5 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (5 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (5 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (5 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (5 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (5 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (5 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (5 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (5 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (5 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (5 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (5 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (5 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (5 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (5 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (5 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (5 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (5 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (5 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (5 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (5 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (5 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (5 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (5 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (5 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (5 downto 0);
        din28_WIDTH : INTEGER;
        CASE29 : STD_LOGIC_VECTOR (5 downto 0);
        din29_WIDTH : INTEGER;
        CASE30 : STD_LOGIC_VECTOR (5 downto 0);
        din30_WIDTH : INTEGER;
        CASE31 : STD_LOGIC_VECTOR (5 downto 0);
        din31_WIDTH : INTEGER;
        CASE32 : STD_LOGIC_VECTOR (5 downto 0);
        din32_WIDTH : INTEGER;
        CASE33 : STD_LOGIC_VECTOR (5 downto 0);
        din33_WIDTH : INTEGER;
        CASE34 : STD_LOGIC_VECTOR (5 downto 0);
        din34_WIDTH : INTEGER;
        CASE35 : STD_LOGIC_VECTOR (5 downto 0);
        din35_WIDTH : INTEGER;
        CASE36 : STD_LOGIC_VECTOR (5 downto 0);
        din36_WIDTH : INTEGER;
        CASE37 : STD_LOGIC_VECTOR (5 downto 0);
        din37_WIDTH : INTEGER;
        CASE38 : STD_LOGIC_VECTOR (5 downto 0);
        din38_WIDTH : INTEGER;
        CASE39 : STD_LOGIC_VECTOR (5 downto 0);
        din39_WIDTH : INTEGER;
        CASE40 : STD_LOGIC_VECTOR (5 downto 0);
        din40_WIDTH : INTEGER;
        CASE41 : STD_LOGIC_VECTOR (5 downto 0);
        din41_WIDTH : INTEGER;
        CASE42 : STD_LOGIC_VECTOR (5 downto 0);
        din42_WIDTH : INTEGER;
        CASE43 : STD_LOGIC_VECTOR (5 downto 0);
        din43_WIDTH : INTEGER;
        CASE44 : STD_LOGIC_VECTOR (5 downto 0);
        din44_WIDTH : INTEGER;
        CASE45 : STD_LOGIC_VECTOR (5 downto 0);
        din45_WIDTH : INTEGER;
        CASE46 : STD_LOGIC_VECTOR (5 downto 0);
        din46_WIDTH : INTEGER;
        CASE47 : STD_LOGIC_VECTOR (5 downto 0);
        din47_WIDTH : INTEGER;
        CASE48 : STD_LOGIC_VECTOR (5 downto 0);
        din48_WIDTH : INTEGER;
        CASE49 : STD_LOGIC_VECTOR (5 downto 0);
        din49_WIDTH : INTEGER;
        CASE50 : STD_LOGIC_VECTOR (5 downto 0);
        din50_WIDTH : INTEGER;
        CASE51 : STD_LOGIC_VECTOR (5 downto 0);
        din51_WIDTH : INTEGER;
        CASE52 : STD_LOGIC_VECTOR (5 downto 0);
        din52_WIDTH : INTEGER;
        CASE53 : STD_LOGIC_VECTOR (5 downto 0);
        din53_WIDTH : INTEGER;
        CASE54 : STD_LOGIC_VECTOR (5 downto 0);
        din54_WIDTH : INTEGER;
        CASE55 : STD_LOGIC_VECTOR (5 downto 0);
        din55_WIDTH : INTEGER;
        CASE56 : STD_LOGIC_VECTOR (5 downto 0);
        din56_WIDTH : INTEGER;
        CASE57 : STD_LOGIC_VECTOR (5 downto 0);
        din57_WIDTH : INTEGER;
        CASE58 : STD_LOGIC_VECTOR (5 downto 0);
        din58_WIDTH : INTEGER;
        CASE59 : STD_LOGIC_VECTOR (5 downto 0);
        din59_WIDTH : INTEGER;
        CASE60 : STD_LOGIC_VECTOR (5 downto 0);
        din60_WIDTH : INTEGER;
        CASE61 : STD_LOGIC_VECTOR (5 downto 0);
        din61_WIDTH : INTEGER;
        CASE62 : STD_LOGIC_VECTOR (5 downto 0);
        din62_WIDTH : INTEGER;
        CASE63 : STD_LOGIC_VECTOR (5 downto 0);
        din63_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        din3 : IN STD_LOGIC_VECTOR (23 downto 0);
        din4 : IN STD_LOGIC_VECTOR (23 downto 0);
        din5 : IN STD_LOGIC_VECTOR (23 downto 0);
        din6 : IN STD_LOGIC_VECTOR (23 downto 0);
        din7 : IN STD_LOGIC_VECTOR (23 downto 0);
        din8 : IN STD_LOGIC_VECTOR (23 downto 0);
        din9 : IN STD_LOGIC_VECTOR (23 downto 0);
        din10 : IN STD_LOGIC_VECTOR (23 downto 0);
        din11 : IN STD_LOGIC_VECTOR (23 downto 0);
        din12 : IN STD_LOGIC_VECTOR (23 downto 0);
        din13 : IN STD_LOGIC_VECTOR (23 downto 0);
        din14 : IN STD_LOGIC_VECTOR (23 downto 0);
        din15 : IN STD_LOGIC_VECTOR (23 downto 0);
        din16 : IN STD_LOGIC_VECTOR (23 downto 0);
        din17 : IN STD_LOGIC_VECTOR (23 downto 0);
        din18 : IN STD_LOGIC_VECTOR (23 downto 0);
        din19 : IN STD_LOGIC_VECTOR (23 downto 0);
        din20 : IN STD_LOGIC_VECTOR (23 downto 0);
        din21 : IN STD_LOGIC_VECTOR (23 downto 0);
        din22 : IN STD_LOGIC_VECTOR (23 downto 0);
        din23 : IN STD_LOGIC_VECTOR (23 downto 0);
        din24 : IN STD_LOGIC_VECTOR (23 downto 0);
        din25 : IN STD_LOGIC_VECTOR (23 downto 0);
        din26 : IN STD_LOGIC_VECTOR (23 downto 0);
        din27 : IN STD_LOGIC_VECTOR (23 downto 0);
        din28 : IN STD_LOGIC_VECTOR (23 downto 0);
        din29 : IN STD_LOGIC_VECTOR (23 downto 0);
        din30 : IN STD_LOGIC_VECTOR (23 downto 0);
        din31 : IN STD_LOGIC_VECTOR (23 downto 0);
        din32 : IN STD_LOGIC_VECTOR (23 downto 0);
        din33 : IN STD_LOGIC_VECTOR (23 downto 0);
        din34 : IN STD_LOGIC_VECTOR (23 downto 0);
        din35 : IN STD_LOGIC_VECTOR (23 downto 0);
        din36 : IN STD_LOGIC_VECTOR (23 downto 0);
        din37 : IN STD_LOGIC_VECTOR (23 downto 0);
        din38 : IN STD_LOGIC_VECTOR (23 downto 0);
        din39 : IN STD_LOGIC_VECTOR (23 downto 0);
        din40 : IN STD_LOGIC_VECTOR (23 downto 0);
        din41 : IN STD_LOGIC_VECTOR (23 downto 0);
        din42 : IN STD_LOGIC_VECTOR (23 downto 0);
        din43 : IN STD_LOGIC_VECTOR (23 downto 0);
        din44 : IN STD_LOGIC_VECTOR (23 downto 0);
        din45 : IN STD_LOGIC_VECTOR (23 downto 0);
        din46 : IN STD_LOGIC_VECTOR (23 downto 0);
        din47 : IN STD_LOGIC_VECTOR (23 downto 0);
        din48 : IN STD_LOGIC_VECTOR (23 downto 0);
        din49 : IN STD_LOGIC_VECTOR (23 downto 0);
        din50 : IN STD_LOGIC_VECTOR (23 downto 0);
        din51 : IN STD_LOGIC_VECTOR (23 downto 0);
        din52 : IN STD_LOGIC_VECTOR (23 downto 0);
        din53 : IN STD_LOGIC_VECTOR (23 downto 0);
        din54 : IN STD_LOGIC_VECTOR (23 downto 0);
        din55 : IN STD_LOGIC_VECTOR (23 downto 0);
        din56 : IN STD_LOGIC_VECTOR (23 downto 0);
        din57 : IN STD_LOGIC_VECTOR (23 downto 0);
        din58 : IN STD_LOGIC_VECTOR (23 downto 0);
        din59 : IN STD_LOGIC_VECTOR (23 downto 0);
        din60 : IN STD_LOGIC_VECTOR (23 downto 0);
        din61 : IN STD_LOGIC_VECTOR (23 downto 0);
        din62 : IN STD_LOGIC_VECTOR (23 downto 0);
        din63 : IN STD_LOGIC_VECTOR (23 downto 0);
        def : IN STD_LOGIC_VECTOR (23 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component top_kernel_sparsemux_33_4_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        din3 : IN STD_LOGIC_VECTOR (23 downto 0);
        din4 : IN STD_LOGIC_VECTOR (23 downto 0);
        din5 : IN STD_LOGIC_VECTOR (23 downto 0);
        din6 : IN STD_LOGIC_VECTOR (23 downto 0);
        din7 : IN STD_LOGIC_VECTOR (23 downto 0);
        din8 : IN STD_LOGIC_VECTOR (23 downto 0);
        din9 : IN STD_LOGIC_VECTOR (23 downto 0);
        din10 : IN STD_LOGIC_VECTOR (23 downto 0);
        din11 : IN STD_LOGIC_VECTOR (23 downto 0);
        din12 : IN STD_LOGIC_VECTOR (23 downto 0);
        din13 : IN STD_LOGIC_VECTOR (23 downto 0);
        din14 : IN STD_LOGIC_VECTOR (23 downto 0);
        din15 : IN STD_LOGIC_VECTOR (23 downto 0);
        def : IN STD_LOGIC_VECTOR (23 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component top_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_24s_24s_48_1_1_U296 : component top_kernel_mul_24s_24s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        dout_WIDTH => 48)
    port map (
        din0 => tmp_2_reg_1869,
        din1 => tmp_1_fu_1461_p35,
        dout => mul_ln90_fu_1054_p2);

    sparsemux_129_6_24_1_1_U297 : component top_kernel_sparsemux_129_6_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "000000",
        din0_WIDTH => 24,
        CASE1 => "000001",
        din1_WIDTH => 24,
        CASE2 => "000010",
        din2_WIDTH => 24,
        CASE3 => "000011",
        din3_WIDTH => 24,
        CASE4 => "000100",
        din4_WIDTH => 24,
        CASE5 => "000101",
        din5_WIDTH => 24,
        CASE6 => "000110",
        din6_WIDTH => 24,
        CASE7 => "000111",
        din7_WIDTH => 24,
        CASE8 => "001000",
        din8_WIDTH => 24,
        CASE9 => "001001",
        din9_WIDTH => 24,
        CASE10 => "001010",
        din10_WIDTH => 24,
        CASE11 => "001011",
        din11_WIDTH => 24,
        CASE12 => "001100",
        din12_WIDTH => 24,
        CASE13 => "001101",
        din13_WIDTH => 24,
        CASE14 => "001110",
        din14_WIDTH => 24,
        CASE15 => "001111",
        din15_WIDTH => 24,
        CASE16 => "010000",
        din16_WIDTH => 24,
        CASE17 => "010001",
        din17_WIDTH => 24,
        CASE18 => "010010",
        din18_WIDTH => 24,
        CASE19 => "010011",
        din19_WIDTH => 24,
        CASE20 => "010100",
        din20_WIDTH => 24,
        CASE21 => "010101",
        din21_WIDTH => 24,
        CASE22 => "010110",
        din22_WIDTH => 24,
        CASE23 => "010111",
        din23_WIDTH => 24,
        CASE24 => "011000",
        din24_WIDTH => 24,
        CASE25 => "011001",
        din25_WIDTH => 24,
        CASE26 => "011010",
        din26_WIDTH => 24,
        CASE27 => "011011",
        din27_WIDTH => 24,
        CASE28 => "011100",
        din28_WIDTH => 24,
        CASE29 => "011101",
        din29_WIDTH => 24,
        CASE30 => "011110",
        din30_WIDTH => 24,
        CASE31 => "011111",
        din31_WIDTH => 24,
        CASE32 => "100000",
        din32_WIDTH => 24,
        CASE33 => "100001",
        din33_WIDTH => 24,
        CASE34 => "100010",
        din34_WIDTH => 24,
        CASE35 => "100011",
        din35_WIDTH => 24,
        CASE36 => "100100",
        din36_WIDTH => 24,
        CASE37 => "100101",
        din37_WIDTH => 24,
        CASE38 => "100110",
        din38_WIDTH => 24,
        CASE39 => "100111",
        din39_WIDTH => 24,
        CASE40 => "101000",
        din40_WIDTH => 24,
        CASE41 => "101001",
        din41_WIDTH => 24,
        CASE42 => "101010",
        din42_WIDTH => 24,
        CASE43 => "101011",
        din43_WIDTH => 24,
        CASE44 => "101100",
        din44_WIDTH => 24,
        CASE45 => "101101",
        din45_WIDTH => 24,
        CASE46 => "101110",
        din46_WIDTH => 24,
        CASE47 => "101111",
        din47_WIDTH => 24,
        CASE48 => "110000",
        din48_WIDTH => 24,
        CASE49 => "110001",
        din49_WIDTH => 24,
        CASE50 => "110010",
        din50_WIDTH => 24,
        CASE51 => "110011",
        din51_WIDTH => 24,
        CASE52 => "110100",
        din52_WIDTH => 24,
        CASE53 => "110101",
        din53_WIDTH => 24,
        CASE54 => "110110",
        din54_WIDTH => 24,
        CASE55 => "110111",
        din55_WIDTH => 24,
        CASE56 => "111000",
        din56_WIDTH => 24,
        CASE57 => "111001",
        din57_WIDTH => 24,
        CASE58 => "111010",
        din58_WIDTH => 24,
        CASE59 => "111011",
        din59_WIDTH => 24,
        CASE60 => "111100",
        din60_WIDTH => 24,
        CASE61 => "111101",
        din61_WIDTH => 24,
        CASE62 => "111110",
        din62_WIDTH => 24,
        CASE63 => "111111",
        din63_WIDTH => 24,
        def_WIDTH => 24,
        sel_WIDTH => 6,
        dout_WIDTH => 24)
    port map (
        din0 => scale_reload,
        din1 => scale_1_reload,
        din2 => scale_2_reload,
        din3 => scale_3_reload,
        din4 => scale_4_reload,
        din5 => scale_5_reload,
        din6 => scale_6_reload,
        din7 => scale_7_reload,
        din8 => scale_8_reload,
        din9 => scale_9_reload,
        din10 => scale_10_reload,
        din11 => scale_11_reload,
        din12 => scale_12_reload,
        din13 => scale_13_reload,
        din14 => scale_14_reload,
        din15 => scale_15_reload,
        din16 => scale_16_reload,
        din17 => scale_17_reload,
        din18 => scale_18_reload,
        din19 => scale_19_reload,
        din20 => scale_20_reload,
        din21 => scale_21_reload,
        din22 => scale_22_reload,
        din23 => scale_23_reload,
        din24 => scale_24_reload,
        din25 => scale_25_reload,
        din26 => scale_26_reload,
        din27 => scale_27_reload,
        din28 => scale_28_reload,
        din29 => scale_29_reload,
        din30 => scale_30_reload,
        din31 => scale_31_reload,
        din32 => scale_32_reload,
        din33 => scale_33_reload,
        din34 => scale_34_reload,
        din35 => scale_35_reload,
        din36 => scale_36_reload,
        din37 => scale_37_reload,
        din38 => scale_38_reload,
        din39 => scale_39_reload,
        din40 => scale_40_reload,
        din41 => scale_41_reload,
        din42 => scale_42_reload,
        din43 => scale_43_reload,
        din44 => scale_44_reload,
        din45 => scale_45_reload,
        din46 => scale_46_reload,
        din47 => scale_47_reload,
        din48 => scale_48_reload,
        din49 => scale_49_reload,
        din50 => scale_50_reload,
        din51 => scale_51_reload,
        din52 => scale_52_reload,
        din53 => scale_53_reload,
        din54 => scale_54_reload,
        din55 => scale_55_reload,
        din56 => scale_56_reload,
        din57 => scale_57_reload,
        din58 => scale_58_reload,
        din59 => scale_59_reload,
        din60 => scale_60_reload,
        din61 => scale_61_reload,
        din62 => scale_62_reload,
        din63 => scale_63_reload,
        def => tmp_2_fu_1176_p129,
        sel => tmp_2_fu_1176_p130,
        dout => tmp_2_fu_1176_p131);

    sparsemux_33_4_24_1_1_U298 : component top_kernel_sparsemux_33_4_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 24,
        CASE1 => "0001",
        din1_WIDTH => 24,
        CASE2 => "0010",
        din2_WIDTH => 24,
        CASE3 => "0011",
        din3_WIDTH => 24,
        CASE4 => "0100",
        din4_WIDTH => 24,
        CASE5 => "0101",
        din5_WIDTH => 24,
        CASE6 => "0110",
        din6_WIDTH => 24,
        CASE7 => "0111",
        din7_WIDTH => 24,
        CASE8 => "1000",
        din8_WIDTH => 24,
        CASE9 => "1001",
        din9_WIDTH => 24,
        CASE10 => "1010",
        din10_WIDTH => 24,
        CASE11 => "1011",
        din11_WIDTH => 24,
        CASE12 => "1100",
        din12_WIDTH => 24,
        CASE13 => "1101",
        din13_WIDTH => 24,
        CASE14 => "1110",
        din14_WIDTH => 24,
        CASE15 => "1111",
        din15_WIDTH => 24,
        def_WIDTH => 24,
        sel_WIDTH => 4,
        dout_WIDTH => 24)
    port map (
        din0 => top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_9_q0,
        din1 => top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_8_q0,
        din2 => top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_q0,
        din3 => top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_q0,
        din4 => top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_q0,
        din5 => top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_q0,
        din6 => top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_q0,
        din7 => top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_q0,
        din8 => top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_q0,
        din9 => top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_q0,
        din10 => p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_5_q0,
        din11 => p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_4_q0,
        din12 => p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_3_q0,
        din13 => p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_2_q0,
        din14 => p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_1_q0,
        din15 => p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_s_q0,
        def => tmp_1_fu_1461_p33,
        sel => trunc_ln88_2_reg_1784,
        dout => tmp_1_fu_1461_p35);

    flow_control_loop_pipe_sequential_init_U : component top_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_fu_440_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln87_fu_1080_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_440 <= select_ln87_1_fu_1118_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_440 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten6_fu_444_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln87_fu_1080_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten6_fu_444 <= add_ln87_1_fu_1086_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_444 <= ap_const_lv15_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_436_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln87_fu_1080_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_436 <= add_ln88_fu_1440_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_436 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln90_reg_1879 <= add_ln90_fu_1579_p2;
                and_ln90_3_reg_1894 <= and_ln90_3_fu_1693_p2;
                and_ln90_4_reg_1900 <= and_ln90_4_fu_1699_p2;
                and_ln90_reg_1884 <= and_ln90_fu_1599_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln90_1_reg_1889 <= icmp_ln90_1_fu_1635_p2;
                tmp_2_reg_1869 <= tmp_2_fu_1176_p131;
                tmp_reg_1874 <= mul_ln90_fu_1054_p2(47 downto 47);
                trunc_ln88_2_reg_1784 <= trunc_ln88_2_fu_1134_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                select_ln90_3_reg_1905 <= select_ln90_3_fu_1737_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    C_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_C_0_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            C_blk_n_W <= m_axi_C_0_WREADY;
        else 
            C_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    add_ln87_1_fu_1086_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv15_1));
    add_ln87_fu_1098_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv9_1));
    add_ln88_fu_1440_p2 <= std_logic_vector(unsigned(select_ln87_fu_1110_p3) + unsigned(ap_const_lv7_1));
    add_ln90_fu_1579_p2 <= std_logic_vector(unsigned(trunc_ln5_fu_1549_p4) + unsigned(zext_ln90_fu_1575_p1));
    and_ln90_1_fu_1661_p2 <= (xor_ln90_1_fu_1655_p2 and icmp_ln90_fu_1621_p2);
    and_ln90_2_fu_1705_p2 <= (icmp_ln90_1_reg_1889 and and_ln90_reg_1884);
    and_ln90_3_fu_1693_p2 <= (xor_ln90_3_fu_1687_p2 and or_ln90_fu_1681_p2);
    and_ln90_4_fu_1699_p2 <= (tmp_5_fu_1585_p3 and select_ln90_1_fu_1667_p3);
    and_ln90_5_fu_1720_p2 <= (xor_ln90_4_fu_1714_p2 and tmp_reg_1874);
    and_ln90_fu_1599_p2 <= (xor_ln90_fu_1593_p2 and tmp_4_fu_1567_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_C_0_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_C_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_C_0_WREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((m_axi_C_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_C_0_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_C_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln87_fu_1080_p2)
    begin
        if (((icmp_ln87_fu_1080_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_440)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_440;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten6_fu_444)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv15_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_444;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_436, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_436;
        end if; 
    end process;

    icmp_ln87_fu_1080_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = ap_const_lv15_4000) else "0";
    icmp_ln88_fu_1104_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv7_40) else "0";
    icmp_ln90_1_fu_1635_p2 <= "1" when (tmp_8_fu_1627_p3 = ap_const_lv10_3FF) else "0";
    icmp_ln90_2_fu_1641_p2 <= "1" when (tmp_8_fu_1627_p3 = ap_const_lv10_0) else "0";
    icmp_ln90_fu_1621_p2 <= "1" when (tmp_7_fu_1613_p3 = ap_const_lv9_1FF) else "0";
    lshr_ln1_fu_1138_p4 <= select_ln87_fu_1110_p3(5 downto 4);
    m_axi_C_0_ARADDR <= ap_const_lv64_0;
    m_axi_C_0_ARBURST <= ap_const_lv2_0;
    m_axi_C_0_ARCACHE <= ap_const_lv4_0;
    m_axi_C_0_ARID <= ap_const_lv1_0;
    m_axi_C_0_ARLEN <= ap_const_lv32_0;
    m_axi_C_0_ARLOCK <= ap_const_lv2_0;
    m_axi_C_0_ARPROT <= ap_const_lv3_0;
    m_axi_C_0_ARQOS <= ap_const_lv4_0;
    m_axi_C_0_ARREGION <= ap_const_lv4_0;
    m_axi_C_0_ARSIZE <= ap_const_lv3_0;
    m_axi_C_0_ARUSER <= ap_const_lv1_0;
    m_axi_C_0_ARVALID <= ap_const_logic_0;
    m_axi_C_0_AWADDR <= ap_const_lv64_0;
    m_axi_C_0_AWBURST <= ap_const_lv2_0;
    m_axi_C_0_AWCACHE <= ap_const_lv4_0;
    m_axi_C_0_AWID <= ap_const_lv1_0;
    m_axi_C_0_AWLEN <= ap_const_lv32_0;
    m_axi_C_0_AWLOCK <= ap_const_lv2_0;
    m_axi_C_0_AWPROT <= ap_const_lv3_0;
    m_axi_C_0_AWQOS <= ap_const_lv4_0;
    m_axi_C_0_AWREGION <= ap_const_lv4_0;
    m_axi_C_0_AWSIZE <= ap_const_lv3_0;
    m_axi_C_0_AWUSER <= ap_const_lv1_0;
    m_axi_C_0_AWVALID <= ap_const_logic_0;
    m_axi_C_0_BREADY <= ap_const_logic_0;
    m_axi_C_0_RREADY <= ap_const_logic_0;
    m_axi_C_0_WDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln90_3_reg_1905),32));
    m_axi_C_0_WID <= ap_const_lv1_0;
    m_axi_C_0_WLAST <= ap_const_logic_0;
    m_axi_C_0_WSTRB <= ap_const_lv4_F;
    m_axi_C_0_WUSER <= ap_const_lv1_0;

    m_axi_C_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            m_axi_C_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_C_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln90_1_fu_1732_p2 <= (and_ln90_5_fu_1720_p2 or and_ln90_3_reg_1894);
    or_ln90_2_fu_1709_p2 <= (and_ln90_4_reg_1900 or and_ln90_2_fu_1705_p2);
    or_ln90_fu_1681_p2 <= (xor_ln90_2_fu_1675_p2 or tmp_5_fu_1585_p3);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_1_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_1_ce0 <= p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_1_ce0_local;

    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_2_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_2_ce0 <= p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_2_ce0_local;

    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_3_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_3_ce0 <= p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_3_ce0_local;

    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_4_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_4_ce0 <= p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_4_ce0_local;

    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_4_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_5_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_5_ce0 <= p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_5_ce0_local;

    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_5_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_s_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_s_ce0 <= p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_s_ce0_local;

    p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_s_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_s_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ10top_kernelPA64_8ap_fixedILi24ELi10EL9ap_q_mode0EL9ap_o_mode0ELi0EES4_E3tmp_s_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln87_1_fu_1118_p3 <= 
        add_ln87_fu_1098_p2 when (icmp_ln88_fu_1104_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln87_fu_1110_p3 <= 
        ap_const_lv7_0 when (icmp_ln88_fu_1104_p2(0) = '1') else 
        ap_sig_allocacmp_j_load;
    select_ln90_1_fu_1667_p3 <= 
        and_ln90_1_fu_1661_p2 when (and_ln90_fu_1599_p2(0) = '1') else 
        icmp_ln90_1_fu_1635_p2;
    select_ln90_2_fu_1725_p3 <= 
        ap_const_lv24_7FFFFF when (and_ln90_3_reg_1894(0) = '1') else 
        ap_const_lv24_800000;
    select_ln90_3_fu_1737_p3 <= 
        select_ln90_2_fu_1725_p3 when (or_ln90_1_fu_1732_p2(0) = '1') else 
        add_ln90_reg_1879;
    select_ln90_fu_1647_p3 <= 
        icmp_ln90_1_fu_1635_p2 when (and_ln90_fu_1599_p2(0) = '1') else 
        icmp_ln90_2_fu_1641_p2;
    tmp_1_fu_1461_p33 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_2_fu_1176_p129 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_2_fu_1176_p130 <= select_ln87_fu_1110_p3(6 - 1 downto 0);
    tmp_3_fu_1559_p3 <= mul_ln90_fu_1054_p2(13 downto 13);
    tmp_4_fu_1567_p3 <= mul_ln90_fu_1054_p2(37 downto 37);
    tmp_5_fu_1585_p3 <= add_ln90_fu_1579_p2(23 downto 23);
    tmp_6_fu_1605_p3 <= mul_ln90_fu_1054_p2(38 downto 38);
    tmp_7_fu_1613_p3 <= mul_ln90_fu_1054_p2(47 downto 39);
    tmp_8_fu_1627_p3 <= mul_ln90_fu_1054_p2(47 downto 38);
    tmp_fu_1541_p3 <= mul_ln90_fu_1054_p2(47 downto 47);
    tmp_s_fu_1148_p3 <= (trunc_ln88_fu_1126_p1 & lshr_ln1_fu_1138_p4);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0 <= top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0_local;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0_local <= ap_const_logic_1;
        else 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0 <= top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0_local;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0_local <= ap_const_logic_1;
        else 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0 <= top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0_local;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0_local <= ap_const_logic_1;
        else 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0 <= top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0_local;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0_local <= ap_const_logic_1;
        else 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0 <= top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0_local;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0_local <= ap_const_logic_1;
        else 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0 <= top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0_local;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0_local <= ap_const_logic_1;
        else 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0 <= top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0_local;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0_local <= ap_const_logic_1;
        else 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_8_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_8_ce0 <= top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_8_ce0_local;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_8_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_8_ce0_local <= ap_const_logic_1;
        else 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_9_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_9_ce0 <= top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_9_ce0_local;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_9_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_9_ce0_local <= ap_const_logic_1;
        else 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_address0 <= zext_ln90_2_fu_1156_p1(10 - 1 downto 0);
    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0 <= top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0_local;

    top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0_local <= ap_const_logic_1;
        else 
            top_kernel_ap_fixed_64_ap_fixed_24_10_0_0_0_64_tmp_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln5_fu_1549_p4 <= mul_ln90_fu_1054_p2(37 downto 14);
    trunc_ln88_2_fu_1134_p1 <= select_ln87_fu_1110_p3(4 - 1 downto 0);
    trunc_ln88_fu_1126_p1 <= select_ln87_1_fu_1118_p3(8 - 1 downto 0);
    xor_ln90_1_fu_1655_p2 <= (tmp_6_fu_1605_p3 xor ap_const_lv1_1);
    xor_ln90_2_fu_1675_p2 <= (select_ln90_fu_1647_p3 xor ap_const_lv1_1);
    xor_ln90_3_fu_1687_p2 <= (tmp_fu_1541_p3 xor ap_const_lv1_1);
    xor_ln90_4_fu_1714_p2 <= (or_ln90_2_fu_1709_p2 xor ap_const_lv1_1);
    xor_ln90_fu_1593_p2 <= (tmp_5_fu_1585_p3 xor ap_const_lv1_1);
    zext_ln90_2_fu_1156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_1148_p3),64));
    zext_ln90_fu_1575_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_1559_p3),24));
end behav;
